import requests
import pandas as pd

# 输入数据：省份、学校名称、网址
data = """
北京	北京大学	https://www.pku.edu.cn/
北京	中国人民大学	https://www.ruc.edu.cn/
北京	清华大学	https://www.tsinghua.edu.cn/
北京	北京交通大学	https://www.bjtu.edu.cn/
北京	北京工业大学	https://www.bjut.edu.cn/
北京	北京航空航天大学	https://www.buaa.edu.cn/
北京	北京理工大学	https://www.bit.edu.cn/
北京	北京科技大学	https://www.ustb.edu.cn/
北京	北方工业大学	https://www.ncut.edu.cn/
北京	北京化工大学	https://www.buct.edu.cn/
北京	北京工商大学	https://www.btbu.edu.cn/
北京	北京服装学院	https://www.bift.edu.cn/
北京	北京邮电大学	https://www.bupt.edu.cn/
北京	北京印刷学院	https://www.bigc.edu.cn/
北京	北京建筑大学	https://www.bucea.edu.cn/
北京	北京石油化工学院	https://www.bipt.edu.cn/
北京	北京电子科技学院	https://www.besti.edu.cn/
北京	中国农业大学	https://www.cau.edu.cn/
北京	北京农学院	https://www.bua.edu.cn/
北京	北京林业大学	https://www.bjfu.edu.cn/
北京	北京协和医学院	https://www.pumc.edu.cn/
北京	首都医科大学	https://www.ccmu.edu.cn/
北京	北京中医药大学	https://www.bucm.edu.cn/
北京	北京师范大学	https://www.bnu.edu.cn/
北京	首都师范大学	https://www.cnu.edu.cn/
北京	首都体育学院	https://www.cupes.edu.cn/
北京	北京外国语大学	https://www.bfsu.edu.cn/
北京	北京第二外国语学院	https://www.bisu.edu.cn/
北京	北京语言大学	https://www.blcu.edu.cn/
北京	中国传媒大学	https://www.cuc.edu.cn/
北京	中央财经大学	https://www.cufe.edu.cn/
北京	对外经济贸易大学	https://www.uibe.edu.cn/
北京	北京物资学院	https://www.bwu.edu.cn/
北京	首都经济贸易大学	https://www.cueb.edu.cn/
北京	中国消防救援学院	https://www.cfri.edu.cn/
北京	外交学院	https://www.cfau.edu.cn/
北京	中国人民公安大学	https://www.cppu.edu.cn/
北京	国际关系学院	https://www.uir.cn/
北京	北京体育大学	https://www.bsu.edu.cn/
北京	中央音乐学院	https://www.ccom.edu.cn/
北京	中国音乐学院	https://www.ccmusic.edu.cn/
北京	中央美术学院	https://www.cafa.edu.cn/
北京	中央戏剧学院	https://www.chntheatre.edu.cn/
北京	中国戏曲学院	https://www.nacta.edu.cn/
北京	北京电影学院	https://www.bfa.edu.cn/
北京	北京舞蹈学院	https://www.bda.edu.cn/
北京	中央民族大学	https://www.muc.edu.cn/
北京	中国政法大学	https://www.cupl.edu.cn/
北京	华北电力大学	https://www.ncepu.edu.cn/
北京	中华女子学院	https://www.cwu.edu.cn/
北京	北京信息科技大学	https://www.bistu.edu.cn/
北京	中国矿业大学（北京）	https://www.cumtb.edu.cn/
北京	中国石油大学（北京）	https://www.cup.edu.cn/
北京	中国地质大学（北京）	https://www.cugb.edu.cn/
北京	北京联合大学	https://www.buu.edu.cn/
北京	中国青年政治学院	http://www.cyu.edu.cn/
北京	首钢工学院	https://www.sgit.edu.cn/
北京	中国劳动关系学院	https://www.ciir.edu.cn/
北京	北京警察学院	https://www.bjpc.edu.cn/
北京	中国科学院大学	https://www.ucas.ac.cn/
北京	中国社会科学院大学	https://www.ucass.edu.cn/
北京	北京科技职业大学	https://www.bjtvu.edu.cn/
北京	民政职业大学	https://www.mzu.edu.cn/
北京	北京城市学院	https://www.bcu.edu.cn/
北京	首都师范大学科德学院	https://www.kdcnu.com/
北京	北京金融科技学院	https://www.bjft.edu.cn/
北京	北京邮电大学世纪学院	https://www.buptsj.edu.cn/
北京	北京工业大学耿丹学院	https://www.gengdancollege.edu.cn/
北京	北京第二外国语学院中瑞酒店管理学院	https://www.bisu.edu.cn/
北京	北京工业职业技术学院	https://www.bgy.org.cn/
北京	北京信息职业技术学院	https://www.bitc.edu.cn/
北京	北京京北职业技术学院	https://www.bjzb.org.cn/
北京	北京交通职业技术学院	https://www.bjjt.edu.cn/
北京	北京青年政治学院	https://www.bjypc.edu.cn/
北京	北京农业职业学院	https://www.bvca.edu.cn/
北京	北京政法职业学院	https://www.bcpl.cn/
北京	北京财贸职业学院	https://www.bjczy.edu.cn/
北京	北京戏曲艺术职业学院	https://www.bjxx.com.cn/
北京	北京经济管理职业学院	https://www.biem.edu.cn/
北京	北京劳动保障职业学院	https://www.bjldxy.com/
北京	北京体育职业学院	https://www.bjtyxy.cn/
北京	北京交通运输职业学院	https://www.bjjtzy.edu.cn/
北京	北京卫生职业学院	https://www.bjwszy.cn/
北京	北京北大方正软件职业技术学院	https://www.pkfbj.com/
北京	北京经贸职业学院	https://www.bjjmxy.cn/
北京	北京经济技术职业学院	https://www.bjjd.edu.cn/
北京	北京汇佳职业学院	https://www.huijia.edu.cn/
北京	北京科技经营管理学院	https://www.bjkjxy.cn/
北京	北京科技职业学院	https://www.bjkj.edu.cn/
北京	北京培黎职业学院	https://www.bjpldx.edu.cn/
北京	北京艺术传媒职业学院	https://www.bjymxy.cn/
北京	北京网络职业学院	https://www.bjwlxy.cn/
天津	南开大学	https://www.nankai.edu.cn/
天津	天津大学	https://www.tju.edu.cn/
天津	天津科技大学	https://www.tust.edu.cn/
天津	天津工业大学	https://www.tjpu.edu.cn/
天津	中国民航大学	https://www.cauc.edu.cn/
天津	天津理工大学	https://www.tjut.edu.cn/
天津	天津农学院	https://www.tjau.edu.cn/
天津	天津医科大学	https://www.tmu.edu.cn/
天津	天津中医药大学	https://www.tjutcm.edu.cn/
天津	天津师范大学	https://www.tjnu.edu.cn/
天津	天津职业技术师范大学	https://www.tute.edu.cn/
天津	天津外国语大学	https://www.tjfsu.edu.cn/
天津	天津商业大学	https://www.tjcu.edu.cn/
天津	天津财经大学	https://www.tjufe.edu.cn/
天津	天津体育学院	https://www.tjus.edu.cn/
天津	天津音乐学院	https://www.tjmusic.edu.cn/
天津	天津美术学院	https://www.tjarts.edu.cn/
天津	天津城建大学	https://www.tjcu.edu.cn/
天津	天津中德应用技术大学	https://www.tsguas.edu.cn/
天津	天津天狮学院	https://www.tianshi.edu.cn/
天津	天津外国语大学滨海外事学院	https://www.tjfsu.edu.cn/
天津	天津传媒学院	https://www.tjcm.edu.cn/
天津	天津商业大学宝德学院	https://www.tjcu.edu.cn/
天津	天津医科大学临床医学院	https://www.tmu.edu.cn/
天津	南开大学滨海学院	https://binhai.nankai.edu.cn/
天津	天津师范大学津沽学院	https://www.tjnu.edu.cn/
天津	天津理工大学中环信息学院	https://www.tjut.edu.cn/
天津	北京科技大学天津学院	https://tj.ustb.edu.cn/
天津	天津仁爱学院	https://www.tjrac.edu.cn/
天津	天津财经大学珠江学院	https://www.tjufe.edu.cn/
天津	天津市职业大学	https://www.tjvc.edu.cn/
天津	天津滨海职业学院	https://www.tjbhzy.com/
天津	天津工程职业技术学院	https://www.tjetc.edu.cn/
天津	天津渤海职业技术学院	https://www.tjbhzyxy.com/
天津	天津电子信息职业技术学院	https://www.tjdz.net/
天津	天津机电职业技术学院	https://www.tjmec.edu.cn/
天津	天津现代职业技术学院	https://www.tjxz.edu.cn/
天津	天津公安警官职业学院	https://www.tjpa.edu.cn/
天津	天津轻工职业技术学院	https://www.tjlivtc.edu.cn/
天津	天津商务职业学院	https://www.tjbvc.edu.cn/
天津	天津国土资源和房屋职业学院	https://www.tjgtf.edu.cn/
天津	天津医学高等专科学校	https://www.tjyzh.cn/
天津	天津开发区职业技术学院	https://www.tjkfq.edu.cn/
天津	天津艺术职业学院	https://www.tjysxy.com/
天津	天津交通职业学院	https://www.tjjy.com.cn/
天津	天津工业职业学院	https://www.tjgyzyxy.cn/
天津	天津石油职业技术学院	https://www.tjsyxy.com/
天津	天津城市职业学院	https://www.tjcsxy.cn/
天津	天津铁道职业技术学院	https://www.tjtdzy.cn/
天津	天津工艺美术职业学院	https://www.tjgmxy.cn/
天津	天津城市建设管理职业技术学院	https://www.tjjsgl.edu.cn/
天津	天津生物工程职业技术学院	https://www.tjswgcxy.cn/
天津	天津海运职业学院	https://www.tjhyxy.com/
天津	天津广播影视职业学院	https://www.tjrftv.edu.cn/
天津	天津体育职业学院	https://www.tjtyzyxy.com/
天津	天津滨海汽车工程职业学院	https://www.tjbqgcxy.com/
上海	复旦大学	https://www.fudan.edu.cn/
上海	同济大学	https://www.tongji.edu.cn/
上海	上海交通大学	https://www.sjtu.edu.cn/
上海	华东理工大学	https://www.ecust.edu.cn/
上海	上海理工大学	https://www.usst.edu.cn/
上海	上海海事大学	https://www.shmtu.edu.cn/
上海	东华大学	https://www.dhu.edu.cn/
上海	上海电力大学	https://www.shiep.edu.cn/
上海	上海应用技术大学	https://www.sit.edu.cn/
上海	上海健康医学院	https://www.sumhs.edu.cn/
上海	上海海洋大学	https://www.shou.edu.cn/
上海	上海中医药大学	https://www.shutcm.edu.cn/
上海	华东师范大学	https://www.ecnu.edu.cn/
上海	上海师范大学	https://www.shnu.edu.cn/
上海	上海外国语大学	https://www.shisu.edu.cn/
上海	上海财经大学	https://www.shufe.edu.cn/
上海	上海对外经贸大学	https://www.suibe.edu.cn/
上海	上海海关学院	https://www.shcc.edu.cn/
上海	华东政法大学	https://www.ecupl.edu.cn/
上海	上海体育大学	https://www.sus.edu.cn/
上海	上海音乐学院	https://www.shcmusic.edu.cn/
上海	上海戏剧学院	https://www.sta.edu.cn/
上海	上海大学	https://www.shu.edu.cn/
上海	上海公安学院	https://www.shpc.edu.cn/
上海	上海工程技术大学	https://www.sues.edu.cn/
上海	上海立信会计金融学院	https://www.lixin.edu.cn/
上海	上海电机学院	https://www.sdju.edu.cn/
上海	上海政法学院	https://www.shupl.edu.cn/
上海	上海第二工业大学	https://www.sspu.edu.cn/
上海	上海商学院	https://www.sbs.edu.cn/
上海	上海科技大学	https://www.shanghaitech.edu.cn/
上海	海军军医大学	https://www.nmu.edu.cn/
上海	上海杉达学院	https://www.sandau.edu.cn/
上海	上海立达学院	https://www.lidapoly.edu.cn/
上海	上海建桥学院	https://www.gench.edu.cn/
上海	上海兴伟学院	https://www.xingwei.edu.cn/
上海	上海中侨职业技术大学	https://www.shzq.edu.cn/
上海	上海视觉艺术学院	https://www.siva.edu.cn/
上海	上海外国语大学贤达经济人文学院	https://www.xdshisu.edu.cn/
上海	上海师范大学天华学院	https://www.sthu.edu.cn/
上海	上海纽约大学	https://shanghai.nyu.edu/
上海	上海旅游高等专科学校	https://www.sitsh.edu.cn/
上海	上海出版印刷高等专科学校	https://www.sppc.edu.cn/
上海	上海行健职业学院	https://www.shxj.edu.cn/
上海	上海城建职业学院	https://www.succ.edu.cn/
上海	上海交通职业技术学院	https://www.sjjzy.sh.cn/
上海	上海海事职业技术学院	https://www.smvtc.edu.cn/
上海	上海电子信息职业技术学院	https://www.sheitc.edu.cn/
上海	上海工艺美术职业学院	https://www.shgymy.edu.cn/
上海	上海科学技术职业学院	https://www.shkjedu.cn/
上海	上海农林职业技术学院	https://www.shafc.edu.cn/
上海	上海工会管理职业学院	https://www.shghxy.edu.cn/
上海	上海民航职业技术学院	https://www.shcac.edu.cn/
上海	上海南湖职业技术学院	https://www.shnh.edu.cn/
上海	上海科创职业技术学院	https://www.shkczyxy.edu.cn/
上海	上海闵行职业技术学院	https://www.shmrzyxy.edu.cn/
上海	上海现代化工职业学院	https://www.shxdhgxy.edu.cn/
上海	上海建设管理职业技术学院	https://www.shjsglzy.edu.cn/
上海	上海浦东职业技术学院	https://www.shpdzy.edu.cn/
上海	上海东海职业技术学院	https://www.shedunxy.edu.cn/
上海	上海工商职业技术学院	https://www.sicp.edu.cn/
上海	上海震旦职业学院	https://www.shzdxy.edu.cn/
上海	上海民远职业技术学院	https://www.shmy.edu.cn/
上海	上海欧华职业技术学院	https://www.shouhua.edu.cn/
上海	上海思博职业技术学院	https://www.shsipo.edu.cn/
上海	上海济光职业技术学院	https://www.shjgu.edu.cn/
上海	上海工商外国语职业学院	https://www.sicfl.edu.cn/
上海	上海邦德职业技术学院	https://www.shbangde.edu.cn/
上海	上海电影艺术职业学院	https://www.shfilmart.edu.cn/
上海	上海中华职业技术学院	https://www.shzzy.edu.cn/
重庆	重庆大学	https://www.cqu.edu.cn/
重庆	重庆邮电大学	https://www.cqupt.edu.cn/
重庆	重庆交通大学	https://www.cqjtu.edu.cn/
重庆	重庆医科大学	https://www.cqmu.edu.cn/
重庆	西南大学	https://www.swu.edu.cn/
重庆	重庆师范大学	https://www.cqnu.edu.cn/
重庆	重庆文理学院	https://www.cqwu.edu.cn/
重庆	重庆三峡学院	https://www.sanxiau.edu.cn/
重庆	长江师范学院	https://www.yznu.edu.cn/
重庆	四川外国语大学	https://www.sisu.edu.cn/
重庆	西南政法大学	https://www.swupl.edu.cn/
重庆	四川美术学院	https://www.scfai.edu.cn/
重庆	重庆科技大学	https://www.cqust.edu.cn/
重庆	重庆理工大学	https://www.cqut.edu.cn/
重庆	重庆工商大学	https://www.ctbu.edu.cn/
重庆	重庆警察学院	https://www.cqpc.edu.cn/
重庆	重庆第二师范学院	https://www.cqsedu.cn/
重庆	重庆电子科技职业大学	https://www.cqeec.edu.cn/
重庆	陆军军医大学	https://www.tmmu.edu.cn/
重庆	重庆中医药学院	https://www.cqtcm.edu.cn/
重庆	重庆机电职业技术大学	https://www.cqjd.edu.cn/
重庆	重庆工程学院	https://www.cqie.edu.cn/
重庆	重庆城市科技学院	https://www.cqcst.edu.cn/
重庆	重庆人文科技学院	https://www.cqrk.edu.cn/
重庆	重庆外语外事学院	https://www.cqifs.edu.cn/
重庆	重庆对外经贸学院	https://www.cqdb.edu.cn/
重庆	重庆财经学院	https://www.cqcc.edu.cn/
重庆	重庆工商大学派斯学院	https://www.ctbu.edu.cn/
重庆	重庆移通学院	https://www.cqytu.edu.cn/
重庆	重庆航天职业技术学院	https://www.cqht.edu.cn/
重庆	重庆电力高等专科学校	https://www.cqepc.edu.cn/
重庆	重庆工业职业技术学院	https://www.cqipc.edu.cn/
重庆	重庆三峡职业学院	https://www.cqsxzy.edu.cn/
重庆	重庆工贸职业技术学院	https://www.cqgm.edu.cn/
重庆	重庆城市管理职业学院	https://www.cqc.edu.cn/
重庆	重庆工程职业技术学院	https://www.cqvie.edu.cn/
重庆	重庆城市职业学院	https://www.cqcy.edu.cn/
重庆	重庆水利电力职业技术学院	https://www.cqsdzy.edu.cn/
重庆	重庆工商职业学院	https://www.cqib.edu.cn/
重庆	重庆三峡医药高等专科学校	https://www.sxyyc.edu.cn/
重庆	重庆医药高等专科学校	https://www.cqyygz.com/
重庆	重庆青年职业技术学院	https://www.cqyzy.edu.cn/
重庆	重庆财经职业学院	https://www.cqcfe.edu.cn/
重庆	重庆建筑工程职业学院	https://www.cqjzc.edu.cn/
重庆	重庆商务职业学院	https://www.cqswxy.edu.cn/
重庆	重庆化工职业学院	https://www.cqhgc.edu.cn/
重庆	重庆旅游职业学院	https://www.cqtvc.edu.cn/
重庆	重庆安全技术职业学院	https://www.cqvit.edu.cn/
重庆	重庆幼儿师范高等专科学校	https://www.cqys.edu.cn/
重庆	重庆文化艺术职业学院	https://www.cqwy.edu.cn/
重庆	重庆工信职业学院	https://www.cqgx.edu.cn/
重庆	重庆五一职业技术学院	https://www.cq51.edu.cn/
重庆	重庆海联职业技术学院	https://www.cqhl.edu.cn/
重庆	重庆信息技术职业学院	https://www.cqitc.edu.cn/
重庆	重庆传媒职业学院	https://www.cqcmxy.edu.cn/
重庆	重庆建筑科技职业学院	https://www.cqjku.edu.cn/
重庆	重庆应用技术职业学院	https://www.cqyyc.edu.cn/
重庆	重庆科创职业学院	https://www.cqkczy.edu.cn/
重庆	重庆电讯职业学院	https://www.cqdx.edu.cn/
重庆	重庆能源职业学院	https://www.cqny.edu.cn/
重庆	重庆交通职业学院	https://www.cqjtedu.cn/
重庆	重庆公共运输职业学院	https://www.cqgy.edu.cn/
重庆	重庆艺术工程职业学院	https://www.cqygc.edu.cn/
重庆	重庆轻工职业学院	https://www.cqqg.edu.cn/
重庆	重庆电信职业学院	https://www.cqdxxy.edu.cn/
重庆	重庆经贸职业学院	https://www.cqjmc.edu.cn/
重庆	重庆科技职业学院	https://www.cqkji.edu.cn/
重庆	重庆资源与环境保护职业学院	https://www.cqzyhb.edu.cn/
重庆	重庆护理职业学院	https://www.cqhlzyxy.edu.cn/
重庆	重庆理工职业学院	https://www.cqlgzyxy.edu.cn/
重庆	重庆智能工程职业学院	https://www.cqzn.edu.cn/
重庆	重庆健康职业学院	https://www.cqjkedu.cn/
重庆	重庆数字产业职业技术学院	https://www.cqsz.edu.cn/
重庆	重庆现代制造职业学院	https://www.cqxzzy.edu.cn/
辽宁	辽宁大学	https://www.lnu.edu.cn/
辽宁	大连理工大学	https://www.dlut.edu.cn/
辽宁	沈阳工业大学	https://www.sut.edu.cn/
辽宁	沈阳航空航天大学	https://www.sau.edu.cn/
辽宁	沈阳理工大学	https://www.sylu.edu.cn/
辽宁	东北大学	https://www.neu.edu.cn/
辽宁	辽宁科技大学	https://www.ustl.edu.cn/
辽宁	辽宁工程技术大学	https://www.lntu.edu.cn/
辽宁	辽宁石油化工大学	https://www.lnpu.edu.cn/
辽宁	沈阳化工大学	https://www.sytu.edu.cn/
辽宁	大连交通大学	https://www.djtu.edu.cn/
辽宁	大连海事大学	https://www.dlmu.edu.cn/
辽宁	大连工业大学	https://www.dpu.edu.cn/
辽宁	沈阳建筑大学	https://www.sjzu.edu.cn/
辽宁	辽宁工业大学	https://www.lnut.edu.cn/
辽宁	沈阳农业大学	https://www.syau.edu.cn/
辽宁	大连海洋大学	https://www.dlou.edu.cn/
辽宁	中国医科大学	https://www.cmu.edu.cn/
辽宁	锦州医科大学	https://www.jzmu.edu.cn/
辽宁	大连医科大学	https://www.dmu.edu.cn/
辽宁	辽宁中医药大学	https://www.lnutcm.edu.cn/
辽宁	沈阳药科大学	https://www.syphu.edu.cn/
辽宁	沈阳医学院	https://www.symc.edu.cn/
辽宁	辽宁师范大学	https://www.lnnu.edu.cn/
辽宁	沈阳师范大学	https://www.synu.edu.cn/
辽宁	渤海大学	https://www.bhu.edu.cn/
辽宁	鞍山师范学院	https://www.asnc.edu.cn/
辽宁	大连外国语大学	https://www.dlufl.edu.cn/
辽宁	东北财经大学	https://www.dufe.edu.cn/
辽宁	中国刑事警察学院	https://www.cipcc.edu.cn/
辽宁	沈阳体育学院	https://www.syty.edu.cn/
辽宁	沈阳音乐学院	https://www.sycm.edu.cn/
辽宁	鲁迅美术学院	https://www.lumei.edu.cn/
辽宁	沈阳大学	https://www.syu.edu.cn/
辽宁	大连大学	https://www.dlu.edu.cn/
辽宁	辽宁科技学院	https://www.lnist.edu.cn/
辽宁	辽宁警察学院	https://www.lnpc.edu.cn/
辽宁	沈阳工程学院	https://www.sie.edu.cn/
辽宁	辽东学院	https://www.ldxy.edu.cn/
辽宁	大连民族大学	https://www.dlnu.edu.cn/
辽宁	营口理工学院	https://www.yku.edu.cn/
辽宁	朝阳师范学院	https://www.cynu.edu.cn/
辽宁	辽宁对外经贸学院	https://www.luibe.edu.cn/
辽宁	辽宁理工职业大学	https://www.lnlg.edu.cn/
辽宁	大连理工大学城市学院	https://www.dlutcity.edu.cn/
辽宁	沈阳工业大学工程学院	https://www.sut.edu.cn/
辽宁	沈阳航空航天大学北方科技学院	https://www.sau.edu.cn/
辽宁	沈阳工学院	https://www.syist.edu.cn/
辽宁	大连工业大学艺术与信息工程学院	https://www.dpu.edu.cn/
辽宁	大连科技学院	https://www.dlkj.edu.cn/
辽宁	沈阳城市建设学院	https://www.sycu.edu.cn/
辽宁	大连医科大学中山学院	https://www.dmu.edu.cn/
辽宁	锦州医科大学医疗学院	https://www.jzmu.edu.cn/
辽宁	辽宁师范大学海华学院	https://www.lnnu.edu.cn/
辽宁	辽宁理工学院	https://www.lnli.edu.cn/
辽宁	大连财经学院	https://www.dlufe.edu.cn/
辽宁	沈阳城市学院	https://www.sysu.edu.cn/
辽宁	大连艺术学院	https://www.dlau.edu.cn/
辽宁	辽宁中医药大学杏林学院	https://www.lnutcm.edu.cn/
辽宁	辽宁何氏医学院	https://www.hvmu.edu.cn/
辽宁	沈阳科技学院	https://www.syst.edu.cn/
辽宁	大连东软信息学院	https://www.neusoft.edu.cn/
辽宁	辽宁财贸学院	https://www.lncm.edu.cn/
辽宁	辽宁传媒学院	https://www.lncu.edu.cn/
辽宁	抚顺师范高等专科学校	https://www.fsnc.edu.cn/
辽宁	锦州师范高等专科学校	https://www.jzsz.edu.cn/
辽宁	营口职业技术学院	https://www.ykdx.edu.cn/
辽宁	铁岭师范高等专科学校	https://www.tlsz.edu.cn/
辽宁	大连职业技术学院	https://www.dlvtc.edu.cn/
辽宁	辽宁农业职业技术学院	https://www.lnnzy.ln.cn/
辽宁	抚顺职业技术学院	https://www.fszyxy.edu.cn/
辽宁	辽阳职业技术学院	https://www.lypt.edu.cn/
辽宁	阜新高等专科学校	https://www.fxgz.com.cn/
辽宁	辽宁省交通高等专科学校	https://www.lncc.edu.cn/
辽宁	辽宁税务高等专科学校	https://www.lntc.edu.cn/
辽宁	盘锦职业技术学院	https://www.pjvtc.edu.cn/
辽宁	沈阳航空职业技术学院	https://www.savs.edu.cn/
辽宁	辽宁体育运动职业技术学院	https://www.lnty.edu.cn/
辽宁	辽宁职业学院	https://www.lnzy.edu.cn/
辽宁	辽宁生态工程职业学院	https://www.lnsth.edu.cn/
辽宁	沈阳职业技术学院	https://www.syz.edu.cn/
辽宁	辽宁金融职业学院	https://www.lnjrzy.edu.cn/
辽宁	辽宁轨道交通职业学院	https://www.lngdzy.edu.cn/
辽宁	辽宁机电职业技术学院	https://www.lnjd.edu.cn/
辽宁	辽宁经济职业技术学院	https://www.lnjjxy.edu.cn/
辽宁	辽宁石化职业技术学院	https://www.lnshzy.edu.cn/
辽宁	渤海船舶职业学院	https://www.bhcy.edu.cn/
辽宁	辽宁商贸职业学院	https://www.lnsmzy.edu.cn/
辽宁	辽宁装备制造职业技术学院	https://www.lnzb.edu.cn/
辽宁	辽河石油职业技术学院	https://www.lhsyzy.edu.cn/
辽宁	辽宁地质工程职业学院	https://www.lndzxy.edu.cn/
辽宁	辽宁铁道职业技术学院	https://www.lntd.edu.cn/
辽宁	辽宁建筑职业学院	https://www.lnjzxy.edu.cn/
辽宁	辽宁现代服务职业技术学院	https://www.lnxdfw.edu.cn/
辽宁	辽宁冶金职业技术学院	https://www.lnyjzy.edu.cn/
辽宁	辽宁工程职业学院	https://www.lngczy.edu.cn/
辽宁	辽宁城市建设职业技术学院	https://www.lncj.edu.cn/
辽宁	辽宁医药职业学院	https://www.lnyyzy.edu.cn/
辽宁	铁岭卫生职业学院	https://www.tlwzyxy.edu.cn/
辽宁	辽宁政法职业学院	https://www.lnzfxy.edu.cn/
辽宁	辽宁民族师范高等专科学校	https://www.lnmzsz.edu.cn/
辽宁	辽宁轻工职业学院	https://www.lnqg.edu.cn/
辽宁	辽宁特殊教育师范高等专科学校	https://www.lnts.edu.cn/
辽宁	辽宁师范高等专科学校	https://www.lnsf.edu.cn/
辽宁	鞍山职业技术学院	https://www.aszy.edu.cn/
辽宁	大连商务职业学院	https://www.dlswzy.edu.cn/
辽宁	辽宁广告职业学院	https://www.lnggzy.edu.cn/
辽宁	大连软件职业学院	https://www.dlruan.edu.cn/
辽宁	大连翻译职业学院	https://www.dlfyzy.edu.cn/
辽宁	大连枫叶职业技术学院	https://www.dlfy.edu.cn/
辽宁	大连航运职业技术学院	https://www.dlhyzy.edu.cn/
辽宁	大连装备制造职业技术学院	https://www.dlzzy.edu.cn/
辽宁	大连汽车职业技术学院	https://www.dlqczy.edu.cn/
辽宁	沈阳北软信息职业技术学院	https://www.sybr.edu.cn/
吉林	吉林大学	https://www.jlu.edu.cn/
吉林	延边大学	https://www.ybu.edu.cn/
吉林	长春理工大学	https://www.ccut.edu.cn/
吉林	东北电力大学	https://www.nedu.edu.cn/
吉林	长春工业大学	https://www.ccut.edu.cn/
吉林	吉林建筑大学	https://www.jliae.edu.cn/
吉林	吉林化工学院	https://www.jlju.edu.cn/
吉林	吉林农业大学	https://www.jlau.edu.cn/
吉林	长春中医药大学	https://www.ccucm.edu.cn/
吉林	东北师范大学	https://www.nenu.edu.cn/
吉林	北华大学	https://www.beihua.edu.cn/
吉林	通化师范学院	https://www.thnu.edu.cn/
吉林	吉林师范大学	https://www.jlnu.edu.cn/
吉林	吉林工程技术师范学院	https://www.jlntu.edu.cn/
吉林	长春师范大学	https://www.ccsfu.edu.cn/
吉林	白城师范学院	https://www.bcsfxy.edu.cn/
吉林	吉林财经大学	https://www.jlufc.edu.cn/
吉林	吉林体育学院	https://www.jlty.edu.cn/
吉林	吉林艺术学院	https://www.jlart.edu.cn/
吉林	吉林工商学院	https://www.jlbtc.edu.cn/
吉林	长春工程学院	https://www.ccit.edu.cn/
吉林	吉林农业科技学院	https://www.jlnku.edu.cn/
吉林	吉林警察学院	https://www.jlpc.edu.cn/
吉林	长春大学	https://www.ccu.edu.cn/
吉林	吉林医药学院	https://www.jlmu.edu.cn/
吉林	长春汽车职业技术大学	https://www.ccqzu.edu.cn/
吉林	长春职业技术大学	https://www.cczyjs.edu.cn/
吉林	吉林铁道职业技术大学	https://www.jltdzy.edu.cn/
吉林	吉林外国语大学	https://www.huawai.edu.cn/
吉林	长春光华学院	https://www.ccugh.edu.cn/
吉林	长春工业大学人文信息学院	https://www.ccut.edu.cn/
吉林	长春电子科技学院	https://www.ccdzy.edu.cn/
吉林	长春财经学院	https://www.cccj.edu.cn/
吉林	吉林建筑科技学院	https://www.jlji.edu.cn/
吉林	长春建筑学院	https://www.jladi.edu.cn/
吉林	长春科技学院	https://www.ccst.edu.cn/
吉林	吉林动画学院	https://www.jldh.edu.cn/
吉林	吉林师范大学博达学院	https://www.jlnu.edu.cn/
吉林	长春大学旅游学院	https://www.ccu.edu.cn/
吉林	长春人文学院	https://www.ccrw.edu.cn/
吉林	长春师范高等专科学校	https://www.ccsfz.edu.cn/
吉林	辽源职业技术学院	https://www.lyzyjs.edu.cn/
吉林	四平职业大学	https://www.spzy.edu.cn/
吉林	长春金融高等专科学校	https://www.ccjr.edu.cn/
吉林	长春医学高等专科学校	https://www.ccyx.edu.cn/
吉林	吉林交通职业技术学院	https://www.jljy.edu.cn/
吉林	吉林司法警官职业学院	https://www.jljt.edu.cn/
吉林	吉林电子信息职业技术学院	https://www.jldzxx.edu.cn/
吉林	吉林工业职业技术学院	https://www.jlvtc.edu.cn/
吉林	吉林工程职业学院	https://www.jlgczy.edu.cn/
吉林	白城医学高等专科学校	https://www.bcyz.edu.cn/
吉林	松原职业技术学院	https://www.syzyjs.edu.cn/
吉林	白城职业技术学院	https://www.bczyxy.edu.cn/
吉林	长白山职业技术学院	https://www.cbszy.edu.cn/
吉林	延边职业技术学院	https://www.ybzyxy.edu.cn/
吉林	吉林水利电力职业学院	https://www.jlsp.edu.cn/
吉林	吉林通用航空职业技术学院	https://www.jltyhk.edu.cn/
吉林	通化医药健康职业学院	https://www.thyyjk.edu.cn/
吉林	长春东方职业学院	https://www.dfzy.edu.cn/
吉林	长春信息技术职业学院	https://www.ccitc.edu.cn/
吉林	吉林科技职业技术学院	https://www.jlvt.edu.cn/
吉林	吉林城市职业技术学院	https://www.jlcszy.edu.cn/
吉林	吉林职业技术学院	https://www.jlzyjs.edu.cn/
吉林	长春健康职业学院	https://www.ccjkzy.edu.cn/
吉林	长春早期教育职业学院	https://www.cczqjy.edu.cn/
吉林	梅河口康美职业技术学院	https://www.mhkmy.edu.cn/
吉林	长春数字科技职业学院	https://www.ccszkj.edu.cn/
河北	河北大学	https://www.hbu.edu.cn/
河北	河北工程大学	https://www.hebeu.edu.cn/
河北	河北地质大学	https://www.hgu.edu.cn/
河北	河北工业大学	https://www.hebut.edu.cn/
河北	华北理工大学	https://www.ncst.edu.cn/
河北	河北科技大学	https://www.hebust.edu.cn/
河北	河北建筑工程学院	https://www.hebiace.edu.cn/
河北	河北水利电力学院	https://www.hbwe.edu.cn/
河北	河北农业大学	https://www.hebau.edu.cn/
河北	河北医科大学	https://www.hebmu.edu.cn/
河北	河北北方学院	https://www.hebeinu.edu.cn/
河北	承德医学院	https://www.cdmc.edu.cn/
河北	河北师范大学	https://www.hebtu.edu.cn/
河北	保定学院	https://www.bdu.edu.cn/
河北	河北民族师范学院	https://www.hbun.edu.cn/
河北	唐山师范学院	https://www.tstc.edu.cn/
河北	廊坊师范学院	https://www.lfsfxy.edu.cn/
河北	衡水学院	https://www.hsnc.edu.cn/
河北	石家庄学院	https://www.sjzc.edu.cn/
河北	邯郸学院	https://www.hdc.edu.cn/
河北	邢台学院	https://www.xttc.edu.cn/
河北	沧州师范学院	https://www.czsfc.edu.cn/
河北	石家庄铁道大学	https://www.stdu.edu.cn/
河北	燕山大学	https://www.ysu.edu.cn/
河北	河北科技师范学院	https://www.hevttc.edu.cn/
河北	唐山学院	https://www.tsc.edu.cn/
河北	华北科技学院	https://www.ncist.edu.cn/
河北	中国人民警察大学	https://www.cppu.edu.cn/
河北	河北体育学院	https://www.hepec.edu.cn/
河北	河北金融学院	https://www.hbfu.edu.cn/
河北	北华航天工业学院	https://www.nciae.edu.cn/
河北	防灾科技学院	https://www.cidp.edu.cn/
河北	河北经贸大学	https://www.heuet.edu.cn/
河北	中央司法警官学院	https://www.cj警院.edu.cn/
河北	河北工业职业技术大学	https://www.hbgy.edu.cn/
河北	河北科技工程职业技术大学	https://www.hbkju.edu.cn/
河北	河北石油职业技术大学	https://www.hbpu.edu.cn/
河北	河北中医药大学	https://www.hebcm.edu.cn/
河北	张家口学院	https://www.zjkxy.edu.cn/
河北	河北环境工程学院	https://www.hebuee.edu.cn/
河北	唐山工业职业技术大学	https://www.tsgzy.edu.cn/
河北	邢台医学院	https://www.xtmc.edu.cn/
河北	河北传媒学院	https://www.hebic.cn/
河北	河北工程技术学院	https://www.hbgc.edu.cn/
河北	河北美术学院	https://www.hbafa.com/
河北	河北科技学院	https://www.hbkj.edu.cn/
河北	河北外国语学院	https://www.hbwy.edu.cn/
河北	河北大学工商学院	https://www.hbu.edu.cn/
河北	华北理工大学轻工学院	https://www.ncst.edu.cn/
河北	河北师范大学汇华学院	https://www.hebtu.edu.cn/
河北	河北经贸大学经济管理学院	https://www.heuet.edu.cn/
河北	河北医科大学临床学院	https://www.hebmu.edu.cn/
河北	河北工程大学科信学院	https://www.hebeu.edu.cn/
河北	燕山大学里仁学院	https://www.ysu.edu.cn/
河北	石家庄铁道大学四方学院	https://www.stdu.edu.cn/
河北	河北地质大学华信学院	https://www.hgu.edu.cn/
河北	河北农业大学现代科技学院	https://www.hebau.edu.cn/
河北	华北理工大学冀唐学院	https://www.ncst.edu.cn/
河北	保定理工学院	https://www.bdlgy.edu.cn/
河北	燕京理工学院	https://www.yit.edu.cn/
河北	北京中医药大学东方学院	https://www.bucm.edu.cn/
河北	沧州交通学院	https://www.czjtu.edu.cn/
河北	河北东方学院	https://www.hbdfxy.edu.cn/
河北	邯郸职业技术学院	https://www.hdvtc.edu.cn/
河北	石家庄职业技术学院	https://www.sjzpt.edu.cn/
河北	张家口职业技术学院	https://www.zjkpt.edu.cn/
河北	河北软件职业技术学院	https://www.hbsi.edu.cn/
河北	河北石油职业技术学院	https://www.hboc.edu.cn/
河北	河北建材职业技术学院	https://www.hbjcxy.edu.cn/
河北	河北政法职业学院	https://www.hbfzxy.edu.cn/
河北	沧州职业技术学院	https://www.czvtc.edu.cn/
河北	河北能源职业技术学院	https://www.hbnyxy.edu.cn/
河北	石家庄铁路职业技术学院	https://www.srtvu.edu.cn/
河北	保定职业技术学院	https://www.bvtc.edu.cn/
河北	秦皇岛职业技术学院	https://www.qhdu.edu.cn/
河北	唐山职业技术学院	https://www.tsvtc.edu.cn/
河北	衡水职业技术学院	https://www.hszj.edu.cn/
河北	河北艺术职业学院	https://www.hbavc.edu.cn/
河北	河北旅游职业学院	https://www.hblyxy.edu.cn/
河北	河北交通职业技术学院	https://www.hbjty.edu.cn/
河北	河北化工医药职业技术学院	https://www.hbhgy.edu.cn/
河北	石家庄信息工程职业学院	https://www.sjziei.edu.cn/
河北	河北对外经贸职业学院	https://www.hbwf.edu.cn/
河北	保定电力职业技术学院	https://www.bddlxy.edu.cn/
河北	河北机电职业技术学院	https://www.hbjd.com.cn/
河北	渤海石油职业学院	https://www.bhsyxy.edu.cn/
河北	廊坊职业技术学院	https://www.lfzhj.edu.cn/
河北	唐山科技职业技术学院	https://www.tskjzy.edu.cn/
河北	石家庄邮电職業技術學院	https://www.sjzptc.edu.cn/
河北	河北公安警察职业学院	https://www.hbgat.edu.cn/
河北	河北司法警官职业学院	https://www.hbsfxy.edu.cn/
河北	沧州医学高等专科学校	https://www.czmc.edu.cn/
河北	河北女子职业技术学院	https://www.hbnz.edu.cn/
河北	冀中职业学院	https://www.jzzy.edu.cn/
河北	河北正定师范高等专科学校	https://www.hbzd.edu.cn/
河北	河北劳动关系职业学院	https://www.hbld.edu.cn/
河北	沧州幼儿师范高等专科学校	https://www.czys.edu.cn/
河北	宣化科技职业学院	https://www.xhkjzy.edu.cn/
河北	廊坊燕京职业技术学院	https://www.lfyj.edu.cn/
河北	承德护理职业学院	https://www.cdhlxy.edu.cn/
河北	石家庄幼儿师范高等专科学校	https://www.sjzys.edu.cn/
河北	廊坊卫生职业学院	https://www.lfws.edu.cn/
河北	河北轨道运输职业技术学院	https://www.hbgdys.edu.cn/
河北	保定幼儿师范高等专科学校	https://www.bdys.edu.cn/
河北	河北工艺美术职业学院	https://www.hbgym.edu.cn/
河北	唐山幼儿师范高等专科学校	https://www.tsys.edu.cn/
河北	承德应用技术职业学院	https://www.cdyt.edu.cn/
河北	邯郸幼儿师范高等专科学校	https://www.hdys.edu.cn/
河北	邯郸科技职业学院	https://www.hdkjzy.edu.cn/
河北	河北资源环境职业技术学院	https://www.hbzyhj.edu.cn/
河北	衡水健康科技职业学院	https://www.hsjzxy.edu.cn/
河北	秦皇岛工业职业技术学院	https://www.qhdvtc.edu.cn/
河北	石家庄工程职业学院	https://www.sjzgxy.edu.cn/
河北	石家庄城市经济职业学院	https://www.sjzcj.edu.cn/
河北	石家庄财经职业学院	https://www.sjzcjxy.edu.cn/
河北	石家庄工商职业学院	https://www.sjzgs.edu.cn/
河北	石家庄理工职业学院	https://www.sjzlgedu.cn/
河北	石家庄科技信息职业学院	https://www.sjzkjxx.cn/
河北	石家庄医学高等专科学校	https://www.sjzmc.edu.cn/
河北	石家庄经济职业学院	https://www.sjzj.edu.cn/
河北	石家庄人民医学高等专科学校	https://www.sjzrm.edu.cn/
河北	石家庄科技职业学院	https://www.sjzkjzy.edu.cn/
河北	渤海理工职业学院	https://www.bhlg.edu.cn/
河北	曹妃甸职业技术学院	https://www.cfdvtc.edu.cn/
河北	唐山海运职业学院	https://www.tshyzy.edu.cn/
河北	邢台应用技术职业学院	https://www.xtyyjs.edu.cn/
河北	沧州航空职业学院	https://www.czhk.edu.cn/
河北	邯郸应用技术职业学院	https://www.hdyyjs.edu.cn/
河北	邢台新能源职业学院	https://www.xtxny.edu.cn/
山西	山西大学	https://www.sxu.edu.cn/
山西	太原科技大学	https://www.tyust.edu.cn/
山西	中北大学	https://www.nuc.edu.cn/
山西	太原理工大学	https://www.tyut.edu.cn/
山西	山西农业大学	https://www.sxau.edu.cn/
山西	山西医科大学	https://www.sxmu.edu.cn/
山西	长治医学院	https://www.czmc.edu.cn/
山西	山西师范大学	https://www.sxnu.edu.cn/
山西	太原师范学院	https://www.tynu.edu.cn/
山西	山西大同大学	https://www.sxdtdx.edu.cn/
山西	晋中学院	https://www.jzxy.edu.cn/
山西	长治学院	https://www.czc.edu.cn/
山西	运城学院	https://www.ycu.edu.cn/
山西	忻州师范学院	https://www.xznu.edu.cn/
山西	山西财经大学	https://www.sxufe.edu.cn/
山西	山西中医药大学	https://www.sxtcm.edu.cn/
山西	吕梁学院	https://www.llhc.edu.cn/
山西	太原学院	https://www.tyu.edu.cn/
山西	山西警察学院	https://www.sxpc.edu.cn/
山西	山西工程科技职业大学	https://www.sxgku.edu.cn/
山西	山西工学院	https://www.sxitu.edu.cn/
山西	山西电子科技学院	https://www.sxitu.edu.cn/
山西	山西科技学院	https://www.sxkj.edu.cn/
山西	太原工业学院	https://www.tit.edu.cn/
山西	山西传媒学院	https://www.sxcm.edu.cn/
山西	山西工程技术学院	https://www.sxgc.edu.cn/
山西	山西能源学院	https://www.sxny.edu.cn/
山西	山西医药学院	https://www.sxmu.edu.cn/
山西	山西应用科技学院	https://www.sxyy.edu.cn/
山西	晋中信息学院	https://www.jzci.edu.cn/
山西	山西晋中理工学院	https://www.sxjzlg.edu.cn/
山西	山西健康学院	https://www.sxjk.edu.cn/
山西	山西财经大学华商学院	https://www.sxufe.edu.cn/
山西	山西工商学院	https://www.sxgs.edu.cn/
山西	运城职业技术大学	https://www.ycptu.edu.cn/
山西	山西省财政税务专科学校	https://www.sxcs.edu.cn/
山西	长治职业技术学院	https://www.czzy.edu.cn/
山西	山西艺术职业学院	https://www.sxysxy.edu.cn/
山西	晋城职业技术学院	https://www.jcvtc.edu.cn/
山西	山西药科职业学院	https://www.sxykzy.edu.cn/
山西	大同煤炭职业技术学院	https://www.dtmtxy.edu.cn/
山西	山西机电职业技术学院	https://www.sxjd.edu.cn/
山西	山西财贸职业技术学院	https://www.sxcm.edu.cn/
山西	山西林业职业技术学院	https://www.sxlyzy.edu.cn/
山西	山西水利职业技术学院	https://www.sxsl.edu.cn/
山西	阳泉职业技术学院	https://www.yqzyjs.edu.cn/
山西	临汾职业技术学院	https://www.lfzyxy.edu.cn/
山西	山西职业技术学院	https://www.sxzy.edu.cn/
山西	山西金融职业学院	https://www.sxjrxy.edu.cn/
山西	太原城市职业技术学院	https://www.tycszy.edu.cn/
山西	山西体育职业学院	https://www.sxtyzy.edu.cn/
山西	山西警官职业学院	https://www.sxpolice.edu.cn/
山西	山西国际商务职业学院	https://www.sxibs.edu.cn/
山西	潞安职业技术学院	https://www.lazc.edu.cn/
山西	太原旅游职业学院	https://www.tylyzy.edu.cn/
山西	山西旅游职业学院	https://www.sxlyzyxy.edu.cn/
山西	山西管理职业学院	https://www.sxglzy.edu.cn/
山西	山西电力职业技术学院	https://www.sxdlzy.edu.cn/
山西	忻州职业技术学院	https://www.xzzy.edu.cn/
山西	晋中职业技术学院	https://www.jzzy.edu.cn/
山西	山西运城农业职业技术学院	https://www.ycnzy.edu.cn/
山西	运城幼儿师范高等专科学校	https://www.ycys.edu.cn/
山西	山西经贸职业学院	https://www.sxjmy.edu.cn/
山西	朔州职业技术学院	https://www.szzy.edu.cn/
山西	山西铁道职业技术学院	https://www.sxtdzy.edu.cn/
山西	晋中师范高等专科学校	https://www.jzsf.edu.cn/
山西	阳泉师范高等专科学校	https://www.yqsf.edu.cn/
山西	山西青年职业学院	https://www.sxqn.edu.cn/
山西	运城护理职业学院	https://www.ychlzy.edu.cn/
山西	运城师范高等专科学校	https://www.ycsf.edu.cn/
山西	朔州师范高等专科学校	https://www.szsf.edu.cn/
山西	吕梁职业技术学院	https://www.llzy.edu.cn/
山西	大同师范高等专科学校	https://www.dtsf.edu.cn/
山西	太原幼儿师范高等专科学校	https://www.tysf.edu.cn/
山西	山西工程职业学院	https://www.sxgcxy.edu.cn/
山西	长治幼儿师范高等专科学校	https://www.czys.edu.cn/
山西	山西通用航空职业技术学院	https://www.sxtk.edu.cn/
山西	朔州陶瓷职业技术学院	https://www.sztc.edu.cn/
山西	山西卫生健康职业学院	https://www.sxwsjk.edu.cn/
山西	吕梁师范高等专科学校	https://www.llsf.edu.cn/
山西	山西信息职业技术学院	https://www.sxxy.edu.cn/
山西	山西同文职业技术学院	https://www.sxtw.edu.cn/
山西	山西华澳商贸职业学院	https://www.sxha.edu.cn/
山西	山西老区职业技术学院	https://www.sxlq.edu.cn/
山西	大同数据科技职业学院	https://www.dtds.edu.cn/
山东	山东大学	https://www.sdu.edu.cn/
山东	中国海洋大学	https://www.ouc.edu.cn/
山东	山东科技大学	https://www.sdust.edu.cn/
山东	中国石油大学（华东）	https://www.upc.edu.cn/
山东	青岛科技大学	https://www.qust.edu.cn/
山东	济南大学	https://www.ujn.edu.cn/
山东	青岛理工大学	https://www.qut.edu.cn/
山东	山东建筑大学	https://www.sdjzu.edu.cn/
山东	齐鲁工业大学	https://www.qlu.edu.cn/
山东	山东理工大学	https://www.sdut.edu.cn/
山东	山东农业大学	https://www.sdau.edu.cn/
山东	青岛农业大学	https://www.qau.edu.cn/
山东	山东第二医科大学	https://www.sdsmu.edu.cn/
山东	山东第一医科大学	https://www.sdfmu.edu.cn/
山东	滨州医学院	https://www.bzmc.edu.cn/
山东	山东中医药大学	https://www.sdutcm.edu.cn/
山东	济宁医学院	https://www.jnmc.edu.cn/
山东	山东师范大学	https://www.sdnu.edu.cn/
山东	曲阜师范大学	https://www.qfnu.edu.cn/
山东	聊城大学	https://www.lcu.edu.cn/
山东	德州学院	https://www.dzu.edu.cn/
山东	山东航空学院	https://www.sda.edu.cn/
山东	鲁东大学	https://www.ldu.edu.cn/
山东	临沂大学	https://www.lyu.edu.cn/
山东	泰山学院	https://www.tsu.edu.cn/
山东	济宁学院	https://www.jnxy.edu.cn/
山东	菏泽学院	https://www.hezeu.edu.cn/
山东	山东财经大学	https://www.sdufe.edu.cn/
山东	山东体育学院	https://www.sdpei.edu.cn/
山东	山东艺术学院	https://www.sdca.edu.cn/
山东	枣庄学院	https://www.uzz.edu.cn/
山东	山东工艺美术学院	https://www.sdada.edu.cn/
山东	青岛大学	https://www.qdu.edu.cn/
山东	烟台大学	https://www.ytu.edu.cn/
山东	潍坊学院	https://www.wfu.edu.cn/
山东	山东警察学院	https://www.sdpc.edu.cn/
山东	山东交通学院	https://www.sdjtu.edu.cn/
山东	山东工商学院	https://www.sdibt.edu.cn/
山东	山东女子学院	https://www.sdwu.edu.cn/
山东	山东石油化工学院	https://www.sdupc.edu.cn/
山东	山东政法学院	https://www.sdupsl.edu.cn/
山东	齐鲁师范学院	https://www.qlnu.edu.cn/
山东	山东青年政治学院	https://www.sdyu.edu.cn/
山东	山东管理学院	https://www.sdmu.edu.cn/
山东	山东农业工程学院	https://www.sdau.edu.cn/
山东	淄博职业技术大学	https://www.zbvc.edu.cn/
山东	康复大学	https://www.ruh.edu.cn/
山东	齐鲁医药学院	https://www.qlmu.edu.cn/
山东	青岛滨海学院	https://www.qdbc.edu.cn/
山东	烟台南山学院	https://www.nanshan.edu.cn/
山东	潍坊科技学院	https://www.wfust.edu.cn/
山东	山东英才学院	https://www.ycxy.com/
山东	青岛恒星科技学院	https://www.hx.cn/
山东	青岛黄海学院	https://www.qdhhc.edu.cn/
山东	山东现代学院	https://www.sdxd.edu.cn/
山东	山东协和学院	https://www.sdxiehe.edu.cn/
山东	山东工程职业技术大学	https://www.sdgcu.edu.cn/
山东	烟台理工学院	https://www.ytit.edu.cn/
山东	聊城大学东昌学院	https://www.lcu.edu.cn/
山东	青岛城市学院	https://www.qdc.edu.cn/
山东	潍坊理工学院	https://www.wfit.edu.cn/
山东	山东财经大学燕山学院	https://www.sdufe.edu.cn/
山东	山东外国语职业技术大学	https://www.sdwaiyu.edu.cn/
山东	泰山科技学院	https://www.tskj.edu.cn/
山东	山东华宇工学院	https://www.huayu.edu.cn/
山东	山东外事职业大学	https://www.sdws.edu.cn/
山东	青岛工学院	https://www.qit.edu.cn/
山东	青岛农业大学海都学院	https://www.qau.edu.cn/
山东	齐鲁理工学院	https://www.qlit.edu.cn/
山东	山东财经大学东方学院	https://www.sdufe.edu.cn/
山东	烟台科技学院	https://www.ytkj.edu.cn/
山东	青岛电影学院	https://www.qdfa.edu.cn/
山东	山东医学高等专科学校	https://www.sdmc.edu.cn/
山东	菏泽医学专科学校	https://www.hzmc.edu.cn/
山东	山东商业职业技术学院	https://www.sdc.edu.cn/
山东	山东电力高等专科学校	https://www.spepc.edu.cn/
山东	日照职业技术学院	https://www.rzpt.edu.cn/
山东	青岛职业技术学院	https://www.qtc.edu.cn/
山东	威海职业学院	https://www.whvc.edu.cn/
山东	山东职业学院	https://www.sdp.edu.cn/
山东	山东劳动职业技术学院	https://www.sdlvtc.edu.cn/
山东	莱芜职业技术学院	https://www.lwvc.edu.cn/
山东	济宁职业技术学院	https://www.jnvc.edu.cn/
山东	潍坊职业学院	https://www.wfvc.edu.cn/
山东	烟台职业学院	https://www.ytvc.edu.cn/
山东	东营职业学院	https://www.dyvc.edu.cn/
山东	聊城职业技术学院	https://www.lcvc.edu.cn/
山东	滨州职业学院	https://www.bzpt.edu.cn/
山东	山东科技职业学院	https://www.sdts.edu.cn/
山东	山东服装职业学院	https://www.sdfzxy.com/
山东	山东水利职业学院	https://www.sdwcvc.edu.cn/
山东	山东畜牧兽医职业学院	https://www.sdmy.edu.cn/
山东	山东交通职业学院	https://www.sdjvc.edu.cn/
山东	山东外贸职业学院	https://www.sdwmc.edu.cn/
山东	青岛酒店管理职业技术学院	https://www.qchm.edu.cn/
山东	山东信息职业技术学院	https://www.sdxx.edu.cn/
山东	青岛港湾职业技术学院	https://www.qdgy.edu.cn/
山东	山东胜利职业学院	https://www.slzyxy.edu.cn/
山东	山东经贸职业学院	https://www.sdec.edu.cn/
山东	山东工业职业学院	https://www.sdivc.edu.cn/
山东	山东化工职业学院	https://www.sdhg.edu.cn/
山东	济南职业学院	https://www.jnvc.edu.cn/
山东	烟台工程职业技术学院	https://www.ytetc.edu.cn/
山东	德州职业技术学院	https://www.dzvtc.edu.cn/
山东	枣庄科技职业学院	https://www.zzkj.edu.cn/
山东	淄博师范高等专科学校	https://www.zbnc.edu.cn/
山东	山东中医药高等专科学校	https://www.sdtcmvc.edu.cn/
山东	济南工程职业技术学院	https://www.jngc.edu.cn/
山东	山东电子职业技术学院	https://www.sdet.edu.cn/
山东	山东旅游职业学院	https://www.sdts.edu.cn/
山东	山东铝业职业学院	https://www.sdlvye.edu.cn/
山东	泰山职业技术学院	https://www.tszy.edu.cn/
山东	山东药品食品职业学院	https://www.sddf.edu.cn/
山东	山东商务职业学院	https://www.sdbi.edu.cn/
山东	山东轻工职业学院	https://www.slzy.edu.cn/
山东	山东城市建设职业学院	https://www.sdcj.edu.cn/
山东	烟台汽车工程职业学院	https://www.ytqc.edu.cn/
山东	山东司法警官职业学院	https://www.sdsf.edu.cn/
山东	菏泽家政职业学院	https://www.hzjzxy.edu.cn/
山东	山东传媒职业学院	https://www.sdcmc.edu.cn/
山东	临沂职业学院	https://www.lyvc.edu.cn/
山东	枣庄职业学院	https://www.zzvc.edu.cn/
山东	山东理工职业学院	https://www.sdlgzy.edu.cn/
山东	青岛远洋船员职业学院	https://www.qdyc.edu.cn/
山东	济南幼儿师范高等专科学校	https://www.jnys.edu.cn/
山东	济南护理职业学院	https://www.jnhlxy.edu.cn/
山东	泰山护理职业学院	https://www.tshlxy.edu.cn/
山东	潍坊护理职业学院	https://www.wfhlxy.edu.cn/
山东	潍坊工程职业学院	https://www.wfec.edu.cn/
山东	菏泽职业学院	https://www.hzzy.edu.cn/
山东	威海海洋职业学院	https://www.whovc.edu.cn/
山东	山东特殊教育职业学院	https://www.sdtsjy.edu.cn/
山东	青岛工程职业学院	https://www.qdec.edu.cn/
山东	青岛幼儿师范高等专科学校	https://www.qdys.edu.cn/
山东	烟台幼儿师范高等专科学校	https://www.ytys.edu.cn/
山东	烟台文化旅游职业学院	https://www.ytwh.edu.cn/
山东	临沂科技职业学院	https://www.lykj.edu.cn/
山东	山东城市服务职业学院	https://www.sdcity.edu.cn/
山东	烟台卫生健康职业学院	https://www.ytwsjk.edu.cn/
山东	山东文化艺术职业学院	https://www.sdwhys.edu.cn/
山东	曲阜远东职业技术学院	https://www.qfyd.edu.cn/
山东	德州科技职业学院	https://www.dzkj.edu.cn/
山东	山东力明科技职业学院	https://www.sdlm.edu.cn/
山东	山东圣翰财贸职业学院	https://www.shcm.edu.cn/
山东	青岛飞洋职业技术学院	https://www.qdfy.edu.cn/
山东	东营科技职业学院	https://www.dyts.edu.cn/
山东	青岛求实职业技术学院	https://www.qdqs.edu.cn/
山东	潍坊工商职业学院	https://www.wfgs.edu.cn/
山东	山东杏林科技职业学院	https://www.sdxl.edu.cn/
山东	山东文化产业职业学院	https://www.sdcp.edu.cn/
山东	山东海事职业学院	https://www.sdms.edu.cn/
山东	山东艺术设计职业学院	https://www.sdys.edu.cn/
山东	烟台黄金职业学院	https://www.ythj.edu.cn/
山东	日照航海工程职业学院	https://www.rzhh.edu.cn/
山东	青岛航空科技职业学院	https://www.qdhk.edu.cn/
山东	潍坊环境工程职业学院	https://www.wfhj.edu.cn/
山东	滨州科技职业学院	https://www.bzts.edu.cn/
山东	潍坊食品科技职业学院	https://www.wfst.edu.cn/
山东	烟台城市科技职业学院	https://www.ytck.edu.cn/
山东	德州工程职业学院	https://www.dzgc.edu.cn/
山东	日照康养职业学院	https://www.rzky.edu.cn/
江苏	南京大学	https://www.nju.edu.cn/
江苏	苏州大学	https://www.suda.edu.cn/
江苏	东南大学	https://www.seu.edu.cn/
江苏	南京航空航天大学	https://www.nuaa.edu.cn/
江苏	南京理工大学	https://www.njust.edu.cn/
江苏	江苏科技大学	https://www.just.edu.cn/
江苏	中国矿业大学	https://www.cumt.edu.cn/
江苏	南京工业大学	https://www.njtech.edu.cn/
江苏	常州大学	https://www.cczu.edu.cn/
江苏	南京邮电大学	https://www.njupt.edu.cn/
江苏	河海大学	https://www.hhu.edu.cn/
江苏	江南大学	https://www.jiangnan.edu.cn/
江苏	南京林业大学	https://www.njfu.edu.cn/
江苏	江苏大学	https://www.ujs.edu.cn/
江苏	南京信息工程大学	https://www.nuist.edu.cn/
江苏	南通大学	https://www.ntu.edu.cn/
江苏	盐城工学院	https://www.ycit.edu.cn/
江苏	南京农业大学	https://www.njau.edu.cn/
江苏	南京医科大学	https://www.njmu.edu.cn/
江苏	徐州医科大学	https://www.xzmc.edu.cn/
江苏	南京中医药大学	https://www.njucm.edu.cn/
江苏	中国药科大学	https://www.cpu.edu.cn/
江苏	南京师范大学	https://www.njnu.edu.cn/
江苏	江苏师范大学	https://www.jsnu.edu.cn/
江苏	淮阴师范学院	https://www.hytc.edu.cn/
江苏	盐城师范学院	https://www.yctc.edu.cn/
江苏	南京财经大学	https://www.njue.edu.cn/
江苏	江苏警官学院	https://www.jspi.edu.cn/
江苏	南京体育学院	https://www.nipes.edu.cn/
江苏	南京艺术学院	https://www.nua.edu.cn/
江苏	苏州科技大学	https://www.usts.edu.cn/
江苏	苏州工学院	https://www.szit.edu.cn/
江苏	南京工业职业技术大学	https://www.niit.edu.cn/
江苏	淮阴工学院	https://www.hyit.edu.cn/
江苏	常州工学院	https://www.czu.edu.cn/
江苏	扬州大学	https://www.yzu.edu.cn/
江苏	南京工程学院	https://www.njit.edu.cn/
江苏	南京审计大学	https://www.nau.edu.cn/
江苏	南京晓庄学院	https://www.njxzc.edu.cn/
江苏	江苏理工学院	https://www.jliet.edu.cn/
江苏	江苏海洋大学	https://www.jou.edu.cn/
江苏	徐州工程学院	https://www.xzit.edu.cn/
江苏	南京特殊教育师范学院	https://www.njty.edu.cn/
江苏	南京警察学院	https://www.njpa.edu.cn/
江苏	泰州学院	https://www.tzu.edu.cn/
江苏	金陵科技学院	https://www.jit.edu.cn/
江苏	无锡学院	https://www.wxu.edu.cn/
江苏	苏州城市学院	https://www.szcu.edu.cn/
江苏	宿迁学院	https://www.sqc.edu.cn/
江苏	江苏第二师范学院	https://www.jssnu.edu.cn/
江苏	连云港师范学院	https://www.lygsf.edu.cn/
江苏	三江学院	https://www.sju.edu.cn/
江苏	南通理工学院	https://www.ntit.edu.cn/
江苏	东南大学成贤学院	https://www.seu.edu.cn/
江苏	无锡太湖学院	https://www.thu.edu.cn/
江苏	中国矿业大学徐海学院	https://www.cumt.edu.cn/
江苏	南京大学金陵学院	https://www.nju.edu.cn/
江苏	南京理工大学紫金学院	https://www.njust.edu.cn/
江苏	南京航空航天大学金城学院	https://www.nuaa.edu.cn/
江苏	南京传媒学院	https://www.cucn.edu.cn/
江苏	南京理工大学泰州科技学院	https://www.njust.edu.cn/
江苏	南京师范大学泰州学院	https://www.njnu.edu.cn/
江苏	南京工业大学浦江学院	https://www.njtech.edu.cn/
江苏	南京师范大学中北学院	https://www.njnu.edu.cn/
江苏	南京医科大学康达学院	https://www.njmu.edu.cn/
江苏	南京中医药大学翰林学院	https://www.njucm.edu.cn/
江苏	苏州大学应用技术学院	https://www.suda.edu.cn/
江苏	苏州科技大学天平学院	https://www.usts.edu.cn/
江苏	江苏大学京江学院	https://www.ujs.edu.cn/
江苏	扬州大学广陵学院	https://www.yzu.edu.cn/
江苏	江苏师范大学科文学院	https://www.jsnu.edu.cn/
江苏	南京邮电大学通达学院	https://www.njupt.edu.cn/
江苏	南京财经大学红山学院	https://www.njue.edu.cn/
江苏	江苏科技大学苏州理工学院	https://www.just.edu.cn/
江苏	常州大学怀德学院	https://www.cczu.edu.cn/
江苏	南通大学杏林学院	https://www.ntu.edu.cn/
江苏	南京审计大学金审学院	https://www.nau.edu.cn/
江苏	西交利物浦大学	https://www.xjtlu.edu.cn/
江苏	昆山杜克大学	https://www.dukekunshan.edu.cn/
江苏	盐城幼儿师范高等专科学校	https://www.ycys.edu.cn/
江苏	苏州幼儿师范高等专科学校	https://www.szsy.edu.cn/
江苏	无锡职业技术学院	https://www.wxit.edu.cn/
江苏	江苏建筑职业技术学院	https://www.jsjzi.edu.cn/
江苏	江苏工程职业技术学院	https://www.jsit.edu.cn/
江苏	苏州工艺美术职业技术学院	https://www.szgm.edu.cn/
江苏	连云港职业技术学院	https://www.lygtc.edu.cn/
江苏	镇江市高等专科学校	https://www.zjc.edu.cn/
江苏	南通职业大学	https://www.ntvu.edu.cn/
江苏	苏州市职业大学	https://www.szvu.edu.cn/
江苏	沙洲职业工学院	https://www.szzy.edu.cn/
江苏	扬州市职业大学	https://www.yzvc.edu.cn/
江苏	江苏经贸职业技术学院	https://www.jseti.edu.cn/
江苏	泰州职业技术学院	https://www.tzvc.edu.cn/
江苏	常州信息职业技术学院	https://www.czcit.edu.cn/
江苏	江苏联合职业技术学院	https://www.jslh.edu.cn/
江苏	江苏海事职业技术学院	https://www.jmi.edu.cn/
江苏	无锡科技职业学院	https://www.wxstc.edu.cn/
江苏	江苏医药职业学院	https://www.jsc.edu.cn/
江苏	扬州环境资源职业技术学院	https://www.yzhj.edu.cn/
江苏	南通科技职业学院	https://www.ntst.edu.cn/
江苏	苏州经贸职业技术学院	https://www.szjm.edu.cn/
江苏	苏州工业职业技术学院	https://www.szit.edu.cn/
江苏	苏州卫生职业技术学院	https://www.szmt.edu.cn/
江苏	无锡商业职业技术学院	https://www.wxsc.edu.cn/
江苏	江苏航运职业技术学院	https://www.jssc.edu.cn/
江苏	南京交通职业技术学院	https://www.njjt.edu.cn/
江苏	江苏电子信息职业学院	https://www.jsei.edu.cn/
江苏	江苏农牧科技职业学院	https://www.jsnm.edu.cn/
江苏	常州纺织服装职业技术学院	https://www.czfti.edu.cn/
江苏	苏州农业职业技术学院	https://www.szah.edu.cn/
江苏	苏州工业园区职业技术学院	https://www.szgxy.edu.cn/
江苏	南京科技职业学院	https://www.njitt.edu.cn/
江苏	常州工业职业技术学院	https://www.czgt.edu.cn/
江苏	常州工程职业技术学院	https://www.czcet.edu.cn/
江苏	江苏农林职业技术学院	https://www.jsnzy.edu.cn/
江苏	江苏食品药品职业技术学院	https://www.jssp.edu.cn/
江苏	南京铁道职业技术学院	https://www.njrts.edu.cn/
江苏	徐州工业职业技术学院	https://www.xzcit.edu.cn/
江苏	江苏信息职业技术学院	https://www.jsitc.edu.cn/
江苏	宿迁职业技术学院	https://www.sqzy.edu.cn/
江苏	南京信息职业技术学院	https://www.njcit.edu.cn/
江苏	常州机电职业技术学院	https://www.czmec.edu.cn/
江苏	江阴职业技术学院	https://www.jypc.edu.cn/
江苏	无锡城市职业技术学院	https://www.wxcs.edu.cn/
江苏	无锡工艺职业技术学院	https://www.wxgyxy.edu.cn/
江苏	苏州健雄职业技术学院	https://www.jxvtc.edu.cn/
江苏	盐城工业职业技术学院	https://www.ycpi.edu.cn/
江苏	江苏财经职业技术学院	https://www.jsfc.edu.cn/
江苏	扬州工业职业技术学院	https://www.yzcit.edu.cn/
江苏	江苏城市职业学院	https://www.jscvc.edu.cn/
江苏	南京城市职业学院	https://www.njcsxy.edu.cn/
江苏	南京机电职业技术学院	https://www.njjd.edu.cn/
江苏	南京旅游职业学院	https://www.njly.edu.cn/
江苏	江苏卫生健康职业学院	https://www.jswszy.edu.cn/
江苏	苏州信息职业技术学院	https://www.szxxjs.edu.cn/
江苏	苏州工业园区服务外包职业学院	https://www.siso.edu.cn/
江苏	徐州幼儿师范高等专科学校	https://www.xzsy.edu.cn/
江苏	徐州生物工程职业技术学院	https://www.xzsw.edu.cn/
江苏	江苏商贸职业学院	https://www.jssmzy.edu.cn/
江苏	南通师范高等专科学校	https://www.ntsz.edu.cn/
江苏	江苏护理职业学院	https://www.jshlxy.edu.cn/
江苏	江苏财会职业学院	https://www.jsczy.edu.cn/
江苏	江苏城乡建设职业学院	https://www.jscj.edu.cn/
江苏	江苏航空职业技术学院	https://www.jshk.edu.cn/
江苏	江苏安全技术职业学院	https://www.jsaq.edu.cn/
江苏	江苏旅游职业学院	https://www.jstc.edu.cn/
江苏	常州幼儿师范高等专科学校	https://www.czsy.edu.cn/
江苏	江苏司法警官职业学院	https://www.jssfjg.edu.cn/
江苏	盐城农业科技职业学院	https://www.yca.edu.cn/
江苏	宿迁幼儿师范高等专科学校	https://www.sqys.edu.cn/
江苏	无锡师范高等专科学校	https://www.wxsf.edu.cn/
江苏	明达职业技术学院	https://www.mdut.edu.cn/
江苏	九州职业技术学院	https://www.jzzy.edu.cn/
江苏	硅湖职业技术学院	https://www.shu.edu.cn/
江苏	应天职业技术学院	https://www.yingtian.edu.cn/
江苏	苏州托普信息职业技术学院	https://www.sztp.edu.cn/
江苏	太湖创意职业技术学院	https://www.thcy.edu.cn/
江苏	炎黄职业技术学院	https://www.yhxy.edu.cn/
江苏	正德职业技术学院	https://www.zdxy.edu.cn/
江苏	钟山职业技术学院	https://www.zszy.edu.cn/
江苏	无锡南洋职业技术学院	https://www.wxny.edu.cn/
江苏	江南影视艺术职业学院	https://www.jnys.edu.cn/
江苏	金肯职业技术学院	https://www.jkvtc.edu.cn/
江苏	建东职业技术学院	https://www.jdxy.edu.cn/
江苏	江海职业技术学院	https://www.jhzy.edu.cn/
江苏	金山职业技术学院	https://www.jszy.edu.cn/
江苏	昆山登云科技职业学院	https://www.kdyc.edu.cn/
江苏	南京视觉艺术职业学院	https://www.nsad.edu.cn/
江苏	苏州高博职业学院	https://www.szgbedu.cn/
江苏	宿迁泽达职业技术学院	https://www.szzy.edu.cn/
江苏	扬州中瑞酒店职业学院	https://www.yzzr.edu.cn/
江苏	苏州百年职业学院	https://www.szbn.edu.cn/
浙江	浙江大学	https://www.zju.edu.cn/
浙江	杭州电子科技大学	https://www.hdu.edu.cn/
浙江	浙江工业大学	https://www.zjut.edu.cn/
浙江	浙江理工大学	https://www.zstu.edu.cn/
浙江	浙江海洋大学	https://www.zjou.edu.cn/
浙江	浙江农林大学	https://www.zafu.edu.cn/
浙江	温州医科大学	https://www.wmu.edu.cn/
浙江	浙江中医药大学	https://www.zcmu.edu.cn/
浙江	浙江师范大学	https://www.zjnu.edu.cn/
浙江	杭州师范大学	https://www.hznu.edu.cn/
浙江	湖州师范学院	https://www.hzttc.edu.cn/
浙江	绍兴文理学院	https://www.usx.edu.cn/
浙江	台州学院	https://www.tzc.edu.cn/
浙江	温州大学	https://www.wzu.edu.cn/
浙江	丽水学院	https://www.lsu.edu.cn/
浙江	浙江工商大学	https://www.zjgsu.edu.cn/
浙江	嘉兴大学	https://www.zjxu.edu.cn/
浙江	中国美术学院	https://www.caa.edu.cn/
浙江	中国计量大学	https://www.cjlu.edu.cn/
浙江	浙江万里学院	https://www.zjwu.edu.cn/
浙江	浙江科技大学	https://www.zust.edu.cn/
浙江	宁波工程学院	https://www.nbut.edu.cn/
浙江	浙江水利水电学院	https://www.zjweu.edu.cn/
浙江	浙江财经大学	https://www.zufe.edu.cn/
浙江	浙江警察学院	https://www.zjpc.edu.cn/
浙江	衢州学院	https://www.qzc.edu.cn/
浙江	宁波大学	https://www.nbu.edu.cn/
浙江	浙江传媒学院	https://www.zjicm.edu.cn/
浙江	浙大城市学院	https://www.zucc.edu.cn/
浙江	浙大宁波理工学院	https://www.nit.zju.edu.cn/
浙江	杭州医学院	https://www.hmc.edu.cn/
浙江	湖州学院	https://www.hzu.edu.cn/
浙江	温州理工学院	https://www.wzpt.edu.cn/
浙江	嘉兴南湖学院	https://www.jxnhu.edu.cn/
浙江	浙江外国语学院	https://www.zjfl.edu.cn/
浙江	浙江音乐学院	https://www.zjcm.edu.cn/
浙江	浙江药科职业大学	https://www.zjpi.edu.cn/
浙江	金华职业技术大学	https://www.jhc.edu.cn/
浙江	浙江机电职业技术大学	https://www.zime.edu.cn/
浙江	浙江树人学院	https://www.zjsru.edu.cn/
浙江	浙江越秀外国语学院	https://www.zyufl.edu.cn/
浙江	宁波财经学院	https://www.nbc.edu.cn/
浙江	浙江广厦建设职业技术大学	https://www.zjgsu.edu.cn/
浙江	浙江工业大学之江学院	https://www.zjut.edu.cn/
浙江	浙江师范大学行知学院	https://www.zjnu.edu.cn/
浙江	宁波大学科学技术学院	https://www.nbu.edu.cn/
浙江	杭州电子科技大学信息工程学院	https://www.hdu.edu.cn/
浙江	浙江理工大学科技与艺术学院	https://www.zstu.edu.cn/
浙江	浙江农林大学暨阳学院	https://www.zafu.edu.cn/
浙江	温州医科大学仁济学院	https://www.wmu.edu.cn/
浙江	浙江中医药大学滨江学院	https://www.zcmu.edu.cn/
浙江	杭州师范大学钱江学院	https://www.hznu.edu.cn/
浙江	绍兴文理学院元培学院	https://www.usx.edu.cn/
浙江	浙江工商大学杭州商学院	https://www.zjgsu.edu.cn/
浙江	中国计量大学现代科技学院	https://www.cjlu.edu.cn/
浙江	浙江财经大学东方学院	https://www.zufe.edu.cn/
浙江	温州商学院	https://www.wzbc.edu.cn/
浙江	同济大学浙江学院	https://www.tjzj.edu.cn/
浙江	上海财经大学浙江学院	https://www.shufe-zj.edu.cn/
浙江	西湖大学	https://www.westlake.edu.cn/
浙江	宁波诺丁汉大学	https://www.nottingham.edu.cn/
浙江	温州肯恩大学	https://www.wku.edu.cn/
浙江	宁波职业技术学院	https://www.nbpt.edu.cn/
浙江	温州职业技术学院	https://www.wzvtc.edu.cn/
浙江	浙江交通职业技术学院	https://www.zjvtit.edu.cn/
浙江	宁波城市职业技术学院	https://www.nbcity.edu.cn/
浙江	浙江电力职业技术学院	https://www.zjepc.edu.cn/
浙江	浙江同济科技职业学院	https://www.zjtj.edu.cn/
浙江	浙江工商职业技术学院	https://www.zjbti.edu.cn/
浙江	台州职业技术学院	https://www.tzvtc.edu.cn/
浙江	浙江工贸职业技术学院	https://www.zjitc.net/
浙江	浙江建设职业技术学院	https://www.zjjc.edu.cn/
浙江	浙江艺术职业学院	https://www.zj-art.edu.cn/
浙江	浙江经贸职业技术学院	https://www.zjiet.edu.cn/
浙江	浙江商业职业技术学院	https://www.zjsy.edu.cn/
浙江	浙江经济职业技术学院	https://www.zjtie.edu.cn/
浙江	浙江旅游职业学院	https://www.tourzj.edu.cn/
浙江	浙江警官职业学院	https://www.zjjy.com.cn/
浙江	浙江金融职业学院	https://www.zjfc.edu.cn/
浙江	浙江工业职业技术学院	https://www.zjipc.edu.cn/
浙江	杭州职业技术学院	https://www.hzvtc.edu.cn/
浙江	嘉兴职业技术学院	https://www.jxvtc.edu.cn/
浙江	湖州职业技术学院	https://www.hzvtc.edu.cn/
浙江	衢州职业技术学院	https://www.qzvtc.edu.cn/
浙江	丽水职业技术学院	https://www.lszjy.com/
浙江	义乌工商职业技术学院	https://www.ywcb.edu.cn/
浙江	浙江纺织服装职业技术学院	https://www.zjff.edu.cn/
浙江	杭州科技职业技术学院	https://www.hzstc.edu.cn/
浙江	浙江邮电职业技术学院	https://www.zjptt.edu.cn/
浙江	宁波卫生职业技术学院	https://www.nbwc.edu.cn/
浙江	台州科技职业学院	https://www.tzvtc.edu.cn/
浙江	浙江国际海运职业技术学院	https://www.zimc.edu.cn/
浙江	浙江体育职业技术学院	https://www.zjty.edu.cn/
浙江	温州科技职业学院	https://www.wzvcst.edu.cn/
浙江	浙江农业商贸职业学院	https://www.zjas.edu.cn/
浙江	浙江特殊教育职业学院	https://www.zjts.edu.cn/
浙江	浙江安防职业技术学院	https://www.zjaf.edu.cn/
浙江	浙江舟山群岛新区旅游与健康职业学院	https://www.zsthc.edu.cn/
浙江	宁波幼儿师范高等专科学校	https://www.nbsy.edu.cn/
浙江	浙江育英职业技术学院	https://www.zjyyc.edu.cn/
浙江	绍兴职业技术学院	https://www.sxvtc.edu.cn/
浙江	浙江东方职业技术学院	https://www.zjdf.edu.cn/
浙江	浙江长征职业技术学院	https://www.zjcz.edu.cn/
浙江	嘉兴南洋职业技术学院	https://www.jxny.edu.cn/
浙江	杭州万向职业技术学院	https://www.wxpoly.edu.cn/
浙江	浙江汽车职业技术学院	https://www.zjqczy.edu.cn/
浙江	浙江横店影视职业学院	https://www.hdys.edu.cn/
浙江	浙江宇翔职业技术学院	https://www.zjyxc.edu.cn/
浙江	浙江金华科贸职业技术学院	https://www.jhkc.edu.cn/
福建	厦门大学	https://www.xmu.edu.cn/
福建	华侨大学	https://www.hqu.edu.cn/
福建	福州大学	https://www.fzu.edu.cn/
福建	福建理工大学	https://www.fjut.edu.cn/
福建	福建农林大学	https://www.fafu.edu.cn/
福建	集美大学	https://www.jmu.edu.cn/
福建	福建医科大学	https://www.fjmu.edu.cn/
福建	福建中医药大学	https://www.fjtcm.edu.cn/
福建	福建师范大学	https://www.fjnu.edu.cn/
福建	闽江学院	https://www.mju.edu.cn/
福建	武夷学院	https://www.wuyiu.edu.cn/
福建	宁德师范学院	https://www.ndsy.edu.cn/
福建	泉州师范学院	https://www.qztc.edu.cn/
福建	闽南师范大学	https://www.mnnu.edu.cn/
福建	厦门理工学院	https://www.xmut.edu.cn/
福建	三明学院	https://www.smxy.edu.cn/
福建	龙岩学院	https://www.lyun.edu.cn/
福建	福建商学院	https://www.fjcc.edu.cn/
福建	福建警察学院	https://www.fjpsc.edu.cn/
福建	莆田学院	https://www.ptu.edu.cn/
福建	厦门医学院	https://www.xmmc.edu.cn/
福建	福建江夏学院	https://www.fjjxxy.edu.cn/
福建	福建技术师范学院	https://www.fjstu.edu.cn/
福建	仰恩大学	https://www.yeu.edu.cn/
福建	厦门华厦学院	https://www.hxxy.edu.cn/
福建	闽南理工学院	https://www.mnust.edu.cn/
福建	泉州职业技术大学	https://www.qzpt.edu.cn/
福建	闽南科技学院	https://www.mnkjxy.edu.cn/
福建	福州工商学院	https://www.fzgsxy.edu.cn/
福建	厦门工学院	https://www.xit.edu.cn/
福建	阳光学院	https://www.ygxy.edu.cn/
福建	厦门大学嘉庚学院	https://www.jgxy.xmu.edu.cn/
福建	福州大学至诚学院	https://www.fzu.edu.cn/
福建	集美大学诚毅学院	https://www.jmu.edu.cn/
福建	福建师范大学协和学院	https://www.fjnu.edu.cn/
福建	福州外语外贸学院	https://www.fzfu.edu.cn/
福建	泉州信息工程学院	https://www.qziedu.cn/
福建	福州理工学院	https://www.fit.edu.cn/
福建	福建农林大学金山学院	https://www.fafu.edu.cn/
福建	福建福耀科技大学	https://www.fuyao.edu.cn/
福建	福建船政交通职业学院	https://www.fjcpc.edu.cn/
福建	漳州职业技术学院	https://www.zvti.edu.cn/
福建	闽西职业技术学院	https://www.mxvtc.edu.cn/
福建	黎明职业大学	https://www.lmu.edu.cn/
福建	福州职业技术学院	https://www.fvti.edu.cn/
福建	福建林业职业技术学院	https://www.fjlyzy.edu.cn/
福建	福建信息职业技术学院	https://www.fjcit.edu.cn/
福建	福建水利电力职业技术学院	https://www.fjsdzy.edu.cn/
福建	福建电力职业技术学院	https://www.fjdltc.edu.cn/
福建	厦门海洋职业技术学院	https://www.xmoc.edu.cn/
福建	福建农业职业技术学院	https://www.fjny.edu.cn/
福建	福建卫生职业技术学院	https://www.fjwsz.edu.cn/
福建	泉州医学高等专科学校	https://www.qzmc.edu.cn/
福建	闽北职业技术学院	https://www.mbzy.edu.cn/
福建	泉州经贸职业技术学院	https://www.qzetc.edu.cn/
福建	湄洲湾职业技术学院	https://www.mzvtc.edu.cn/
福建	福建生物工程职业技术学院	https://www.fjsw.edu.cn/
福建	福建艺术职业学院	https://www.fjysxy.edu.cn/
福建	福建幼儿师范高等专科学校	https://www.fjys.edu.cn/
福建	厦门城市职业学院	https://www.xmcu.edu.cn/
福建	泉州工艺美术职业学院	https://www.qzgm.edu.cn/
福建	三明医学科技职业学院	https://www.smzy.edu.cn/
福建	宁德职业技术学院	https://www.ndzy.edu.cn/
福建	福建体育职业技术学院	https://www.fjtyzy.edu.cn/
福建	漳州城市职业学院	https://www.zzcsxy.edu.cn/
福建	漳州卫生职业学院	https://www.zzws.edu.cn/
福建	泉州幼儿师范高等专科学校	https://www.qzys.edu.cn/
福建	闽江师范高等专科学校	https://www.mjtc.edu.cn/
福建	福建华南女子职业学院	https://www.hnwomen.edu.cn/
福建	福州英华职业学院	https://www.fzey.edu.cn/
福建	泉州纺织服装职业学院	https://www.qzfzxy.edu.cn/
福建	泉州华光职业学院	https://www.qzhg.edu.cn/
福建	福州黎明职业技术学院	https://www.fzlm.edu.cn/
福建	厦门演艺职业学院	https://www.xmyy.edu.cn/
福建	厦门华天涉外职业技术学院	https://www.xmht.edu.cn/
福建	福州科技职业技术学院	https://www.fzkj.edu.cn/
福建	福州软件职业技术学院	https://www.fzstc.edu.cn/
福建	厦门兴才职业技术学院	https://www.xmxc.edu.cn/
福建	厦门软件职业技术学院	https://www.xmsoft.edu.cn/
福建	厦门南洋职业学院	https://www.xmny.edu.cn/
福建	厦门东海职业技术学院	https://www.xmdh.edu.cn/
福建	漳州科技职业学院	https://www.zzkj.edu.cn/
福建	漳州理工职业学院	https://www.zzlg.edu.cn/
福建	武夷山职业学院	https://www.wyszy.edu.cn/
福建	泉州海洋职业学院	https://www.qzhy.edu.cn/
福建	泉州轻工职业学院	https://www.qzqg.edu.cn/
福建	厦门安防科技职业学院	https://www.xmaf.edu.cn/
福建	泉州工程职业技术学院	https://www.qzgc.edu.cn/
福建	福州墨尔本理工职业学院	https://www.fml.edu.cn/
江西	南昌大学	https://www.ncu.edu.cn/
江西	华东交通大学	https://www.ecjtu.edu.cn/
江西	东华理工大学	https://www.ecit.edu.cn/
江西	南昌航空大学	https://www.nchu.edu.cn/
江西	江西理工大学	https://www.jxust.edu.cn/
江西	景德镇陶瓷大学	https://www.jci.edu.cn/
江西	江西农业大学	https://www.jxau.edu.cn/
江西	江西中医药大学	https://www.jxutcm.edu.cn/
江西	赣南医科大学	https://www.gmu.edu.cn/
江西	江西师范大学	https://www.jxnu.edu.cn/
江西	上饶师范学院	https://www.sru.edu.cn/
江西	宜春学院	https://www.ycu.edu.cn/
江西	赣南师范大学	https://www.gnnu.edu.cn/
江西	井冈山大学	https://www.jgsu.edu.cn/
江西	江西财经大学	https://www.jxufe.edu.cn/
江西	景德镇学院	https://www.jdzu.edu.cn/
江西	萍乡学院	https://www.pxu.edu.cn/
江西	江西科技师范大学	https://www.jxstnu.edu.cn/
江西	南昌工程学院	https://www.nit.edu.cn/
江西	江西警察学院	https://www.jxga.edu.cn/
江西	新余学院	https://www.xyu.edu.cn/
江西	九江学院	https://www.jju.edu.cn/
江西	赣东学院	https://www.gdc.edu.cn/
江西	赣南科技学院	https://www.gnkj.edu.cn/
江西	南昌医学院	https://www.ncmu.edu.cn/
江西	豫章师范学院	https://www.yznu.edu.cn/
江西	南昌师范学院	https://www.ncnu.edu.cn/
江西	江西职业技术大学	https://www.jxvu.edu.cn/
江西	江西飞行学院	https://www.jxfx.edu.cn/
江西	江西科技学院	https://www.jxut.edu.cn/
江西	江西工程学院	https://www.jxgc.edu.cn/
江西	南昌理工学院	https://www.nclg.edu.cn/
江西	江西应用科技学院	https://www.jxas.edu.cn/
江西	江西服装学院	https://www.jift.edu.cn/
江西	南昌职业大学	https://www.ncvu.edu.cn/
江西	南昌工学院	https://www.ncgx.edu.cn/
江西	南昌大学科学技术学院	https://www.ncu.edu.cn/
江西	南昌大学共青学院	https://www.ncu.edu.cn/
江西	南昌交通学院	https://www.ncjt.edu.cn/
江西	南昌航空大学科技学院	https://www.nchu.edu.cn/
江西	景德镇艺术职业大学	https://www.jzay.edu.cn/
江西	江西农业大学南昌商学院	https://www.jxau.edu.cn/
江西	江西师范大学科学技术学院	https://www.jxnu.edu.cn/
江西	赣南师范大学科技学院	https://www.gnnu.edu.cn/
江西	南昌应用技术师范学院	https://www.ncyt.edu.cn/
江西	江西财经大学现代经济管理学院	https://www.jxufe.edu.cn/
江西	江西软件职业技术大学	https://www.jxsr.edu.cn/
江西	上饶幼儿师范高等专科学校	https://www.sryz.edu.cn/
江西	抚州幼儿师范高等专科学校	https://www.fzys.edu.cn/
江西	江西工业职业技术学院	https://www.jxgcxy.edu.cn/
江西	江西医学高等专科学校	https://www.jxzy.edu.cn/
江西	九江职业大学	https://www.jjvu.edu.cn/
江西	江西司法警官职业学院	https://www.jxsfa.edu.cn/
江西	江西陶瓷工艺美术职业技术学院	https://www.jxtc.edu.cn/
江西	江西旅游商贸职业学院	https://www.jxlsxy.edu.cn/
江西	江西电力职业技术学院	https://www.jxdl.edu.cn/
江西	江西环境工程职业学院	https://www.jxhjxy.edu.cn/
江西	江西艺术职业学院	https://www.jxys.edu.cn/
江西	鹰潭职业技术学院	https://www.ytvtc.edu.cn/
江西	江西信息应用职业技术学院	https://www.jxcia.edu.cn/
江西	江西交通职业技术学院	https://www.jxjt.edu.cn/
江西	江西财经职业学院	https://www.jxvc.edu.cn/
江西	江西应用技术职业学院	https://www.jxutvc.edu.cn/
江西	江西现代职业技术学院	https://www.jxxd.edu.cn/
江西	江西工业工程职业技术学院	https://www.jxgcedu.com/
江西	江西机电职业技术学院	https://www.jxjd.edu.cn/
江西	江西外语外贸职业学院	https://www.jxwy.edu.cn/
江西	江西工业贸易职业技术学院	https://www.jxgm.edu.cn/
江西	宜春职业技术学院	https://www.ycvc.jx.cn/
江西	江西应用工程职业学院	https://www.jxyy.edu.cn/
江西	江西生物科技职业学院	https://www.jxswkj.edu.cn/
江西	江西建设职业技术学院	https://www.jxjs.edu.cn/
江西	抚州职业技术学院	https://www.fzzy.edu.cn/
江西	江西中医药高等专科学校	https://www.jxzyy.edu.cn/
江西	江西制造职业技术学院	https://www.jxzz.edu.cn/
江西	江西工程职业学院	https://www.jxgcxy.com/
江西	江西青年职业学院	https://www.jxqn.edu.cn/
江西	上饶职业技术学院	https://www.srzy.edu.cn/
江西	江西农业工程职业学院	https://www.jxng.edu.cn/
江西	江西卫生职业学院	https://www.jxwsz.edu.cn/
江西	江西冶金职业技术学院	https://www.jxmt.edu.cn/
江西	江西管理职业学院	https://www.jxgl.edu.cn/
江西	江西传媒职业学院	https://www.jxcm.edu.cn/
江西	赣州师范高等专科学校	https://www.gzs.edu.cn/
江西	江西水利职业学院	https://www.jxsz.edu.cn/
江西	宜春幼儿师范高等专科学校	https://www.ycsy.edu.cn/
江西	吉安职业技术学院	https://www.jxjt.edu.cn/
江西	江西师范高等专科学校	https://www.jxsf.edu.cn/
江西	赣南卫生健康职业学院	https://www.gnws.edu.cn/
江西	萍乡卫生职业学院	https://www.pxws.edu.cn/
江西	江西婺源茶业职业学院	https://www.wycy.edu.cn/
江西	赣州职业技术学院	https://www.gzzy.edu.cn/
江西	南昌健康职业技术学院	https://www.ncjk.edu.cn/
江西	吉安幼儿师范高等专科学校	https://www.jays.edu.cn/
江西	上饶卫生健康职业学院	https://www.srws.edu.cn/
江西	江西电子信息职业技术学院	https://www.jxdzxx.edu.cn/
江西	江西科技职业学院	https://www.jxkjedu.com/
江西	江西航空职业技术学院	https://www.jxhk.edu.cn/
江西	赣西科技职业学院	https://www.gxkj.edu.cn/
江西	江西新能源科技职业学院	https://www.jxxny.edu.cn/
江西	江西枫林涉外经贸职业学院	https://www.jxfl.edu.cn/
江西	江西泰豪动漫职业学院	https://www.jxth.edu.cn/
江西	江西工商职业技术学院	https://www.jxgs.edu.cn/
江西	景德镇陶瓷职业技术学院	https://www.jztc.edu.cn/
江西	共青科技职业学院	https://www.gqkj.edu.cn/
江西	江西洪州职业学院	https://www.jxhz.edu.cn/
江西	南昌影视传播职业学院	https://www.ncys.edu.cn/
江西	九江理工职业学院	https://www.jjlg.edu.cn/
江西	和君职业学院	https://www.hjxy.edu.cn/
江西	江西樟树中医药职业学院	https://www.zszy.edu.cn/
江西	赣东职业技术学院	https://www.gdzy.edu.cn/
江西	鹰潭卫生职业学院	https://www.ytws.edu.cn/
河南	华北水利水电大学	https://www.ncwu.edu.cn/
河南	郑州大学	https://www.zzu.edu.cn/
河南	河南理工大学	https://www.hpu.edu.cn/
河南	郑州轻工业大学	https://www.zzuli.edu.cn/
河南	河南工业大学	https://www.haut.edu.cn/
河南	河南科技大学	https://www.hust.edu.cn/
河南	中原工学院	https://www.zut.edu.cn/
河南	河南农业大学	https://www.henau.edu.cn/
河南	河南科技学院	https://www.hist.edu.cn/
河南	河南牧业经济学院	https://www.hnuahe.edu.cn/
河南	河南中医药大学	https://www.hactcm.edu.cn/
河南	新乡医学院	https://www.xxmu.edu.cn/
河南	河南大学	https://www.henu.edu.cn/
河南	河南师范大学	https://www.hnnu.edu.cn/
河南	信阳师范大学	https://www.xynu.edu.cn/
河南	周口师范学院	https://www.zknu.edu.cn/
河南	安阳师范学院	https://www.aynu.edu.cn/
河南	许昌学院	https://www.xcu.edu.cn/
河南	南阳师范学院	https://www.nynu.edu.cn/
河南	洛阳师范学院	https://www.lynu.edu.cn/
河南	商丘师范学院	https://www.sqnu.edu.cn/
河南	河南财经政法大学	https://www.huel.edu.cn/
河南	郑州航空工业管理学院	https://www.zua.edu.cn/
河南	黄淮学院	https://www.huanghuai.edu.cn/
河南	平顶山学院	https://www.pdsu.edu.cn/
河南	郑州工程技术学院	https://www.zit.edu.cn/
河南	洛阳理工学院	https://www.lit.edu.cn/
河南	新乡学院	https://www.xxu.edu.cn/
河南	信阳农林学院	https://www.xyafu.edu.cn/
河南	河南工学院	https://www.hnit.edu.cn/
河南	安阳工学院	https://www.ayit.edu.cn/
河南	河南工程学院	https://www.haue.edu.cn/
河南	河南财政金融学院	https://www.hafu.edu.cn/
河南	南阳理工学院	https://www.nyp.edu.cn/
河南	河南城建学院	https://www.hncj.edu.cn/
河南	河南警察学院	https://www.hngat.edu.cn/
河南	郑州警察学院	https://www.zzpc.edu.cn/
河南	郑州师范学院	https://www.zztc.edu.cn/
河南	黄河水利职业技术大学	https://www.yrcti.edu.cn/
河南	河南体育学院	https://www.hnpc.edu.cn/
河南	黄河科技学院	https://www.huanghe.edu.cn/
河南	郑州科技学院	https://www.zit.edu.cn/
河南	郑州工业应用技术学院	https://www.zzy.edu.cn/
河南	郑州财经学院	https://www.zzjm.edu.cn/
河南	黄河交通学院	https://www.hhjt.edu.cn/
河南	商丘工学院	https://www.sqgxy.edu.cn/
河南	河南开封科技传媒学院	https://www.kfu.edu.cn/
河南	中原科技学院	https://www.zkxy.edu.cn/
河南	信阳学院	https://www.xyu.edu.cn/
河南	安阳学院	https://www.ayxy.edu.cn/
河南	豫北医学院	https://www.ybmu.edu.cn/
河南	新乡工程学院	https://www.xxgc.edu.cn/
河南	郑州工商学院	https://www.zzgs.edu.cn/
河南	郑州经贸学院	https://www.zzjm.edu.cn/
河南	商丘学院	https://www.squ.edu.cn/
河南	郑州商学院	https://www.zzsy.edu.cn/
河南	河南科技职业大学	https://www.hnkju.edu.cn/
河南	郑州升达经贸管理学院	https://www.shengda.edu.cn/
河南	郑州西亚斯学院	https://www.sias.edu.cn/
河南	郑州健康学院	https://www.zzjk.edu.cn/
河南	漯河食品工程职业大学	https://www.lhsy.edu.cn/
河南	郑州美术学院	https://www.zzms.edu.cn/
河南	河南职业技术学院	https://www.hnzj.edu.cn/
河南	漯河职业技术学院	https://www.lhvtc.edu.cn/
河南	三门峡职业技术学院	https://www.smxtc.edu.cn/
河南	郑州铁路职业技术学院	https://www.zzrvtc.edu.cn/
河南	开封大学	https://www.kfu.edu.cn/
河南	焦作大学	https://www.jzu.edu.cn/
河南	濮阳职业技术学院	https://www.pyvtc.edu.cn/
河南	郑州电力高等专科学校	https://www.zzepc.edu.cn/
河南	许昌职业技术学院	https://www.xcvtc.edu.cn/
河南	河南工业和信息化职业学院	https://www.hngy.edu.cn/
河南	河南水利与环境职业学院	https://www.hnsh.edu.cn/
河南	商丘职业技术学院	https://www.sqzy.edu.cn/
河南	平顶山工业职业技术学院	https://www.pzxy.edu.cn/
河南	周口职业技术学院	https://www.zkvtc.edu.cn/
河南	济源职业技术学院	https://www.jyvtc.edu.cn/
河南	河南司法警官职业学院	https://www.hnsf.edu.cn/
河南	鹤壁职业技术学院	https://www.hbzy.edu.cn/
河南	河南工业职业技术学院	https://www.hnpi.edu.cn/
河南	焦作师范高等专科学校	https://www.jzsf.edu.cn/
河南	河南检察职业学院	https://www.hnjc.edu.cn/
河南	河南质量工程职业学院	https://www.hnzlgc.edu.cn/
河南	郑州信息科技职业学院	https://www.zzist.edu.cn/
河南	漯河医学高等专科学校	https://www.lhmc.edu.cn/
河南	南阳医学高等专科学校	https://www.nymc.edu.cn/
河南	商丘医学高等专科学校	https://www.sqyx.edu.cn/
河南	信阳职业技术学院	https://www.xyvtc.edu.cn/
河南	郑州工业安全职业学院	https://www.zzga.edu.cn/
河南	永城职业学院	https://www.ycvc.edu.cn/
河南	河南经贸职业学院	https://www.hnjm.edu.cn/
河南	河南交通职业技术学院	https://www.hnjt.edu.cn/
河南	河南农业职业学院	https://www.hnny.edu.cn/
河南	郑州旅游职业学院	https://www.zzly.edu.cn/
河南	郑州职业技术学院	https://www.zzptc.edu.cn/
河南	河南信息统计职业学院	https://www.hnist.edu.cn/
河南	河南林业职业学院	https://www.hnlzy.edu.cn/
河南	河南工业贸易职业学院	https://www.hngm.edu.cn/
河南	河南建筑职业技术学院	https://www.hnjz.edu.cn/
河南	安阳职业技术学院	https://www.ayvtc.edu.cn/
河南	新乡职业技术学院	https://www.xxvtc.edu.cn/
河南	驻马店职业技术学院	https://www.zmdvtc.edu.cn/
河南	开封文化艺术职业学院	https://www.kfwy.edu.cn/
河南	河南应用技术职业学院	https://www.hnjs.edu.cn/
河南	河南艺术职业学院	https://www.hnys.edu.cn/
河南	河南机电职业学院	https://www.hnjd.edu.cn/
河南	河南护理职业学院	https://www.hnhlxy.edu.cn/
河南	许昌电气职业学院	https://www.xcdq.edu.cn/
河南	河南推拿职业学院	https://www.hntn.edu.cn/
河南	洛阳职业技术学院	https://www.lyvtc.edu.cn/
河南	郑州幼儿师范高等专科学校	https://www.zzys.edu.cn/
河南	安阳幼儿师范高等专科学校	https://www.ayys.edu.cn/
河南	河南医学高等专科学校	https://www.hnzzy.edu.cn/
河南	郑州财税金融职业学院	https://www.zzcsjr.edu.cn/
河南	南阳农业职业学院	https://www.nyavc.edu.cn/
河南	濮阳医学高等专科学校	https://www.pymc.edu.cn/
河南	驻马店幼儿师范高等专科学校	https://www.zmdys.edu.cn/
河南	三门峡社会管理职业学院	https://www.smsh.edu.cn/
河南	河南轻工职业学院	https://www.hnqg.edu.cn/
河南	河南测绘职业学院	https://www.hnch.edu.cn/
河南	郑州卫生健康职业学院	https://www.zzws.edu.cn/
河南	河南物流职业学院	https://www.hnwl.edu.cn/
河南	河南地矿职业学院	https://www.hndk.edu.cn/
河南	河南女子职业学院	https://www.hnnz.edu.cn/
河南	河南对外经济贸易职业学院	https://www.hnwm.edu.cn/
河南	濮阳石油化工职业技术学院	https://www.pysh.edu.cn/
河南	南阳科技职业学院	https://www.nykj.edu.cn/
河南	兰考三农职业学院	https://www.lksn.edu.cn/
河南	汝州职业技术学院	https://www.rzzy.edu.cn/
河南	洛阳文化旅游职业学院	https://www.lywl.edu.cn/
河南	周口文理职业学院	https://www.zkwl.edu.cn/
河南	信阳艺术职业学院	https://www.xyys.edu.cn/
河南	平顶山职业技术学院	https://www.pzzy.edu.cn/
河南	南阳工艺美术职业学院	https://www.nygm.edu.cn/
河南	濮阳科技职业学院	https://www.pykj.edu.cn/
河南	商丘幼儿师范高等专科学校	https://www.sqys.edu.cn/
河南	周口理工职业学院	https://www.zklt.edu.cn/
河南	驻马店农业工程职业学院	https://www.zmdny.edu.cn/
河南	郑州电子信息职业技术学院	https://www.zzeu.edu.cn/
河南	嵩山少林武术职业学院	https://www.sslws.edu.cn/
河南	郑州电力职业技术学院	https://www.zzdl.edu.cn/
河南	郑州城市职业学院	https://www.zzcs.edu.cn/
河南	焦作工贸职业学院	https://www.jzgm.edu.cn/
河南	许昌陶瓷职业学院	https://www.xctc.edu.cn/
河南	郑州理工职业学院	https://www.zzlg.edu.cn/
河南	郑州信息工程职业学院	https://www.zzxx.edu.cn/
河南	长垣烹饪职业技术学院	https://www.cypc.edu.cn/
河南	信阳涉外职业技术学院	https://www.xysw.edu.cn/
河南	鹤壁汽车工程职业学院	https://www.hbqc.edu.cn/
河南	南阳职业学院	https://www.nyzy.edu.cn/
河南	郑州商贸旅游职业学院	https://www.zzsl.edu.cn/
河南	郑州黄河护理职业学院	https://www.zzhh.edu.cn/
河南	洛阳科技职业学院	https://www.lykj.edu.cn/
河南	鹤壁能源化工职业学院	https://www.hbnh.edu.cn/
河南	平顶山文化艺术职业学院	https://www.pzwh.edu.cn/
河南	信阳航空职业学院	https://www.xyhk.edu.cn/
河南	林州建筑职业技术学院	https://www.lzjz.edu.cn/
河南	郑州电子商务职业学院	https://www.zzds.edu.cn/
河南	郑州轨道工程职业学院	https://www.zzgd.edu.cn/
河南	郑州体育职业学院	https://www.zzty.edu.cn/
河南	郑州城建职业学院	https://www.zzcj.edu.cn/
河南	郑州医药健康职业学院	https://www.zzyy.edu.cn/
河南	焦作新材料职业学院	https://www.jzxc.edu.cn/
河南	开封职业学院	https://www.kfzy.edu.cn/
河南	洛阳商业职业学院	https://www.lysy.edu.cn/
河南	郑州软件职业技术学院	https://www.zzrj.edu.cn/
河南	郑州智能科技职业学院	https://www.zzzn.edu.cn/
河南	郑州食品工程职业学院	https://www.zzsp.edu.cn/
河南	郑州汽车工程职业学院	https://www.zzqc.edu.cn/
河南	信阳科技职业学院	https://www.xykj.edu.cn/
河南	信阳工程职业学院	https://www.xygy.edu.cn/
河南	周口城市职业学院	https://www.zkcs.edu.cn/
河南	河南新乡工商职业学院	https://www.xxgs.edu.cn/
河南	郑州亚欧交通职业学院	https://www.zzye.edu.cn/
"""

# 解析输入数据，拆分省份、学校名称和网址
websites = []
for line in data.strip().split("\n"):
    parts = line.split()
    province, name, url = parts[0], parts[1], parts[2]
    websites.append({"province": province, "name": name, "url": url})

# 记录无法访问的网站
unreachable_sites = []

# 检查每个大学网站是否可以访问
for site in websites:
    try:
        print(f"正在检查 {site['province']} {site['name']} ({site['url']})...")
        response = requests.get(site["url"], timeout=5)
        if response.status_code == 200:
            print(f"{site['name']} - 可访问")
        else:
            print(f"{site['name']} - 无法访问，状态码：{response.status_code}")
            unreachable_sites.append(site)
    except Exception as e:
        print(f"{site['name']} - 无法访问，错误：{str(e)}")
        unreachable_sites.append(site)

# 将无法访问的网站保存到 Excel 文件
output_file = "unreachable_universities.xlsx"
if unreachable_sites:  # 如果有无法访问的网站
    df = pd.DataFrame(unreachable_sites, columns=["province", "name", "url"])
    df.columns = ["省份", "名称", "网址"]  # 设置中文表头
    df.to_excel(output_file, index=False, engine='openpyxl')
    print(f"\n检查完成！无法访问的网站已保存到 {output_file}")
else:
    print("\n检查完成！所有网站均可访问，无需生成文件")
