import requests
import pandas as pd
from bs4 import BeautifulSoup
import os

# 学校网址（以多行字符串的方式）
urls = """
http://www.tsu.edu.cn/
http://www.jnxy.edu.cn/
http://www.hezeu.edu.cn/
http://www.sdufe.edu.cn/

http://www.sdca.edu.cn/
http://www.uzz.edu.cn/
http://www.sdada.edu.cn/
http://www.qdu.edu.cn/
http://www.ytu.edu.cn/
http://www.wfu.edu.cn/
http://www.sdpc.edu.cn/
http://www.sdjtu.edu.cn/
http://www.sdtbu.edu.cn/
http://www.sdwz.edu.cn/
http://www.sdip.edu.cn/
http://www.sdupsl.edu.cn/
http://www.qlnu.edu.cn/
http://www.sdyu.edu.cn/
http://www.sdmu.edu.cn/
http://www.sdaeu.edu.cn/
http://www.zbvc.edu.cn/
http://www.ruh.edu.cn/
http://www.qlmu.edu.cn/
http://www.qdbhu.edu.cn/
http://www.nanshan.edu.cn/
http://www.wfust.edu.cn/
http://www.sdei.edu.cn/
http://www.hxst.edu.cn/
http://www.qdhhc.edu.cn/
http://www.sdxd.edu.cn/
http://www.sdxiehe.edu.cn/
http://www.sdetu.edu.cn/
http://www.ytlc.edu.cn/
http://www.dcxy.lcu.edu.cn/
http://www.qdc.edu.cn/
http://www.wfit.edu.cn/
http://www.ysxy.sdufe.edu.cn/
http://www.sdwaiyu.edu.cn/
http://www.tstc.edu.cn/
http://www.huayu.edu.cn/
http://www.sdwsc.edu.cn/
http://www.qdcit.edu.cn/
http://www.haidu.edu.cn/
http://www.qlit.edu.cn/
http://www.dfxy.sdufe.edu.cn/
http://www.ytkj.edu.cn/
http://www.qdca.edu.cn/
http://www.sdykyz.edu.cn/
http://www.hzmc.edu.cn/
http://www.sdcit.edu.cn/
http://www.spepc.edu.cn/
http://www.rzpt.edu.cn/
http://www.qtc.edu.cn/
http://www.whvc.edu.cn/
http://www.sdcet.edu.cn/
http://www.sdlvtc.edu.cn/
http://www.lwvc.edu.cn/
http://www.jnzy.edu.cn/
http://www.wfvc.edu.cn/
http://www.ytvc.edu.cn/
http://www.dyvc.edu.cn/
http://www.lcvc.edu.cn/
http://www.bzpt.edu.cn/
http://www.sdts.edu.cn/
http://www.sdfzxy.edu.cn/
http://www.sdwc.edu.cn/
http://www.sdxmsy.edu.cn/
http://www.sdjzxy.edu.cn/
http://www.sdwmy.edu.cn/
http://www.qchm.edu.cn/
http://www.sdcit.edu.cn/
http://www.qdgy.edu.cn/
http://www.slzy.edu.cn/
http://www.sdec.edu.cn/
http://www.sdivc.edu.cn/
http://www.sdhgxy.edu.cn/
http://www.jnvc.edu.cn/
http://www.ytetc.edu.cn/
http://www.dzvtc.edu.cn/
http://www.zzkjxy.edu.cn/
http://www.zbnc.edu.cn/
http://www.sdszy.edu.cn/
http://www.jnzyjsxy.edu.cn/
http://www.sdec.edu.cn/
http://www.sdts.edu.cn/
http://www.sdalvc.edu.cn/
http://www.tszy.edu.cn/
http://www.sdfda.edu.cn/
http://www.sdswxy.edu.cn/
http://www.sdqgzy.edu.cn/
http://www.sdcj.edu.cn/
http://www.ytqczy.edu.cn/
http://www.sdsfjy.edu.cn/
http://www.hzjzxy.edu.cn/
http://www.sdcmc.edu.cn/
http://www.lyvc.edu.cn/
http://www.zzvc.edu.cn/
http://www.sdlgzy.edu.cn/
http://www.qdfyc.edu.cn/
http://www.jnys.edu.cn/
http://www.jnhlxy.edu.cn/
http://www.tshlxy.edu.cn/
http://www.wfhlxy.edu.cn/
http://www.wfvtc.edu.cn/
http://www.hzzy.edu.cn/
http://www.whovc.edu.cn/
http://www.sdse.edu.cn/
http://www.qdec.edu.cn/
http://www.qdys.edu.cn/
http://www.ytys.edu.cn/
http://www.ytctvc.edu.cn/
http://www.lykjzy.edu.cn/
http://www.sdcsvc.edu.cn/
http://www.ytwsjkzy.edu.cn/
http://www.sdwysy.edu.cn/
http://www.qfydvc.edu.cn/
http://www.dzkjxy.edu.cn/
http://www.sdlm.edu.cn/
http://www.shcm.edu.cn/
http://www.qdfy.edu.cn/
http://www.dyts.edu.cn/
http://www.qdqs.edu.cn/
http://www.wfgsxy.edu.cn/
http://www.sdxlxy.edu.cn/
http://www.sdwci.edu.cn/
http://www.sdmsvc.edu.cn/
http://www.sdas.edu.cn/
http://www.ythjzy.edu.cn/
http://www.rzhg.edu.cn/
http://www.qdhkzy.edu.cn/
http://www.wfhjgc.edu.cn/
http://www.bzts.edu.cn/
http://www.wfst.edu.cn/
http://www.ytcst.edu.cn/
http://www.dzgc.edu.cn/
http://www.rzkyzy.edu.cn/
http://www.nju.edu.cn
http://www.suda.edu.cn
http://www.seu.edu.cn
http://www.nuaa.edu.cn
http://www.njust.edu.cn
http://www.just.edu.cn
http://www.cumt.edu.cn
http://www.njtech.edu.cn
http://www.cczu.edu.cn
http://www.njupt.edu.cn
http://www.hhu.edu.cn
http://www.jiangnan.edu.cn
http://www.njfu.edu.cn
http://www.ujs.edu.cn
http://www.nuist.edu.cn
http://www.ntu.edu.cn
http://www.ycit.edu.cn
http://www.njau.edu.cn
http://www.njmu.edu.cn
http://www.xzmc.edu.cn
http://www.njucm.edu.cn
http://www.cpu.edu.cn
http://www.njnu.edu.cn
http://www.jsnu.edu.cn
http://www.hytc.edu.cn
http://www.yctc.edu.cn
http://www.njue.edu.cn
http://www.jspi.edu.cn
http://www.njty.edu.cn
http://www.nua.edu.cn
http://www.usts.edu.cn
http://www.szit.edu.cn
http://www.niit.edu.cn
http://www.hyit.edu.cn
http://www.czust.edu.cn
http://www.yzu.edu.cn
http://www.njit.edu.cn
http://www.nau.edu.cn
http://www.njxzc.edu.cn
http://www.jit.edu.cn
http://www.jou.edu.cn
http://www.xzit.edu.cn
http://www.njts.edu.cn
http://www.njpa.edu.cn
http://www.tzu.edu.cn
http://www.jit.edu.cn
http://www.wxit.edu.cn
http://www.szcu.edu.cn
http://www.sqc.edu.cn
http://www.jsnu2.edu.cn
http://www.lygsf.edu.cn
http://www.sju.edu.cn
http://www.ntit.edu.cn
http://www.seucx.edu.cn
http://www.thxy.edu.cn
http://www.xhxy.edu.cn
http://www.jlxy.edu.cn
http://www.zjxy.edu.cn
http://www.jcxy.edu.cn
http://www.cucn.edu.cn
http://www.tzkjxy.edu.cn
http://www.tzxy.edu.cn
http://www.pjxy.edu.cn
http://www.zbxy.edu.cn
http://www.kdxy.edu.cn
http://www.hlxy.edu.cn
http://www.szyyjs.edu.cn
http://www.tpxy.edu.cn
http://www.jjxy.edu.cn
http://www.glxy.edu.cn
http://www.kwxy.edu.cn
http://www.tdxy.edu.cn
http://www.hsxy.edu.cn
http://www.szlgxy.edu.cn
http://www.hdxy.edu.cn
http://www.xlxy.edu.cn
http://www.jsxy.edu.cn
http://www.xjtlu.edu.cn
http://www.dukekunshan.edu.cn
http://www.ycys.edu.cn
http://www.szsy.edu.cn
http://www.wxstc.edu.cn
http://www.jsjzi.edu.cn
http://www.jsit.edu.cn
http://www.szgm.edu.cn
http://www.lygzy.edu.cn
http://www.zjvtc.edu.cn
http://www.ntvu.edu.cn
http://www.szvu.edu.cn
http://www.szzy.edu.cn
http://www.yzvu.edu.cn
http://www.jseti.edu.cn
http://www.tzzy.edu.cn
http://www.czcit.edu.cn
http://www.jslhzy.edu.cn
http://www.jmi.edu.cn
http://www.wxkjzy.edu.cn
http://www.jsyyzy.edu.cn
http://www.yzhjzy.edu.cn
http://www.ntkjzy.edu.cn
http://www.szjmzy.edu.cn
http://www.szgyzy.edu.cn
http://www.szwszy.edu.cn
http://www.wxsc.edu.cn
http://www.jssc.edu.cn
http://www.njjt.edu.cn
http://www.jsdxzy.edu.cn
http://www.jsnmzy.edu.cn
http://www.czfczy.edu.cn
http://www.szzy.edu.cn
http://www.sipvtc.edu.cn
http://www.njtc.edu.cn
http://www.czgyzy.edu.cn
http://www.czgcxy.edu.cn
http://www.jsnlzy.edu.cn
http://www.jsspzy.edu.cn
http://www.njtdzy.edu.cn
http://www.xzgyzy.edu.cn
http://www.jsxxzy.edu.cn
http://www.sqzy.edu.cn
http://www.njcit.edu.cn
http://www.czmtc.edu.cn
http://www.jypc.edu.cn
http://www.wxcszy.edu.cn
http://www.wxgyzy.edu.cn
http://www.jxzy.edu.cn
http://www.ycgyzy.edu.cn
http://www.jscjzy.edu.cn
http://www.yzgyzy.edu.cn
http://www.jscszy.edu.cn
http://www.njcszy.edu.cn
http://www.njjdzy.edu.cn
http://www.njlyzy.edu.cn
http://www.jswszy.edu.cn
http://www.szxxzy.edu.cn
http://www.siso.edu.cn
http://www.xzsy.edu.cn
http://www.xzswgc.edu.cn
http://www.jssmzy.edu.cn
http://www.ntsf.edu.cn
http://www.jshlzy.edu.cn
http://www.jsczzy.edu.cn
http://www.jscjzy.edu.cn
http://www.jshkzy.edu.cn
http://www.jsaqzy.edu.cn
http://www.jsta.edu.cn
http://www.czsy.edu.cn
http://www.jssfjg.edu.cn
http://www.ycnkzy.edu.cn
http://www.sqsy.edu.cn
http://www.wxsf.edu.cn
http://www.mdzy.edu.cn
http://www.jzzy.edu.cn
http://www.ghzy.edu.cn
http://www.ytzy.edu.cn
http://www.sztp.edu.cn
http://www.thcy.edu.cn
http://www.yhzy.edu.cn
http://www.zdzy.edu.cn
http://www.zszy.edu.cn
http://www.wxny.edu.cn
http://www.jnys.edu.cn
http://www.jkzy.edu.cn
http://www.jdong.edu.cn
http://www.jhzy.edu.cn
http://www.jszy.edu.cn
http://www.kdyzy.edu.cn
http://www.njsy.edu.cn
http://www.szgb.edu.cn
http://www.szzy.edu.cn
http://www.yzzr.edu.cn
http://www.szbn.edu.cn
https://www.zju.edu.cn/
https://www.hdu.edu.cn/
http://www.zjut.edu.cn/
http://www.zstu.edu.cn/
http://www.zjou.edu.cn/
https://www.zafu.edu.cn/
https://www.wmu.edu.cn/
http://www.zcmu.edu.cn/
http://www.zjnu.edu.cn/
https://www.hznu.edu.cn/
http://www.zjhzu.edu.cn/
http://www.usx.edu.cn/
http://www.tzc.edu.cn/
https://www.wzu.edu.cn/
http://www.lsu.edu.cn/
https://www.zjgsu.edu.cn/
https://www.zjxmu.edu.cn/
https://www.caa.edu.cn/
https://www.cjlu.edu.cn/
http://www.zwu.edu.cn/
https://www.zust.edu.cn/
http://www.nbut.edu.cn/
http://www.zjweu.edu.cn/
http://www.zufe.edu.cn/
https://www.zjpc.edu.cn/
http://www.qzc.edu.cn/
https://www.nbu.edu.cn/
https://www.zjicm.edu.cn/
https://www.zucc.edu.cn/
https://www.nit.zju.edu.cn/
http://www.hmc.edu.cn/
http://www.zjhu.edu.cn/
http://www.wzut.edu.cn/
http://www.nhu.edu.cn/
http://www.zisu.edu.cn/
http://www.zjcm.edu.cn/
http://www.zjpu.edu.cn/
http://www.jhc.edu.cn/
http://www.zime.edu.cn/
http://www.zjsru.edu.cn/
http://www.zyufl.edu.cn/
http://www.nbfu.edu.cn/
http://www.zjgsu.edu.cn/
http://www.zjzju.edu.cn/
http://www.xzc.zjnu.edu.cn/
http://www.stc.nbu.edu.cn/
http://www.ie.hdu.edu.cn/
http://www.ky.zstu.edu.cn/
http://www.jy.zafu.edu.cn/
http://www.rjc.wmu.edu.cn/
http://www.bjc.zcmu.edu.cn/
http://www.qjc.hznu.edu.cn/
http://www.ypc.usx.edu.cn/
http://www.hzic.zjgsu.edu.cn/
http://www.xdkj.cjlu.edu.cn/
http://www.dfxy.zufe.edu.cn/
https://www.wzbc.edu.cn/
http://www.tjzj.edu.cn/
http://www.zjsfu.edu.cn/
https://www.westlake.edu.cn/
https://www.nottingham.edu.cn/
https://www.wku.edu.cn/
http://www.nbpt.edu.cn/
http://www.wzvtc.edu.cn/
http://www.zjvtit.edu.cn/
http://www.nbcc.edu.cn/
http://www.zjepc.edu.cn/
http://www.zjtongji.edu.cn/
http://www.zjtbu.edu.cn/
http://www.tzvtc.edu.cn/
http://www.zjitc.edu.cn/
http://www.zjjc.edu.cn/
http://www.zj-art.edu.cn/
http://www.zjiet.edu.cn/
http://www.zjbc.edu.cn/
http://www.zjtie.edu.cn/
https://www.tourzj.edu.cn/
http://www.zjpc.net.cn/
https://www.zfc.edu.cn/
http://www.zjipc.edu.cn/
http://www.hzvtc.edu.cn/
http://www.jxvtc.edu.cn/
http://www.hzvtc.edu.cn/
http://www.qzvtc.edu.cn/
http://www.lszy.edu.cn/
http://www.ywcb.edu.cn/
http://www.zjff.edu.cn/
http://www.hzstc.edu.cn/
http://www.zjptt.edu.cn/
http://www.nbhealth.edu.cn/
http://www.tzkj.edu.cn/
http://www.zimc.edu.cn/
http://www.zjsc.edu.cn/
http://www.wzkj.edu.cn/
http://www.zjnsw.edu.cn/
http://www.zjtjzy.edu.cn/
http://www.zjaf.edu.cn/
http://www.zstdc.edu.cn/
http://www.nbyey.edu.cn/
http://www.zyec.edu.cn/
http://www.sxvtc.edu.cn/
http://www.zjdfc.edu.cn/
http://www.zjcz.edu.cn/
http://www.jxny.edu.cn/
http://www.wxpoly.edu.cn/
http://www.zjqczy.edu.cn/
http://www.hdjyc.edu.cn/
http://www.zjyuxiang.edu.cn/
http://www.jhkm.edu.cn/
http://www.xmu.edu.cn
http://www.hqu.edu.cn
http://www.fzu.edu.cn
http://www.fjut.edu.cn
http://www.fafu.edu.cn
http://www.jmu.edu.cn
http://www.fjmu.edu.cn
http://www.fjtcm.edu.cn
http://www.fjnu.edu.cn
http://www.mju.edu.cn
http://www.wyu.edu.cn
http://www.ndnu.edu.cn
http://www.qztc.edu.cn
http://www.mnnu.edu.cn
http://www.xmut.edu.cn
http://www.smxy.edu.cn
http://www.lyun.edu.cn
http://www.fjcc.edu.cn
http://www.fjpsc.edu.cn
http://www.ptu.edu.cn
http://www.xmmc.edu.cn
http://www.fjjxu.edu.cn
http://www.fjstu.edu.cn
http://www.yeu.edu.cn
http://www.hxxy.edu.cn
http://www.mnust.edu.cn
http://www.qzptu.edu.cn
http://www.mnkju.edu.cn
http://www.fzgsxy.edu.cn
http://www.xit.edu.cn
http://www.ygu.edu.cn
http://www.jgxy.edu.cn
http://www.zcxy.edu.cn
http://www.cyxy.edu.cn
http://www.xiehe.edu.cn
http://www.fzfu.edu.cn
http://www.qzie.edu.cn
http://www.fzlgxy.edu.cn
http://www.jsxy.edu.cn
http://www.fytu.edu.cn
http://www.fjcpc.edu.cn
http://www.zzpt.edu.cn
http://www.mxvtc.edu.cn
http://www.lmu.edu.cn
http://www.fvti.edu.cn
http://www.fjlyzy.edu.cn
http://www.fjitt.edu.cn
http://www.fjsdzy.edu.cn
http://www.fjdzy.edu.cn
http://www.xmoc.edu.cn
http://www.fjnyzy.edu.cn
http://www.fjwszy.edu.cn
http://www.qzy.edu.cn
http://www.mbzy.edu.cn
http://www.qzjmy.edu.cn
http://www.mzvtc.edu.cn
http://www.fjswgc.edu.cn
http://www.fjyszy.edu.cn
http://www.fjys.edu.cn
http://www.xmcu.edu.cn
http://www.qzgmy.edu.cn
http://www.smzy.edu.cn
http://www.ndzy.edu.cn
http://www.fjtyzy.edu.cn
http://www.zzcszy.edu.cn
http://www.zzwszy.edu.cn
http://www.qzys.edu.cn
http://www.mjtc.edu.cn
http://www.hnwomen.edu.cn
http://www.fzyhzy.edu.cn
http://www.qzfzzy.edu.cn
http://www.qzhgzy.edu.cn
http://www.fzlmzy.edu.cn
http://www.xmyyzy.edu.cn
http://www.xmhtzy.edu.cn
http://www.fzkjzy.edu.cn
http://www.fzrzy.edu.cn
http://www.xmxczy.edu.cn
http://www.xmrjzy.edu.cn
http://www.xmnyzy.edu.cn
http://www.xmdhzy.edu.cn
http://www.zzkjzy.edu.cn
http://www.zzlgzy.edu.cn
http://www.wyszy.edu.cn
http://www.qzhyzy.edu.cn
http://www.qzqgzy.edu.cn
http://www.xmafzy.edu.cn
http://www.qzgcxy.edu.cn
http://www.fmp.edu.cn
https://www.ncu.edu.cn/
https://www.ecjtu.edu.cn/
http://www.ecit.cn/
http://www.nchu.edu.cn/
https://www.jxust.edu.cn/
https://www.jci.edu.cn/
https://www.jxau.edu.cn/
https://www.jxutcm.edu.cn/
https://www.gmu.edu.cn/
https://www.jxnu.edu.cn/
http://www.srnu.edu.cn/
http://www.ycu.jx.cn/
http://www.gnnu.cn/
http://www.jgsu.edu.cn/
https://www.jxufe.edu.cn/
http://www.jdzu.edu.cn/
http://www.pxc.jx.cn/
http://www.jxstnu.edu.cn/
http://www.nit.edu.cn/
http://www.jxga.edu.cn/
http://www.xyu.edu.cn/
http://www.jju.edu.cn/
http://www.gdx.edu.cn/
http://www.gnust.edu.cn/
http://www.ncmu.edu.cn/
http://www.yuznu.jx.cn/
http://www.ncnu.edu.cn/
http://www.jxztu.edu.cn/
http://www.jxflight.edu.cn/
http://www.jxut.edu.cn/
http://www.jxgcxy.net/
http://www.nclg.com.cn/
http://www.jxcsedu.com/
http://www.jift.edu.cn/
http://www.nczyxy.com/
http://www.ncist.edu.cn/
http://www.ndkjxy.cn/
http://www.gqxy.ncu.edu.cn/
http://www.ncjtxy.edu.cn/
http://www.kjxy.nchu.edu.cn/
http://www.jciu.edu.cn/
http://www.ncsc.jxau.edu.cn/
http://www.kjxy.jxnu.edu.cn/
http://www.kjxy.gnnu.edu.cn/
http://www.ncatnu.edu.cn/
http://www.xdjjgl.jxufe.edu.cn/
https://www.jxsr.edu.cn/
http://www.srysz.edu.cn/
http://www.fzys.edu.cn/
http://www.jxgzy.cn/
http://www.jxyy.edu.cn/
http://www.jjvu.jx.cn/
http://www.jxsfgxy.edu.cn/
http://www.jxtcmy.com/
http://www.jxtbc.edu.cn/
http://www.jxdlzy.com/
http://www.jxhjxy.com/
http://www.jxysxy.com/
http://www.ytvtc.com/
http://www.jxcia.com/
http://www.jxjtxy.edu.cn/
http://www.jxvc.jx.cn/
https://www.jxatc.edu.cn/
http://www.jxxy.edu.cn/
http://www.jxgcxy.com/
http://www.jxjdzy.com/
http://www.jxwywm.com/
http://www.jxgmxy.edu.cn/
http://www.ycvc.jx.cn/
http://www.jxyyxy.com/
http://www.jxswkj.com/
http://www.jxjsxy.edu.cn/
http://www.fzzy.edu.cn/
http://www.jxzyy.com/
http://www.jxzzxy.edu.cn/
http://www.jxgcxy.net.cn/
http://www.jxqy.com.cn/
http://www.srzy.edu.cn/
http://www.jxnzy.edu.cn/
http://www.jxwsc.com/
http://www.jxyjxy.com/
http://www.jxglxy.com/
http://www.jxcmxy.edu.cn/
http://www.gzsz.edu.cn/
http://www.jxslsdxy.com/
http://www.ycys.edu.cn/
http://www.jxjatc.edu.cn/
http://www.jxsfs.edu.cn/
http://www.gnwsjk.edu.cn/
http://www.pxwsxy.edu.cn/
http://www.wycyxy.com/
http://www.gzpt.edu.cn/
http://www.ncjky.com/
http://www.jays.edu.cn/
http://www.srwsjk.edu.cn/
http://www.jxdzy.edu.cn/
http://www.jxkjxy.com/
http://www.jxhkxy.com/
http://www.gxkjxy.com/
http://www.jxnyxy.com/
http://www.jxflw.edu.cn/
http://www.thdm.edu.cn/
http://www.jxgsxy.net/
http://www.jtcvc.com/
http://www.gqkjxy.com/
http://www.jxhzxy.com/
http://www.ncyscbxy.com/
http://www.jjlgxy.com/
http://www.hjxy.edu.cn/
http://www.zszyyxy.com/
http://www.gdxzy.edu.cn/
http://www.ytwsxy.com/
http://www.ncwu.edu.cn
http://www.zzu.edu.cn
http://www.hpu.edu.cn
http://www.zzuli.edu.cn
http://www.haut.edu.cn
http://www.haust.edu.cn
http://www.zut.edu.cn
http://www.henau.edu.cn
http://www.hist.edu.cn
http://www.hnuahe.edu.cn
http://www.hactcm.edu.cn
http://www.xxmu.edu.cn
http://www.henu.edu.cn
http://www.htu.edu.cn
http://www.xynu.edu.cn
http://www.zknu.edu.cn
http://www.aynu.edu.cn
http://www.xcu.edu.cn
http://www.nynu.edu.cn
http://www.lynu.edu.cn
http://www.sqnu.edu.cn
http://www.huel.edu.cn
http://www.zua.edu.cn
http://www.huanghuai.edu.cn
http://www.pdsu.edu.cn
http://www.zzut.edu.cn
http://www.lit.edu.cn
http://www.xxu.edu.cn
http://www.xyafu.edu.cn
http://www.hnpu.edu.cn
http://www.ayit.edu.cn
http://www.haue.edu.cn
http://www.hafu.edu.cn
http://www.nylg.edu.cn
http://www.hncj.edu.cn
http://www.hnp.edu.cn
http://www.zzpc.edu.cn
http://www.zzsfc.edu.cn
http://www.yrcti.edu.cn
http://www.hnist.edu.cn
http://www.hhstu.edu.cn
http://www.zit.edu.cn
http://www.zzyedu.cn
http://www.zzjm.edu.cn
http://www.ytjc.edu.cn
http://www.sqgxy.edu.cn
http://www.kfu.edu.cn
http://www.zykj.edu.cn
http://www.xyhc.edu.cn
http://www.ayxy.edu.cn
http://www.ybyxy.edu.cn
http://www.xxgcxy.edu.cn
http://www.zzgs.edu.cn
http://www.zzjmxy.edu.cn
http://www.squ.edu.cn
http://www.zzsx.edu.cn
http://www.havust.edu.cn
http://www.shengda.edu.cn
http://www.sias.edu.cn
http://www.zzjku.edu.cn
http://www.lhspgc.edu.cn
http://www.zzmc.edu.cn
http://www.hnzj.edu.cn
http://www.lhvtc.edu.cn
http://www.smxvtc.edu.cn
http://www.zzrvtc.edu.cn
http://www.kfu.edu.cn
http://www.jzu.edu.cn
http://www.pyvtc.edu.cn
http://www.zzdl.com
http://www.xcvtc.edu.cn
http://www.hngy.edu.cn
http://www.hnshxy.edu.cn
http://www.sqzy.edu.cn
http://www.pzxy.edu.cn
http://www.zkvtc.edu.cn
http://www.jyvtc.edu.cn
http://www.hnsfxy.edu.cn
http://www.hbzy.edu.cn
http://www.hnpi.edu.cn
http://www.jzsz.edu.cn
http://www.hnjc.edu.cn
http://www.hnzlgc.edu.cn
http://www.zxitz.edu.cn
http://www.lhmc.edu.cn
http://www.nymc.edu.cn
http://www.sqyx.edu.cn
http://www.xyvtc.edu.cn
http://www.zzgyaq.edu.cn
http://www.ycvc.edu.cn
http://www.hnjm.edu.cn
http://www.hnjt.edu.cn
http://www.hnny.edu.cn
http://www.zzly.edu.cn
http://www.zzptc.edu.cn
http://www.hnistat.edu.cn
http://www.hnly.edu.cn
http://www.hngm.edu.cn
http://www.hnjz.edu.cn
http://www.ayvtc.edu.cn
http://www.xxvtc.edu.cn
http://www.zmdvtc.edu.cn
http://www.kfwy.edu.cn
http://www.hnjs.edu.cn
http://www.hnys.edu.cn
http://www.hnjd.edu.cn
http://www.hnhlxy.edu.cn
http://www.xcdq.edu.cn
http://www.hntn.edu.cn
http://www.lyvtc.edu.cn
http://www.zzys.edu.cn
http://www.ayys.edu.cn
http://www.hnmc.edu.cn
http://www.zzcsjr.edu.cn
http://www.nynzy.edu.cn
http://www.pymc.edu.cn
http://www.zmdys.edu.cn
http://www.smxsh.edu.cn
http://www.hnqg.edu.cn
http://www.hnch.edu.cn
http://www.zzwj.edu.cn
http://www.hnwl.edu.cn
http://www.hndk.edu.cn
http://www.hnnz.edu.cn
http://www.hnwm.edu.cn
http://www.pysyhx.edu.cn
http://www.nykj.edu.cn
http://www.lksn.edu.cn
http://www.rzzy.edu.cn
http://www.lywl.edu.cn
http://www.zkwl.edu.cn
http://www.xyyszy.edu.cn
http://www.pdszy.edu.cn
http://www.nygm.edu.cn
http://www.pykjzy.edu.cn
http://www.sqys.edu.cn
http://www.zklt.edu.cn
http://www.zmdny.edu.cn
http://www.zzdzy.edu.cn
http://www.sslws.edu.cn
http://www.zzdlzy.edu.cn
http://www.zzcszy.edu.cn
http://www.jzgm.edu.cn
http://www.xctc.edu.cn
http://www.zzlg.edu.cn
http://www.zzxgy.edu.cn
http://www.cypr.edu.cn
http://www.xysw.edu.cn
http://www.hbqczy.edu.cn
http://www.nyzy.edu.cn
http://www.zzsml.edu.cn
http://www.zzyh.edu.cn
http://www.lykjzy.edu.cn
http://www.hbny.edu.cn
http://www.pdswy.edu.cn
http://www.xyhk.edu.cn
http://www.lzjzzy.edu.cn
http://www.zzdszy.edu.cn
http://www.zzgd.edu.cn
http://www.zztyzy.edu.cn
http://www.zzcjxy.edu.cn
http://www.zzyy.edu.cn
http://www.jzxc.edu.cn
http://www.kfzy.edu.cn
http://www.lysy.edu.cn
http://www.zzrj.edu.cn
http://www.zzcit.edu.cn
http://www.zzsp.edu.cn
http://www.zzqc.edu.cn
http://www.xykjzy.edu.cn
http://www.xyjs.edu.cn
http://www.zkcs.edu.cn
http://www.xxgs.edu.cn
http://www.zzya.edu.cn
https://www.ahu.edu.cn/
https://www.ustc.edu.cn/
https://www.hfut.edu.cn/
http://www.ahut.edu.cn/
https://www.aust.edu.cn/
http://www.ahpu.edu.cn/
https://www.ahau.edu.cn/
https://www.ahmu.edu.cn/
http://www.bbmc.edu.cn/
http://www.wnmc.edu.cn/
http://www.ahtcm.edu.cn/
https://www.ahnu.edu.cn/
http://www.fynu.edu.cn/
http://www.aqnu.edu.cn/
https://www.hbnu.edu.cn/
http://www.hsu.edu.cn/
http://www.wxc.edu.cn/
http://www.chzu.edu.cn/
https://www.aufe.edu.cn/
http://www.ahszu.edu.cn/
http://www.chu.edu.cn/
http://www.hnnu.edu.cn/
http://www.tlu.edu.cn/
https://www.ahjzu.edu.cn/
http://www.ahstu.edu.cn/
https://www.hfuu.edu.cn/
http://www.bbc.edu.cn/
http://www.czu.edu.cn/
http://www.ahbzu.edu.cn/
http://www.hfut.edu.cn/
http://www.hfnu.edu.cn/
http://www.ahyx.edu.cn/
http://www.ahpa.edu.cn/
http://www.sanlian.edu.cn/
http://www.axhu.edu.cn/
http://www.wenda.edu.cn/
http://www.awu.edu.cn/
http://www.bbc.edu.cn/
http://www.aiit.edu.cn/
http://www.masu.edu.cn/
http://www.hfcity.edu.cn/
http://www.hfjj.edu.cn/
http://www.whu.edu.cn/
http://www.ahmu.edu.cn/lcyxy/
http://www.fyit.edu.cn/
http://www.hblgxy.edu.cn/
http://www.wjit.edu.cn/
http://www.uta.edu.cn/
http://www.hbvtc.edu.cn/
https://www.whvc.edu.cn/
http://www.hnuu.edu.cn/
http://www.ahsmxy.edu.cn/
http://www.ahsdxy.edu.cn/
http://www.fyvtc.edu.cn/
http://www.tlpt.edu.cn/
http://www.ahjgxy.edu.cn/
http://www.hnvtc.edu.cn/
http://www.ahiec.edu.cn/
http://www.hftc.edu.cn/
http://www.ahgmxy.edu.cn/
http://www.szzy.ah.cn/
http://www.lvtc.edu.cn/
http://www.aeitc.cn/
http://www.ahjt.edu.cn/
http://www.ahty.edu.cn/
http://www.ahzyy.cn/
http://www.ahyz.edu.cn/
https://www.htc.edu.cn/
http://www.czvtc.edu.cn/
http://www.czvtc.cn/
http://www.xcvtc.edu.cn/
http://www.ahrt.edu.cn/
http://www.ahdy.edu.cn/
http://www.ahyky.edu.cn/
http://www.ahcm.edu.cn/
http://www.ahjd.edu.cn/
http://www.ahgs.edu.cn/
http://www.ahzzy.edu.cn/
http://www.bzvtc.edu.cn/
http://www.ahgfxy.edu.cn/
http://www.aqvtc.cn/
http://www.ahysxy.edu.cn/
http://www.mtvtc.edu.cn/
http://www.ahcmxy.edu.cn/
http://www.ahibs.edu.cn/
http://www.ahgaxy.edu.cn/
http://www.ahlyxy.edu.cn/
http://www.ahsjxy.edu.cn/
http://www.ahcbxy.edu.cn/
http://www.ahptc.cn/
http://www.ahgy.edu.cn/
http://www.aqyyz.edu.cn/
http://www.hspx.edu.cn/
http://www.maszy.edu.cn/
http://www.tcnc.edu.cn/
http://www.hsxy.edu.cn/
http://www.czcitycollege.edu.cn/
http://www.ahqcxy.edu.cn/
http://www.wxwsxy.edu.cn/
http://www.hfys.edu.cn/
http://www.ahhmxy.edu.cn/
http://www.ahlsxy.edu.cn/
http://www.ahwsjkxy.edu.cn/
http://www.wbwsxy.edu.cn/
http://www.fyys.edu.cn/
http://www.wanboedu.cn/
http://www.hfet.edu.cn/
http://www.bhxy.edu.cn/
http://www.fky.edu.cn/
http://www.hfcfe.edu.cn/
http://www.aife.edu.cn/
http://www.lhxy.edu.cn/
http://www.gdxy.edu.cn/
http://www.bbetc.cn/
http://www.ahlyxy.com/
http://www.ahxdxy.edu.cn/
http://www.ahkyxy.edu.cn/
http://www.hfit.edu.cn/
http://www.yzzy.edu.cn/
http://www.hfkz.edu.cn/
http://www.hskjxy.edu.cn/
http://www.szhyxy.edu.cn/
http://www.whyywsxy.edu.cn/
http://www.whhyxy.edu.cn/
http://www.bbcgtxy.edu.cn/
http://www.whu.edu.cn
http://www.hust.edu.cn
http://www.wust.edu.cn
http://www.yangtzeu.edu.cn
http://www.wit.edu.cn
http://www.cug.edu.cn
http://www.wtu.edu.cn
http://www.whpu.edu.cn
http://www.whut.edu.cn
http://www.hbut.edu.cn
http://www.hzau.edu.cn
http://www.hbtcm.edu.cn
http://www.ccnu.edu.cn
http://www.hubu.edu.cn
http://www.hbnu.edu.cn
http://www.hgnu.edu.cn
http://www.hbmy.edu.cn
http://www.hjnu.edu.cn
http://www.hbuas.edu.cn
http://www.zuel.edu.cn
http://www.wipe.edu.cn
http://www.hifa.edu.cn
http://www.scuec.edu.cn
http://www.huat.edu.cn
http://www.hbeu.edu.cn
http://www.hblg.edu.cn
http://www.hbust.edu.cn
http://www.hbmu.edu.cn
http://www.jhun.edu.cn
http://www.ctgu.edu.cn
http://www.hbpa.edu.cn
http://www.jcut.edu.cn
http://www.whcm.edu.cn
http://www.hbue.edu.cn
http://www.wbu.edu.cn
http://www.hue.edu.cn
http://www.wtuv.edu.cn
http://www.wdu.edu.cn
http://www.hkxy.edu.cn
http://www.wsyu.edu.cn
http://www.wut.edu.cn
http://www.whsw.edu.cn
http://www.qcu.edu.cn
http://www.zxxy.hubu.edu.cn
http://www.whcityu.edu.cn
http://www.kjxy.ctgu.edu.cn
http://www.whwlu.edu.cn
http://www.gcx.hbut.edu.cn
http://www.witpt.edu.cn
http://www.wtuiec.edu.cn
http://www.wcit.edu.cn
http://www.wtbu.edu.cn
http://www.jzxy.edu.cn
http://www.wlxy.yangtzeu.edu.cn
http://www.hbsmxy.edu.cn
http://www.kjxy.huat.edu.cn
http://www.yhxy.hbmu.edu.cn
http://www.hbesxy.edu.cn
http://www.fsxy.hbue.edu.cn
http://www.tkxy.wipe.edu.cn
http://www.wlxy.hbnu.edu.cn
http://www.lgxy.hbuas.edu.cn
http://www.xjxy.hbeu.edu.cn
http://www.whxy.edu.cn
http://www.whxy.whu.edu.cn
http://www.wuhues.edu.cn
http://www.hxut.edu.cn
http://www.whmc.edu.cn
http://www.whsdy.edu.cn
http://www.hbsxhk.edu.cn
http://www.hgzy.edu.cn
http://www.cjxy.edu.cn
http://www.jzit.edu.cn
http://www.hbgy.edu.cn
http://www.ezu.edu.cn
http://www.whcvc.edu.cn
http://www.hbvtc.edu.cn
http://www.wspc.edu.cn
http://www.eszy.edu.cn
http://www.xyvtc.edu.cn
http://www.jzvtc.edu.cn
http://www.whgczy.edu.cn
http://www.xtzy.edu.cn
http://www.hblgzy.edu.cn
http://www.hbctc.edu.cn
http://www.hbzyy.edu.cn
http://www.whhh.edu.cn
http://www.wru.edu.cn
http://www.wsrj.edu.cn
http://www.hbsxzy.edu.cn
http://www.szvti.edu.cn
http://www.whetc.edu.cn
http://www.hbsy.edu.cn
http://www.hbcjxy.edu.cn
http://www.whjgxy.edu.cn
http://www.hbswkj.edu.cn
http://www.hbys.edu.cn
http://www.whjzy.edu.cn
http://www.xnvtc.edu.cn
http://www.cjgcxy.edu.cn
http://www.jhys.edu.cn
http://www.whmz.edu.cn
http://www.hbyjgl.edu.cn
http://www.hbcsxy.edu.cn
http://www.hbgtry.edu.cn
http://www.hbst.edu.cn
http://www.sxdl.edu.cn
http://www.hbkjzy.edu.cn
http://www.hbqnzy.edu.cn
http://www.hbgcxy.edu.cn
http://www.sxlyzy.edu.cn
http://www.tmzy.edu.cn
http://www.hbtyzy.edu.cn
http://www.xyqczy.edu.cn
http://www.hbyssf.edu.cn
http://www.hbtdzy.edu.cn
http://www.whhszy.edu.cn
http://www.jmzy.edu.cn
http://www.whql.edu.cn
http://www.xykjzy.edu.cn
http://www.yczy.edu.cn
http://www.jmthzy.edu.cn
http://www.whgmzy.edu.cn
http://www.hbkf.edu.cn
http://www.whkzy.edu.cn
http://www.whws.edu.cn
http://www.whxcb.edu.cn
http://www.wczy.edu.cn
http://www.whsmzy.edu.cn
http://www.hgkjzy.edu.cn
http://www.cjysgc.edu.cn
http://www.whggzy.edu.cn
http://www.hbjkzy.edu.cn
http://www.hbmg.edu.cn
https://www.xtu.edu.cn/
https://www.jsu.edu.cn/
https://www.hnu.edu.cn/
https://www.csu.edu.cn/
https://www.hnust.edu.cn/
https://www.csust.edu.cn/
https://www.hunau.edu.cn/
https://www.csuft.edu.cn/
https://www.hnucm.edu.cn/
https://www.hunnu.edu.cn/
https://www.hnit.edu.cn/
https://www.xnu.edu.cn/
https://www.hynu.edu.cn/
https://www.syu.edu.cn/
https://www.hhtc.edu.cn/
https://www.hnwu.edu.cn/
https://www.huse.edu.cn/
https://www.huhst.edu.cn/
https://www.hutb.edu.cn/
https://www.usc.edu.cn/
https://www.cczu.edu.cn/
https://www.hnie.edu.cn/
https://www.hncu.edu.cn/
https://www.hnpu.edu.cn/
https://www.hufe.edu.cn/
https://www.hnpolice.com/
https://www.hut.edu.cn/
https://www.hnwu.edu.cn/
https://www.hnfnu.edu.cn/
https://www.hnmu.edu.cn/
https://www.csgy.edu.cn/
https://www.csnu.edu.cn/
https://www.hnqj.edu.cn/
https://www.nudt.edu.cn/
https://www.csmu.edu.cn/
https://www.hieu.edu.cn/
https://xxxy.xtu.edu.cn/
https://kjxy.hut.edu.cn/
https://xxxy.hnust.edu.cn/
https://ssxy.usc.edu.cn/
https://www.xtit.edu.cn/
https://dfkj.hunau.edu.cn/
https://swxy.csuft.edu.cn/
https://www.cdu.edu.cn/
https://www.yyu.edu.cn/
https://nyxy.hynu.edu.cn/
https://yjsy.hnie.edu.cn/
https://xxxy.hnucm.edu.cn/
https://www.zjjc.edu.cn/
https://cnxy.csust.edu.cn/
https://www.hnyyxy.com/
https://www.hnuit.edu.cn/
https://www.hnjtgc.edu.cn/
https://www.hnswxy.com/
https://www.cskjxy.edu.cn/
https://www.xzyesf.com/
https://www.csmzxy.edu.cn/
https://www.hnivit.edu.cn/
https://www.zzsf.edu.cn/
https://www.hnxxjsxy.com/
https://www.hntax.edu.cn/
https://www.hnmtc.edu.cn/
https://www.cavtc.cn/
https://www.hncmc.edu.cn/
https://www.yzzy.edu.cn/
https://www.hntdzy.com/
https://www.hnkjxy.edu.cn/
https://www.hnbemc.edu.cn/
https://www.hnjtzy.edu.cn/
https://www.hnswxy.edu.cn/
https://www.hntyxy.edu.cn/
https://www.hngczy.edu.cn/
https://www.bxxy.com/
https://www.hnwmxy.edu.cn/
https://www.hnwlxy.edu.cn/
https://www.syzyedu.com/
https://www.hnsfjy.edu.cn/
https://www.hnslxy.com/
https://www.hnshjx.com/
https://www.hnydxy.net/
https://www.xtzywx.com/
https://www.czzy.edu.cn/
https://www.ldzy.edu.cn/
https://www.zjjhy.net/
https://www.cseptc.net/
https://www.hnyszyxy.com/
https://www.hnjdzy.net/
https://www.cszyedu.cn/
https://www.hhzjxy.cn/
https://www.yyzjxy.cn/
https://www.cdzy.cn/
https://www.hnhgzy.com/
https://www.hnucjzy.edu.cn/
https://www.hnsyzy.edu.cn/
https://www.hnzyy.com/
https://www.hnmzxy.com/
https://www.xxmzzy.com/
https://www.hncyzyxy.com/
https://www.yyzy.edu.cn/
https://www.hnmyxy.com/
https://www.hnjyzy.com/
https://www.hnlgzy.net/
https://www.csdzy.edu.cn/
https://www.hnsdzy.com/
https://www.hnxlzy.com/
https://www.hngtzy.com/
https://www.hntky.com/
https://www.hnaqzy.net/
https://www.hndqzy.com/
https://www.yyygz.com/
https://www.hngfzy.com/
https://www.cswszy.com/
https://www.hnspxy.com/
https://www.hnyszy.com/
https://www.hnysedu.com/
https://www.xnyesf.com/
https://www.hnldxy.com/
https://www.hhsfxy.com/
https://www.yzsfxy.com/
https://www.hyyesf.com/
https://www.csyesfxy.com/
https://www.yysfxy.com/
https://www.ldyesf.com/
https://www.cdkjzy.com/
https://www.sysyzy.com/
https://www.hhgszy.com/
https://www.xtkjzy.com/
https://www.csnfu.com/
https://www.xxsyzy.com/
https://www.hnflc.com/
https://www.hndsxy.com/
https://www.hnevc.com/
https://www.hngfzyxy.com/
https://www.hngszyxy.com/
https://www.sanyedu.com/
https://www.jlqcxy.com/
https://www.csjdzyxy.com/
https://www.cswcysxy.com/
https://www.yyxdfwzy.com/
https://www.czskzy.com/
https://www.hykjzyxy.com/
https://www.csyyjkzy.com/
https://www.cskjzyxy.com/
https://www.zzkjzyxy.com/
https://www.hylgzyxy.com/
https://www.czztkjzy.com/
http://www.sysu.edu.cn
http://www.jnu.edu.cn
http://www.stu.edu.cn
http://www.scut.edu.cn
http://www.scau.edu.cn
http://www.gdou.edu.cn
http://www.gzhmu.edu.cn
http://www.gdmu.edu.cn
http://www.gzucm.edu.cn
http://www.gdpu.edu.cn
http://www.scnu.edu.cn
http://www.sgu.edu.cn
http://www.hzu.edu.cn
http://www.hstc.edu.cn
http://www.lntc.edu.cn
http://www.zqu.edu.cn
http://www.jyu.edu.cn
http://www.gipe.edu.cn
http://www.gzarts.edu.cn
http://www.xhcom.edu.cn
http://www.gpnu.edu.cn
http://www.szu.edu.cn
http://www.gdufe.edu.cn
http://www.gzhu.edu.cn
http://www.gzmtu.edu.cn
http://www.gdppla.edu.cn
http://www.zhku.edu.cn
http://www.wyu.edu.cn
http://www.gduf.edu.cn
http://www.gdupt.edu.cn
http://www.dgut.edu.cn
http://www.gdut.edu.cn
http://www.gdufs.edu.cn
http://www.fosu.edu.cn
http://www.smu.edu.cn
http://www.gdei.edu.cn
http://www.sustech.edu.cn
http://www.sztu.edu.cn
http://www.gdqy.edu.cn
http://www.szpt.edu.cn
http://www.zqmc.edu.cn
http://www.szlgu.edu.cn
http://www.baiyun.edu.cn
http://www.zsc.edu.cn
http://www.peizheng.edu.cn
http://www.neusoft.edu.cn
http://www.gzcu.edu.cn
http://www.gzrj.edu.cn
http://www.nfu.edu.cn
http://www.ngxy.edu.cn
http://www.hsxy.edu.cn
http://www.zjkju.edu.cn
http://www.zjxy.edu.cn
http://www.gzit.edu.cn
http://www.hualixy.edu.cn
http://www.gdyyxy.edu.cn
http://www.gzcc.edu.cn
http://www.blzhxy.edu.cn
http://www.zhkju.edu.cn
http://www.gzgs.edu.cn
http://www.gzkju.edu.cn
http://www.gdust.edu.cn
http://www.gdlgu.edu.cn
http://www.gdgs.edu.cn
http://www.dgcity.edu.cn
http://www.xinhua.edu.cn
http://www.uic.edu.cn
http://www.cuhk.edu.cn
http://www.hkust-gz.edu.cn
http://www.cityu-dg.edu.cn
http://www.smbu.edu.cn
http://www.gtiit.edu.cn
http://www.sdpt.edu.cn
http://www.gdjtc.edu.cn
http://www.gdsl.edu.cn
http://www.gdsngs.edu.cn
http://www.caac.edu.cn
http://www.gzpyp.edu.cn
http://www.gdss.edu.cn
http://www.gdaib.edu.cn
http://www.fspt.edu.cn
http://www.gdkjxy.edu.cn
http://www.gdyzy.edu.cn
http://www.gdxz.edu.cn
http://www.gdtyzy.edu.cn
http://www.gdzy.edu.cn
http://www.gdcj.edu.cn
http://www.gdnz.edu.cn
http://www.gdmec.edu.cn
http://www.swpt.edu.cn
http://www.ldzy.edu.cn
http://www.yjzy.edu.cn
http://www.hypt.edu.cn
http://www.gupt.edu.cn
http://www.stpt.edu.cn
http://www.jypt.edu.cn
http://www.szitt.edu.cn
http://www.qypt.edu.cn
http://www.gditt.edu.cn
http://www.gdsf.edu.cn
http://www.gdwyy.edu.cn
http://www.gdwy.edu.cn
http://www.gztyzy.edu.cn
http://www.gzgc.edu.cn
http://www.zstp.edu.cn
http://www.jmpt.edu.cn
http://www.mmpt.edu.cn
http://www.zhcpt.edu.cn
http://www.gdlgzy.edu.cn
http://www.gzcsxy.edu.cn
http://www.gdgczy.edu.cn
http://www.gztlxy.edu.cn
http://www.gdkm.edu.cn
http://www.gzkm.edu.cn
http://www.zspt.edu.cn
http://www.dgpt.edu.cn
http://www.gdhbzy.edu.cn
http://www.gdqnzy.edu.cn
http://www.gdyszy.edu.cn
http://www.hzwzy.edu.cn
http://www.gdstgc.edu.cn
http://www.hzcc.edu.cn
http://www.mmjkedu.cn
http://www.mmyssf.edu.cn
http://www.gzwszy.edu.cn
http://www.hzgc.edu.cn
http://www.gdjmzy.edu.cn
http://www.mmnkj.edu.cn
http://www.gdjmys.edu.cn
http://www.gdcm.edu.cn
http://www.gzys.edu.cn
http://www.stys.edu.cn
http://www.mzzy.edu.cn
http://www.czwszy.edu.cn
http://www.yfzyy.edu.cn
http://www.zjys.edu.cn
http://www.szcc.edu.cn
http://www.cszy.edu.cn
http://www.hlu.edu.cn
http://www.gdxa.edu.cn
http://www.gzkd.edu.cn
http://www.zhuai.edu.cn
http://www.lnpc.edu.cn
http://www.gdysyy.edu.cn
http://www.gzswjj.edu.cn
http://www.nyp.edu.cn
http://www.hzec.edu.cn
http://www.gzxd.edu.cn
http://www.gzhn.edu.cn
http://www.hlkj.edu.cn
http://www.gzpj.edu.cn
http://www.gzsd.edu.cn
http://www.gdwlsy.edu.cn
http://www.gzcj.edu.cn
http://www.gdnf.edu.cn
http://www.hszy.edu.cn
http://www.hxzy.edu.cn
http://www.gddh.edu.cn
http://www.gdcxxy.edu.cn
http://www.gdxxgc.edu.cn
http://www.bgy.edu.cn
http://www.gdjdgl.edu.cn
http://www.zqhk.edu.cn
http://www.glzy.edu.cn
https://www.hainanu.edu.cn/
http://www.hntoi.edu.cn/
http://www.hainnu.edu.cn/
http://www.hainmc.edu.cn/
http://www.qtnu.edu.cn/
http://www.hkc.edu.cn/
https://www.syau.edu.cn/
https://www.hnkjedu.cn/
https://www.buas-hainan.cn/
http://www.hnzy.edu.cn/
http://www.hnsoftedu.com/
http://www.hnplc.com/
http://www.hnflc.edu.cn/
https://www.hnjmxy.edu.cn/
http://www.hnty.edu.cn/
http://www.hnwsjkzyxy.com/
https://www.hkvc.edu.cn/
http://www.hnart.edu.cn/
http://www.sycsxy.cn/
http://www.hn工商.edu.cn/
http://www.hnasatc.com/
http://www.sylgxy.com/
http://www.syzr.edu.cn/
http://www.hnjkglxy.com/
http://www.hnxinsilu.com/
http://www.syhlxy.com/
http://www.scu.edu.cn
http://www.swjtu.edu.cn
http://www.uestc.edu.cn
http://www.swpu.edu.cn
http://www.cdut.edu.cn
http://www.swust.edu.cn
http://www.cuit.edu.cn
http://www.suse.edu.cn
http://www.xhu.edu.cn
http://www.cafuc.edu.cn
http://www.sicau.edu.cn
http://www.xcc.edu.cn
http://www.swmu.edu.cn
http://www.cdutcm.edu.cn
http://www.nsmc.edu.cn
http://www.sicnu.edu.cn
http://www.cwnu.edu.cn
http://www.mnu.edu.cn
http://www.njtc.edu.cn
http://www.yibinu.edu.cn
http://www.sasu.edu.cn
http://www.abtc.edu.cn
http://www.lssc.edu.cn
http://www.swufe.edu.cn
http://www.cdsu.edu.cn
http://www.sccm.cn
http://www.swun.edu.cn
http://www.cdu.edu.cn
http://www.cdit.edu.cn
http://www.pzhu.edu.cn
http://www.sctu.edu.cn
http://www.scun.edu.cn
http://www.scpolicec.edu.cn
http://www.cmc.edu.cn
http://www.cdnu.edu.cn
http://www.scetc.edu.cn
http://www.cdnsc.edu.cn
http://www.cdart.edu.cn
http://www.cduestc.edu.cn
http://www.cdutetc.edu.cn
http://www.scmc.edu.cn
http://www.yxhm.edu.cn
http://www.cdwlc.edu.cn
http://www.sctbc.edu.cn
http://www.cisuedu.com
http://www.scit.edu.cn
http://www.cdjcc.edu.cn
http://www.tfswufe.edu.cn
http://www.scujj.edu.cn
http://www.scuci.edu.cn
http://www.mycc.edu.cn
http://www.swjtuhc.edu.cn
http://www.scftvc.edu.cn
http://www.geely.edu.cn
http://www.cdtc.edu.cn
http://www.cdavc.edu.cn
http://www.scept.edu.cn
http://www.cdvtc.edu.cn
http://www.sccvtc.edu.cn
http://www.swcvc.edu.cn
http://www.nczy.edu.cn
http://www.njvtc.edu.cn
http://www.sasc.edu.cn
http://www.sptc.edu.cn
http://www.scemvtc.edu.cn
http://www.myvtc.edu.cn
http://www.sjvtc.edu.cn
http://www.scgzy.edu.cn
http://www.scatc.edu.cn
http://www.dzvtc.edu.cn
http://www.cdnkxy.edu.cn
http://www.ybzy.edu.cn
http://www.lzzy.edu.cn
http://www.mszy.edu.cn
http://www.sczyxy.edu.cn
http://www.lszy.edu.cn
http://www.yazyc.edu.cn
http://www.scsw.edu.cn
http://www.sjsf.edu.cn
http://www.gavtc.edu.cn
http://www.scitc.edu.cn
http://www.stdu.edu.cn
http://www.scyszy.edu.cn
http://www.sczyz.edu.cn
http://www.scci.edu.cn
http://www.sccfe.edu.cn
http://www.scys.edu.cn
http://www.cbys.edu.cn
http://www.scwskf.edu.cn
http://www.cnys.edu.cn
http://www.scnvc.edu.cn
http://www.cdivtc.edu.cn
http://www.cdgmxy.edu.cn
http://www.xcmzys.edu.cn
http://www.abzy.edu.cn
http://www.dzzyy.edu.cn
http://www.njwszy.edu.cn
http://www.ncwly.edu.cn
http://www.gzzy.edu.cn
http://www.sctyzy.edu.cn
http://www.xcmzy.edu.cn
http://www.tianyicollege.edu.cn
http://www.sctuopu.edu.cn
http://www.scaev.edu.cn
http://www.scwcmc.edu.cn
http://www.schxmvc.edu.cn
http://www.sckjzy.edu.cn
http://www.sccvc.edu.cn
http://www.scxzy.edu.cn
http://www.scczy.edu.cn
http://www.scshzy.edu.cn
http://www.scqczy.edu.cn
http://www.bzvtc.edu.cn
http://www.xwqcxy.edu.cn
http://www.scdzjx.edu.cn
http://www.scwxzy.edu.cn
http://www.xnhkzy.edu.cn
http://www.scyyjs.edu.cn
http://www.msyzy.edu.cn
http://www.tfxxzy.edu.cn
http://www.dyct.edu.cn
http://www.dykm.edu.cn
http://www.jycjzy.edu.cn
http://www.tfhtzy.edu.cn
http://www.tftkzy.edu.cn
http://www.nckjzy.edu.cn
http://www.pzhpx.edu.cn
http://www.zyky.edu.cn
http://www.zyhj.edu.cn
http://www.ncdygy.edu.cn
http://www.myfx.edu.cn
http://www.dynkzy.edu.cn
http://www.lzylqx.edu.cn
http://www.zgzyjsxy.edu.cn
http://www.gyzh.edu.cn
http://www.snnyzy.edu.cn
http://www.sngc.edu.cn
http://www.snzy.edu.cn
http://www.cdgtjt.edu.cn
https://www.gzu.edu.cn/
https://www.gmc.edu.cn/
https://www.zmu.edu.cn/
https://www.gzy.edu.cn/
https://www.gznu.edu.cn/
http://www.zync.edu.cn/
https://www.tru.edu.cn/
http://www.xynun.edu.cn/
http://www.asu.edu.cn/
http://www.gzeat.edu.cn/
http://www.kluniv.edu.cn/
http://www.qnnu.edu.cn/
https://www.gufe.edu.cn/
https://www.gzmu.edu.cn/
http://www.gyu.edu.cn/
http://www.lpsnu.edu.cn/
http://www.gzcc.edu.cn/
http://www.gzjd.edu.cn/
http://www.gyky.edu.cn/
https://www.gznc.edu.cn/
https://www.git.edu.cn/
http://www.gzjtzy.edu.cn/
http://szxy.gzy.edu.cn/
http://www.gzqnxy.edu.cn/
http://www.gzqnkxy.edu.cn/
http://www.gyitk.edu.cn/
http://www.gyrwxy.edu.cn/
http://ykjxy.zmu.edu.cn/
http://sqmyxy.gmc.edu.cn/
http://www.mtxy.edu.cn/
http://www.qnmc.edu.cn/
http://www.gzhtzy.edu.cn/
http://www.gzeic.edu.cn/
http://www.aszy.edu.cn/
http://www.qdnpt.edu.cn/
http://www.qnvmc.edu.cn/
http://www.zyzy.edu.cn/
http://www.gzky.edu.cn/
http://www.gzdlzy.edu.cn/
http://www.lpszy.edu.cn/
https://www.trzy.edu.cn/
http://www.qxnzy.edu.cn/
https://www.gzqy.edu.cn/
http://www.zunyiyizhuan.edu.cn/
http://www.gyvtc.edu.cn/
http://www.bjvtc.edu.cn/
https://www.gzvte.edu.cn/
http://www.gyys.edu.cn/
http://www.trys.edu.cn/
http://www.qnys.edu.cn/
http://www.bjyz.edu.cn/
http://www.gzjszy.edu.cn/
http://www.bjys.edu.cn/
http://www.gznyzy.edu.cn/
http://www.gzsdzy.edu.cn/
http://www.gzdszy.edu.cn/
http://www.gzdzkjzy.edu.cn/
http://www.gzzbzy.edu.cn/
http://www.gzjkzy.edu.cn/
http://www.gzspgc.edu.cn/
http://www.gzjmzy.edu.cn/
http://www.gzhlzy.edu.cn/
http://www.lpsy.edu.cn/
http://www.bjgy.edu.cn/
http://www.gzjdzy.edu.cn/
http://www.gzcjzy.edu.cn/
http://www.gzwhlyzy.edu.cn/
http://www.gzhtzyxy.edu.cn/
http://www.gztyzy.edu.cn/
http://www.gzcmzy.edu.cn/
http://www.gzstnyzy.edu.cn/
http://www.qdnlg.edu.cn/
https://www.gzcsxy.cn/
http://www.sheng-hua.cn/
http://www.gzgszy.edu.cn/
http://www.gzieu.com/
http://www.gzgmzy.edu.cn/
http://www.gzust.edu.cn/
http://www.gzmyhkzy.edu.cn/
http://www.gztrsjzy.edu.cn/
http://www.ynu.edu.cn
http://www.kmust.edu.cn
http://www.ynau.edu.cn
http://www.swfu.edu.cn
http://www.kmmu.edu.cn
http://www.dali.edu.cn
http://www.ynutcm.edu.cn
http://www.ynnu.edu.cn
http://www.ztu.edu.cn
http://www.qjnu.edu.cn
http://www.peuni.edu.cn
http://www.bsu.edu.cn
http://www.uoh.edu.cn
http://www.ynufe.edu.cn
http://www.ynart.edu.cn
http://www.ynni.edu.cn
http://www.yxnu.edu.cn
http://www.cxnu.edu.cn
http://www.ynpc.edu.cn
http://www.kmu.edu.cn
http://www.wsu.edu.cn
http://www.dxstnu.edu.cn
http://www.wyuas.edu.cn
http://www.ljnu.edu.cn
http://www.dhsf.edu.cn
http://www.ynjgy.com
http://www.ynudcc.edu.cn
http://www.ljtu.edu.cn
http://www.kust-jq.edu.cn
http://www.kmcc.edu.cn
http://www.kmwlc.edu.cn
http://www.hyxy.kmmu.edu.cn
http://www.kmcmc.edu.cn
http://www.ynig.edu.cn
http://www.kmyz.edu.cn
http://www.yngtxy.edu.cn
http://www.ynjtc.edu.cn
http://www.kmgy.edu.cn
http://www.ynavc.edu.cn
http://www.ynsfxy.edu.cn
http://www.ynwy.edu.cn
http://www.ynsports.edu.cn
http://www.xsbnzy.edu.cn
http://www.yxat.edu.cn
http://www.ynny.edu.cn
http://www.yngf.edu.cn
http://www.ynjd.edu.cn
http://www.ynfvc.edu.cn
http://www.qjyz.edu.cn
http://www.cxmtc.edu.cn
http://www.bszyy.edu.cn
http://www.ynxy.edu.cn
http://www.dhvc.edu.cn
http://www.ynxd.edu.cn
http://www.ynctv.edu.cn
http://www.hhwzy.edu.cn
http://www.dlnl.edu.cn
http://www.ynxf.edu.cn
http://www.yncj.edu.cn
http://www.kmtdzy.edu.cn
http://www.ztwszy.edu.cn
http://www.dlhzy.edu.cn
http://www.ynsdzy.edu.cn
http://www.ynqf.edu.cn
http://www.ynts.edu.cn
http://www.yngm.edu.cn
http://www.ynjtzy.edu.cn
http://www.kmyssf.edu.cn
http://www.qjvtc.edu.cn
http://www.hhvtc.edu.cn
http://www.yxvtc.edu.cn
http://www.bsvtc.edu.cn
http://www.ztvtc.edu.cn
http://www.wszy.edu.cn
http://www.ljvtc.edu.cn
http://www.xglzy.edu.cn
http://www.njzy.edu.cn
http://www.lczyxy.edu.cn
http://www.yngyxx.edu.cn
http://www.ynkjxx.edu.cn
http://www.kmart.edu.cn
http://www.ynccs.edu.cn
http://www.ynenc.edu.cn
http://www.ynxxzy.edu.cn
http://www.ynjmgj.edu.cn
http://www.ynsxzy.edu.cn
http://www.ynswzy.edu.cn
http://www.kmhv.edu.cn
http://www.ynws.edu.cn
http://www.ynyyjk.edu.cn
http://www.ynlgedu.cn
http://www.lzu.edu.cn
http://www.lut.edu.cn
http://www.lzjtu.edu.cn
http://www.gsau.edu.cn
http://www.gszy.edu.cn
http://www.nwnu.edu.cn
http://www.lzcu.edu.cn
http://www.ldxy.edu.cn
http://www.tsnu.edu.cn
http://www.hxu.edu.cn
http://www.lzufe.edu.cn
http://www.xbmu.edu.cn
http://www.gsli.edu.cn
http://www.gnun.edu.cn
http://www.luas.edu.cn
http://www.gsmc.edu.cn
http://www.lzit.edu.cn
http://www.lzpuvt.edu.cn
http://www.lzre.edu.cn
http://www.lntc.edu.cn
http://www.jqvtc.edu.cn
http://www.gspc.edu.cn
http://www.gsly.edu.cn
http://www.lzgs.edu.cn
http://www.lzbw.edu.cn
http://www.lzist.edu.cn
http://www.dxss.edu.cn
http://www.gscat.edu.cn
http://www.lzzy.edu.cn
http://www.gspc.edu.cn
http://www.wwvc.edu.cn
http://www.gsjtxy.edu.cn
http://www.gsny.edu.cn
http://www.gsxm.edu.cn
http://www.gsgt.edu.cn
http://www.gsjdx.edu.cn
http://www.gsys.edu.cn
http://www.byky.edu.cn
http://www.gswszy.edu.cn
http://www.qyvtc.edu.cn
http://www.lxzx.edu.cn
http://www.lzx.edu.cn
http://www.plvtc.edu.cn
http://www.plvc.edu.cn
http://www.lzavc.edu.cn
http://www.gscmxy.edu.cn
http://www.dxzy.edu.cn
http://www.lzwy.edu.cn
http://www.lzkjzy.edu.cn
http://www.byxy.edu.cn
https://www.nwu.edu.cn/
https://www.xjtu.edu.cn/
https://www.nwpu.edu.cn/
https://www.xaut.edu.cn/
https://www.xidian.edu.cn/
http://www.xatu.edu.cn/
https://www.xauat.edu.cn/
https://www.xust.edu.cn/
https://www.xsyu.edu.cn/
https://www.sust.edu.cn/
https://www.xpu.edu.cn/
https://www.chd.edu.cn/
https://www.nwsuaf.edu.cn/
https://www.sntcm.edu.cn/
https://www.snnu.edu.cn/
https://www.yau.edu.cn/
https://www.snut.edu.cn/
https://www.bjwlxy.edu.cn/
http://www.xysf.edu.cn/
https://www.wnu.edu.cn/
https://www.xisu.edu.cn/
https://www.nwupl.edu.cn/
https://www.xaipe.edu.cn/
https://www.xacom.edu.cn/
https://www.xafa.edu.cn/
https://www.xawl.edu.cn/
https://www.yulinu.edu.cn/
https://www.slxy.edu.cn/
https://www.aku.edu.cn/
https://www.xaufe.edu.cn/
https://www.xiyou.edu.cn/
https://www.xaau.edu.cn/
https://www.xiyi.edu.cn/
https://www.snsy.edu.cn/
https://www.sxpolice.edu.cn/
https://www.fmmu.edu.cn/
https://www.peihua.cn/
https://www.eurasia.edu.cn/
https://www.xaiu.edu.cn/
https://www.xafy.edu.cn/
https://www.xijing.edu.cn/
https://www.xasyu.edu.cn/
https://www.csiic.edu.cn/
http://www.sxfyc.edu.cn/
http://www.xjgyedu.cn/
https://www.xjtucc.edu.cn/
https://www.xdxd.edu.cn/
https://www.hqc.edu.cn/
https://www.xzcedu.cn/
https://www.hjxy.edu.cn/
https://www.xags.edu.cn/
https://www.yaucx.edu.cn/
https://www.xdca.edu.cn/
https://www.xaqu.edu.cn/
https://www.mdit.edu.cn/
https://www.xaiu.edu.cn/
https://www.xinghua.edu.cn/
https://www.xlgxy.edu.cn/
https://www.gxdx.edu.cn/
https://www.sxpi.edu.cn/
https://www.ylvtc.edu.cn/
http://www.xaepi.edu.cn/
http://www.sxnyzy.edu.cn/
https://www.sngy.edu.cn/
https://www.xihang.edu.cn/
http://www.sxczy.edu.cn/
https://www.sxjt.edu.cn/
https://www.sxzy.edu.cn/
https://www.stedu.edu.cn/
https://www.bjvtc.edu.cn/
https://www.sxhkxy.edu.cn/
http://www.sptc.edu.cn/
http://www.sxjm.edu.cn/
https://www.xatzy.edu.cn/
https://www.xianyangzhiyuan.edu.cn/
https://www.xzyedu.cn/
http://www.slzy.edu.cn/
https://www.hzvtc.edu.cn/
https://www.yaztc.edu.cn/
https://www.wnzy.edu.cn/
https://www.akvtc.edu.cn/
http://www.tczyxy.edu.cn/
https://www.sxqnzy.edu.cn/
https://www.sxgsxy.edu.cn/
https://www.ylzy.edu.cn/
https://www.sxyszy.edu.cn/
http://www.smzy.edu.cn/
https://www.sxjdzy.edu.cn/
http://www.xianht.com/
http://www.xacsjs.edu.cn/
http://www.sxdi.edu.cn/
http://www.xahtxy.edu.cn/
http://www.xajkxy.edu.cn/
http://www.sxlypr.edu.cn/
http://www.xayz.edu.cn/
http://www.bjshzyxy.edu.cn/
http://www.ylnkjxy.edu.cn/
http://www.bjzbzyxy.edu.cn/
https://www.qhu.edu.cn/
https://www.qhnu.edu.cn/
https://www.qhmu.edu.cn/
https://www.qhvu.edu.cn/
https://www.qhlg.edu.cn/
http://klxy.qhu.edu.cn/
http://www.qhhealthcollege.cn/
http://www.qhpolice.edu.cn/
http://www.qhnmkjzy.edu.cn/
http://www.qhcj.edu.cn/
http://www.xncszy.edu.cn/
http://www.qhgz.edu.cn/
http://www.qhcdmzyxy.edu.cn/
http://www.gxu.edu.cn
http://www.gxust.edu.cn
http://www.guet.edu.cn
http://www.glut.edu.cn
http://www.gxmu.edu.cn
http://www.ymun.edu.cn
http://www.gxtcmu.edu.cn
http://www.glmc.edu.cn
http://www.gxnu.edu.cn
http://www.nnnu.edu.cn
http://www.gxmnu.edu.cn
http://www.hcnu.edu.cn
http://www.ylu.edu.cn
http://www.gxau.edu.cn
http://www.gxmzu.edu.cn
http://www.bsuc.edu.cn
http://www.gxuwz.edu.cn
http://www.gxstnu.edu.cn
http://www.gxufe.edu.cn
http://www.bbgu.edu.cn
http://www.guat.edu.cn
http://www.glit.edu.cn
http://www.hzu.edu.cn
http://www.gxjcxy.edu.cn
http://www.gxnavt.edu.cn
http://www.gxzf.edu.cn
http://www.nnvtc.edu.cn
http://www.glnu.edu.cn
http://www.lzvtc.edu.cn
http://www.nanningu.edu.cn
http://www.bhadi.edu.cn
http://www.lzgc.edu.cn
http://www.xshl.edu.cn
http://www.glxy.edu.cn
http://www.syxy.nnnu.edu.cn
http://www.syxyc.edu.cn
http://www.git.edu.cn
http://www.nnit.edu.cn
http://www.gxufl.edu.cn
http://www.bhbh.edu.cn
http://www.gxcu.edu.cn
http://www.gxjdx.edu.cn
http://www.gxtyz.edu.cn
http://www.gxsdzy.edu.cn
http://www.gxzjy.edu.cn
http://www.gxstzy.edu.cn
http://www.gxjtc.edu.cn
http://www.gxgyxy.edu.cn
http://www.gxibvc.edu.cn
http://www.lztdzy.edu.cn
http://www.gxjszy.edu.cn
http://www.gxxdzy.edu.cn
http://www.bhzyxy.edu.cn
http://www.gxjmy.edu.cn
http://www.gxgsxy.edu.cn
http://www.gxdlzy.edu.cn
http://www.lzcszy.edu.cn
http://www.bszyxy.edu.cn
http://www.wzzy.edu.cn
http://www.gxys.edu.cn
http://www.gxwszy.edu.cn
http://www.gxjrxy.edu.cn
http://www.gxaqzy.edu.cn
http://www.gxzrzy.edu.cn
http://www.qzys.edu.cn
http://www.gxzzgc.edu.cn
http://www.gxwlzy.edu.cn
http://www.fcgvtc.edu.cn
http://www.gxix.edu.cn
http://www.gxngzy.edu.cn
http://www.czys.edu.cn
http://www.gxzlzy.edu.cn
http://www.ylvtc.edu.cn
http://www.gxznzz.edu.cn
http://www.glshjk.edu.cn
http://www.glsszy.edu.cn
http://www.gxyyzy.edu.cn
http://www.gxyh.edu.cn
http://www.gxgcxy.edu.cn
http://www.gxlgzy.edu.cn
http://www.gxjjxy.edu.cn
http://www.gxkzzy.edu.cn
http://www.gxpx.edu.cn
http://www.gxzyzy.edu.cn
http://www.yczyjs.edu.cn
http://www.gxltzy.edu.cn
http://www.wzys.edu.cn
http://www.bhkyzy.edu.cn
http://www.glxxgc.edu.cn
https://www.nxu.edu.cn/
https://www.nxmu.edu.cn/
https://www.nxnu.edu.cn/
https://www.nbue.edu.cn/
http://www.nxist.edu.cn/
http://xhc.nxu.edu.cn/
http://www.ycu.edu.cn/
http://www.yctu.edu.cn/
http://www.nxmzy.edu.cn/
http://www.nxgy.edu.cn/
https://www.nxzy.edu.cn/
http://www.nxgs.edu.cn/
http://www.nxcy.edu.cn/
http://www.nxjy.edu.cn/
http://www.nxjzy.edu.cn/
http://www.nxpt.edu.cn/
http://www.nxys.edu.cn/
http://www.nxart.edu.cn/
http://www.nxty.edu.cn/
http://www.szsgm.edu.cn/
http://www.nxwj.edu.cn/
http://www.nxjt.edu.cn/
https://www.xju.edu.cn/
https://www.taru.edu.cn/
https://www.xjau.edu.cn/
https://www.shzu.edu.cn/
https://www.xjmu.edu.cn/
https://www.xjnu.edu.cn/
https://www.ksu.edu.cn/
https://www.ylnu.edu.cn/
https://www.xjufe.edu.cn/
https://www.xjart.edu.cn/
https://www.xjie.edu.cn/
https://www.cjc.edu.cn/
https://www.xjpolice.edu.cn/
https://www.xjit.edu.cn/
https://www.xjmc2.edu.cn/
https://www.xjstc.edu.cn/
https://www.xjzfxy.edu.cn/
https://www.htxy.edu.cn/
https://www.xjnzy.edu.cn/
https://www.uqzy.edu.cn/
https://www.xjjtu.edu.cn/
https://www.xjgyxy.edu.cn/
https://kjxy.xjau.edu.cn/
https://www.tszy.edu.cn/
https://www.wzzy.edu.cn/
https://www.kzvtc.edu.cn/
https://www.xjjdzy.edu.cn/
https://www.xjqg.edu.cn/
https://www.cjvtc.edu.cn/
https://www.ylzyjsxy.edu.cn/
https://www.akszy.edu.cn/
https://www.byglzy.edu.cn/
https://www.xjjszy.edu.cn/
https://www.shzzy.edu.cn/
https://www.xjvu.edu.cn/
https://www.xjtyzy.edu.cn/
https://www.xjyyzy.edu.cn/
https://www.xjtc.edu.cn/
https://www.xjtdzy.edu.cn/
https://www.xxjzy.edu.cn/
https://www.hmzy.edu.cn/
https://www.tlfzy.edu.cn/
https://www.bltzy.edu.cn/
https://www.htzyxy.edu.cn/
https://www.shzgc.edu.cn/
https://www.kszyxy.edu.cn/
https://www.kzlszy.edu.cn/
https://www.altzy.edu.cn/
https://www.tczyxy.edu.cn/
https://www.tlzy.edu.cn/
https://www.xjgyzy.edu.cn/
https://www.tmgzy.edu.cn/
https://www.xjsfzy.edu.cn/
https://www.aksgyzy.edu.cn/
https://www.kslgzy.edu.cn/
https://www.tmzy.edu.cn/
https://www.kkdlzy.edu.cn/
https://www.xxzyxy.edu.cn/
https://www.kyzyxy.edu.cn/
https://www.shzyxy.edu.cn/
https://www.xjnyzy.edu.cn/
https://www.xjxdzy.edu.cn/
https://www.xjkjzy.edu.cn/
https://www.xjkxzy.edu.cn/
https://www.xza.edu.cn/
https://www.utibet.edu.cn/
https://www.xzmu.edu.cn/
https://www.ttmc.edu.cn/
https://www.lssy.edu.cn/
http://www.xzpolice.edu.cn/
https://www.xzzd.edu.cn/
http://www.hlju.edu.cn
http://www.hit.edu.cn
http://www.hrbust.edu.cn
http://www.hrbeu.edu.cn
http://www.usth.edu.cn
http://www.nepu.edu.cn
http://www.jmsu.edu.cn
http://www.hljby.edu.cn
http://www.neau.edu.cn
http://www.nefu.edu.cn
http://www.hrbmu.edu.cn
http://www.hljucm.edu.cn
http://www.mdjmu.edu.cn
http://www.hrbnu.edu.cn
http://www.qqhru.edu.cn
http://www.mdjnu.edu.cn
http://www.hrbu.edu.cn
http://www.dqsy.edu.cn
http://www.shxy.edu.cn
http://www.hrbcu.edu.cn
http://www.hrbipe.edu.cn
http://www.hfu.edu.cn
http://www.qmu.edu.cn
http://www.hljit.edu.cn
http://www.hljit.edu.cn
http://www.hhhxy.edu.cn
http://www.hrbcm.edu.cn
http://www.hrbzzy.edu.cn
http://www.dfxy.edu.cn
http://www.hxci.edu.cn
http://www.qqe.edu.cn
http://www.hiu.edu.cn
http://www.hfu.edu.cn
http://www.hip.edu.cn
http://www.hgsxy.edu.cn
http://www.feuedu.cn
http://www.hjcu.edu.cn
http://www.kllyxy.edu.cn
http://www.hgsxy.edu.cn
http://www.hwd.edu.cn
http://www.qqhrtc.edu.cn
http://www.ycvc.edu.cn
http://www.mdjdx.edu.cn
http://www.hljp.edu.cn
http://www.hljcat.edu.cn
http://www.hljart.edu.cn
http://www.dqvc.edu.cn
http://www.hljlzy.edu.cn
http://www.hljnzy.edu.cn
http://www.hngzy.edu.cn
http://www.hnzy.edu.cn
http://www.hljpolice.edu.cn
http://www.hgss.edu.cn
http://www.hljdl.edu.cn
http://www.htzy.edu.cn
http://www.dxalzy.edu.cn
http://www.hljnjj.edu.cn
http://www.hljsc.edu.cn
http://www.hljga.edu.cn
http://www.hljlyzy.edu.cn
http://www.hljst.edu.cn
http://www.hljny.edu.cn
http://www.qthzy.edu.cn
http://www.hljminzu.edu.cn
http://www.dqyxy.edu.cn
http://www.hljjt.edu.cn
http://www.hljys.edu.cn
http://www.hljkj.edu.cn
http://www.jmszy.edu.cn
http://www.hljhl.edu.cn
http://www.hrbys.edu.cn
http://www.hljbx.edu.cn
http://www.hrbcmzy.edu.cn
http://www.hrbcszy.edu.cn
http://www.sjms.edu.cn
http://www.hrbyszy.edu.cn
http://www.qqlg.edu.cn
http://www.hbfh.edu.cn
https://www.imu.edu.cn/
https://www.imust.edu.cn/
https://www.imut.edu.cn/
https://www.imau.edu.cn/
https://www.immc.edu.cn/
https://www.imnu.edu.cn/
https://www.imun.edu.cn/
https://www.cfxy.edu.cn/
https://www.imufe.edu.cn/
https://www.hlbrc.edu.cn/
https://www.jntc.edu.cn/
https://www.htxy.edu.cn/
https://www.hmxy.edu.cn/
https://www.imac.edu.cn/
https://www.oit.edu.cn/
https://www.nmgjcxy.edu.cn/
https://cyxy.imu.edu.cn/
https://www.hdwlc.edu.cn/
https://www.imcac.edu.cn/
https://www.btzy.edu.cn/
https://www.xazy.edu.cn/
https://www.hhvc.edu.cn/
https://www.btqgzyjsxy.edu.cn/
https://www.imeic.edu.cn/
https://www.nmgjd.edu.cn/
https://www.nmghgzy.edu.cn/
https://www.nmgjx.edu.cn/
https://www.xlglvc.edu.cn/
https://www.nmtyzy.edu.cn/
https://www.wlcbzyxy.edu.cn/
https://www.tlzy.edu.cn/
https://www.kqysxy.edu.cn/
https://www.nmjtzy.edu.cn/
https://www.btgzy.edu.cn/
https://www.whvtc.edu.cn/
https://www.bttdzy.edu.cn/
https://www.wlcbzyz.edu.cn/
https://www.ordosvc.edu.cn/
https://www.hlbzy.edu.cn/
https://www.mzlry.edu.cn/
https://www.cfgyzy.edu.cn/
https://www.alszyjsxy.edu.cn/
https://www.nmgmy.edu.cn/
https://www.ordossthj.edu.cn/
https://www.zltvc.edu.cn/
https://www.cfyyc.edu.cn/
https://www.nmgfzxy.edu.cn/
https://www.nmgkzy.edu.cn/
https://www.nmgbf.edu.cn/
https://www.cfzyedu.cn/
https://www.nmgjmy.edu.cn/
https://www.nmggyzy.edu.cn/
https://www.nmgnyzy.edu.cn/
https://www.nmgmszy.edu.cn/
http://www.sdpei.edu.cn/

"""

# 将多行字符串分割成列表
urls = urls.strip().split("\n")


# 检查网站是否响应式的函数
def check_responsive(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')

        # 查找<meta>标签，检查是否有viewport属性来判断是否为响应式设计
        if soup.find('meta', attrs={'name': 'viewport'}):
            return "响应式网站"
        else:
            return "非响应式网站"
    except Exception as e:
        return f"无法访问: {e}"


# 批量检查每个网址的响应式状态并导出结果
results = []
batch_size = 5  # 每次保存5条数据

output_file = "website_check_results.xlsx"

# 检查每个网址
for index, url in enumerate(urls):
    result = check_responsive(url)
    results.append([url, result])
    print(f"网址: {url}, 结果: {result}")

    # 每处理完5条数据，就保存一次
    if (index + 1) % batch_size == 0 or (index + 1) == len(urls):
        # 创建 DataFrame
        df = pd.DataFrame(results, columns=["网址", "结果"])

        # 如果文件不存在，创建新文件并写入
        if not os.path.exists(output_file):
            df.to_excel(output_file, index=False)
        else:
            # 如果文件存在，使用 openpyxl 追加数据
            with pd.ExcelWriter(output_file, engine='openpyxl', mode='a', if_sheet_exists='overlay') as writer:
                df.to_excel(writer, index=False, header=False, startrow=writer.sheets['Sheet1'].max_row)

        print(f"已保存 {len(results)} 条数据到 {output_file}")

        # 重置结果列表，以便下一个批次使用
        results = []
