import requests
import pandas as pd
from bs4 import BeautifulSoup
import os

# 学校网址（以多行字符串的方式）
urls = """
http://3g.ahmodern.cn/index.php
http://byhvatc.com/
http://cswcxyedu.cn/
http://feiyang.zhijiaow.com/
http://gaxy.ahpc.edu.cn/
http://gdmzvtc.edu.cn/
http://hau.whc.edu.cn/index.htm
http://hlpolice.gov.cn/
http://hnyznc.cn/
http://jgxy.gdsspt.edu.cn/
http://jxzsxy.com/list/2/7497
http://kjxy.bysjy.com.cn/
http://lazyjsxy.net/
http://lyvcct.cn/
http://qit.edu.cn/
http://rzky.com.cn/
http://rzmevc.edu.cn/index.htm
http://ugx23692369.zhongzhao.org.cn/
http://whyyjkxy.edu.cn/
http://www.acac.cn/
http://www.ahjgxy.edu.cn/
http://www.aksgyxy.com/
http://www.bjy.ah.cn/
http://www.bowenedu.cn/
http://www.bszyxy.com.cn/
http://www.ccszkj.com/index.html
http://www.cdzy.cn/
http://www.cfyyzy.cn/
http://www.chaoshan.cn/index.html
http://www.chinahifl.com/
http://www.cjchuanxi.com/
http://www.cjit.edu.cn/
http://www.cnxiaoyuan.com/siteinfo/1588.html
http://www.cnyz.edu.cn/
http://www.cseptc.net/
http://www.csgdjtxy.com/
http://www.csysgz.com/
http://www.cvit.edu.cn/
http://www.cxmtc.net/
http://www.czhkzy.com/
http://www.czjdu.com/
http://www.dcurt.cn/
http://www.dqygz.com/
http://www.dzcmc.com/
http://www.fafl.cn/
http://www.fjdy.net/
http://www.fykxjs.com/
http://www.fzlmxy.cn/
http://www.fzmjtc.cn/
http://www.gdcmxy.edu.cn/
http://www.gdcp.cn/
http://www.gdep.edu.cn/
http://www.gdstpec.edu.cn/
http://www.gdsty.edu.cn/
http://www.geely.edu.cn/
http://www.glhic.com/
http://www.gqkj.com.cn/
http://www.gsysyj.cn/
http://www.gxcvuedu.com/
http://www.gxgcedu.com/
http://www.gxjrxy.com/
http://www.gyhvu.edu.cn/
http://www.gypec.edu.cn/
http://www.gzcsxy.cn/
http://www.gzgsxx.cn/
http://www.gzjtzy.net/
http://www.gzmiec.edu.cn/?s=aaaa&tsrknzhnclr
http://www.gzstvs.com.cn/
http://www.gzzjxy.edu.cn/
http://www.hainhmc.edu.cn/
http://www.hbei.edu.cn/
http://www.hbpem.com/
http://www.hbqcxy.com/
http://www.hbskzy.cn/
http://www.hcft.edu.cn/
http://www.hcvt.cn/
http://www.hdyz.edu.cn/
http://www.hebnzxy.com/
http://www.helc.edu.cn/
http://www.hevute.edu.cn/index.htm
http://www.hgu.cn/
http://www.hhhxy.cn/
http://www.hhvtc.cn/
http://www.hieu.edu.cn/
http://www.hkvts.cn/
http://www.hlbrzy.com/
http://www.hljhlgz.org.cn/
http://www.hljyzy.org.cn/
http://www.hncfs.edu.cn/
http://www.hncpu.com/
http://www.hndq.edu.cn/
http://www.hngeelyedu.cn/
http://www.hnisvc.com/
http://www.hnlgzy.net/
http://www.hnlrzy.cn/
http://www.hnupc.com/
http://www.hnwomen.com.cn/main.htm
http://www.hnxxgs.edu.cn/
http://www.honder.com/
http://www.htxy.net/
http://www.huaue.com/xacsjs/
http://www.hycgy.com/
http://www.hyyzy.com/
http://www.imtvc.cn/index.php
http://www.jingmenga.com/
http://www.jladi.com/
http://www.jlaudev.com.cn/
http://www.jluat.edu.cn/
http://www.juti.cn/
http://www.jxfte.com/
http://www.jxgcxy.com/
http://www.jxtvc.com/
http://www.kmtdzy.cn/
http://www.kzvtc.edu.cn/
http://www.lanzhoutbc.cn/_t4/main.psp
http://www.ljlyzy.org.cn/
http://www.lxxdzy.com/
http://www.lysyxy.com/
http://www.lztdzy.com/
http://www.msykxy.edu.cn/
http://www.ncyscb.com/
http://www.nimt.edu.cn/
http://www.njjku.com/
http://www.njrts.edu.cn/
http://www.nmgmsxy.net/
http://www.nmtyxy.com/
http://www.nxfszs.cn/
http://www.nxszsgm.com/
http://www.nyca.edu.cn/
http://www.nygymy.com/
http://www.ordosvc.cn/
http://www.ovstc.com/
http://www.oxbridge.cn/
http://www.pypcc.edu.cn/
http://www.qcdx.net/
http://www.qicheedu.com/
http://www.qledu.net/
http://www.qzqgxy.com/
http://www.rpc.edu.cn/
http://www.scemvtc.com/
http://www.schk777.com/
http://www.scstc.cn/
http://www.scwxzyxy.cn/
http://www.sdecu.com/
http://www.sdlivc.com/
http://www.sdpu.edu.cn/
http://www.sdwfvc.com/
http://www.sdwhyx.cn/
http://www.shuozhou.gov.cn/ztjs/szszz
http://www.sjmsxy.net.cn/
http://www.skzyxy.com/
http://www.stdusfc.edu.cn/
http://www.svchr.edu.cn/
http://www.svtcc.edu.cn/
http://www.sxbac.net.cn/
http://www.sxcmvc.com/
http://www.sxczyz.cn/
http://www.sxitu.com/
http://www.sxlqzy.cn/
http://www.sxtvi.edu.cn/
http://www.sysy.com.cn/
http://www.tctc.edu.cn/
http://www.tgcep.ceec.net.cn/
http://www.tlfzj.com/
http://www.ttmc.edu.cn/
http://www.tynxy.com/
http://www.uvu.edu.cn/
http://www.vcit.cn/
http://www.wfspxy.edu.cn/
http://www.whgmxy.edu.cn/
http://www.whhxit.edu.cn/
http://www.whkjz.com/
http://www.wsoc.edu.cn/
http://www.wxcu.edu.cn/
http://www.wxnc.edu.cn/
http://www.xiyi.edu.cn/
http://www.xjjsxy.net/
http://www.xjjtedu.com/
http://www.xjyyedu.cn/
http://www.xmafkj.com/
http://www.xmdh.com/
http://www.xnyesz.com/
http://www.xshxy.cn/
http://www.xtyzy.cn/
http://www.xtzy.com/
http://www.xueli9.com/edu516575.html
http://www.xyqczy.com/
http://www.xyvca.edu.cn/
http://www.xztu.edu.cn/
http://www.ybvtc.com/
http://www.ycnzy.com/
http://www.ynarts.cn/
http://www.yqzyjsxy.cn/
http://www.ytqcvc.cn/
http://www.ytwsxx.com/
http://www.ytzyjsxy.cn/
http://www.yxnzy.net/
http://www.zazy.cn/
http://www.zjjcxy.cn/
http://www.zlxy.edu.cn/
http://www.zsxy.gxnu.edu.cn/main.htm
http://www.zxxyedu.com/
http://www.zyedu.org/
http://www.zyrnvc.com/
http://www.zzhvc.com/
http://www.zzhvc.com/
http://www.zzspxy.cn/
http://yngf.zhiye.chaoxing.com/
http://zlgc.nnxy.cn/
https://api.srygz.com/
https://cqu.cqbys.com/teachin/view?id=123441
https://ehall.zbu.edu.cn/ywtb-portal/official/index.html
https://ev.buaa.edu.cn/
https://fzstc.com.cn/
https://gdx.cdgmxy.edu.cn/
https://gztrsjzy.cn/
https://gztyzyxy.com/
https://hnieyy.hnie.edu.cn/
https://jkgc.web2.superchutou.com/
https://jkglx.nxtc.edu.cn/
https://jwc.jxnyi.edu.cn/index.htm
https://jyjx.mdut.cn/
https://kjxy.huat.edu.cn/
https://kjxy.whsu.edu.cn/
https://localsite.baidu.com/site/wjzsorv8/8cd47d9a-7797-42f3-9306-b902ded71161?qaId=1025050&categoryLv1=%E6%95%99%E8%82%B2%E5%9F%B9%E8%AE%AD&efs=1&ch=54&srcid=10014&source=natural&category=%E5%85%B6%E4%BB%96&eduFrom=136&botSourceType=46
https://localsite.baidu.com/site/wjzsorv8/8cd47d9a-7797-42f3-9306-b902ded71161?qaId=3701242&categoryLv1=%E6%95%99%E8%82%B2%E5%9F%B9%E8%AE%AD&efs=1&ch=54&srcid=10014&source=natural&category=%E4%B8%93%E7%A7%91&eduFrom=136&botSourceType=46
https://localsite.baidu.com/site/wjzsorv8/8cd47d9a-7797-42f3-9306-b902ded71161?qaId=4609000&categoryLv1=%E6%95%99%E8%82%B2%E5%9F%B9%E8%AE%AD&efs=1&ch=54&srcid=10014&source=natural&category=%E5%A4%A7%E4%B8%93&eduFrom=136&botSourceType=46
https://localsite.baidu.com/site/wjzsorv8/8cd47d9a-7797-42f3-9306-b902ded71161?qaId=719342&categoryLv1=%E6%95%99%E8%82%B2%E5%9F%B9%E8%AE%AD&efs=1&ch=54&srcid=10014&source=natural&category=%E4%B8%93%E7%A7%91&eduFrom=136&botSourceType=46
https://localsite.baidu.com/site/wjzsorv8/8cd47d9a-7797-42f3-9306-b902ded71161?qaId=727533&categoryLv1=%E6%95%99%E8%82%B2%E5%9F%B9%E8%AE%AD&efs=1&ch=54&srcid=10014&source=natural&category=%E4%B8%93%E7%A7%91&eduFrom=136&botSourceType=46
https://new.gxgj.com/
https://newws.gcac.edu.cn/
https://nhjcxy.edu.cn/
https://nmgjwy.nmbys.cn/
https://pt.gdcvi.edu.cn/
https://sdcc.edu.cn/
https://snevc.cn
https://suiningc.com/
https://tmgxy.edu.cn/
https://top.080210.com/siteinfo/2624.html
https://top.chinaz.com/site_jlxy.nju.edu.cn.html
https://unn.edu.cn/
https://wbws.edu.cn/
https://wlxy.hbnu.edu.cn/
https://wlxy.yangtzeu.edu.cn/
https://www.abc.edu.cn/
https://www.abvc.edu.cn/
https://www.acdt.edu.cn/
https://www.acvtc.edu.cn/
https://www.afc.edu.cn/
https://www.ahavtc.edu.cn/
https://www.ahbvc.cn/
https://www.ahcme.edu.cn/
https://www.ahdy.edu.cn/
https://www.ahgm.edu.cn:443/
https://www.ahip.cn/
https://www.ahptc.cn/
https://www.ahua.edu.cn/
https://www.ahyzxy.cn/6?device=mobile
https://www.ahzyygz.edu.cn:443/
https://www.amtc.edu.cn/
https://www.aqvtc.edu.cn/
https://www.artah.cn/
https://www.arthn.com/
https://www.asotc.cn/
https://www.ausedu.cn/
https://www.avcmt.edu.cn/
https://www.baidu.com/baidu.php?url=a00000KEJeCxDFezEbg-gB1Qt3_dcJANVBJd8Aj4C8qabUHMOGZI60P6YCpdmd56iCiCtFMY9ImI_GePxuMUN6M8PrAWhwc8GjEClDijofdu8kA_P5jI6agShnrHP9Uza4_1bLOHM-jFIiZgwJBpJZJBMAWCDDhFNMiAO5ulRXwD5LzeWt4xlFF-ZuC0ffZFboSiR6bGjkQkZm9XkAmyYlWU0O8V.Db_NR2Ar5Od66u8utovTyKDDUlamrjQslnVdLYfnlbkRreqrFWF8dtRePLm1j8E34PzI15Z_dGtUrzzqMk9vUS_U_DY2yQe_SeoWC_knTx2Em1T1MsSX1j_tT5Vq8Z1LmIMVsSLuMOeZO013x5I9qEu9qEW9tOZjELmISOj4e_5VSyZvq5gVHC3ZHgnmx5x9qEH9Let5MY3xgu9qEdsSxu9qIhZvOQj4qrZxY3IMW9tqvZvqhZvSrZ1LmxUt_5VlT5M33IOu9qXrZ1vmxUqT5o33x5GseO-9qVXZ1en5ol3xgGlG4XdrW6IPIBmo_3vXrexYvI-MHvIIXFBQqS1l51xVkxwPSOOooOPSLjIPSOGWOPgGOeDgeXxCBOU98dNOQojRkvIUe8glnHDgeqMYxhOUBSBUqOOggSUq8AlUqOHZSpEHOvcEvtOw7SLjIJotXBQqSz5NgsIDgeOzoOP-9e51uUrZtdxlDxyAGW_lLLTVOwZfmtL_OSjqECvx21vYFElrjIE__Sgz_OtZtWtdxH3Y5zOtjqa2zzzz1OsIAeBMqEOu8O3__LUSxqSEO_mOY593xS0MOuSWdElIMLOBxhOAzzzzzzzzzzzkh1VhOdlxdOhOxtymoq5lqxet5U7SLtoE1xEvNtZeqMl3_ELq_gOmOQO3cJtAyQqaZKS9SS1PxDOKuYvyyxglOll5YIrrzzz1H3YPLqZuf____1vyyyXngqZqEuSU1YxqBF5zO3Vve6ORCxk5qoVOZ1BqMS1gSnNjSWSL_OP4l5SkDM4xtyeIsxJR53MSdvOW4kX1OuoOZttgtHOpexkt3EuO_dOWSIrelPMfeOsX1tLVOBxtg_ObxEkdOWIkH4Oo4I-gqZOB_____zOYxl5qZSWOwOCOYxl5qZSWIODtx-OcSgyrlAWv3h5USENZg8dkSLOpSHeOlrgZx8SJ-muCyrM_zU-0.U1Yk0ZDq1Sr3vqUf1_iYtqAMFHc3zXeUvBRzriRznQMu1x60TA-W5HD0IjL53eWUdVjrkQH1YpxFl_xo15ytO6KGUHYznWR0u1dEugK1n0KdpHdBmy-bIfKspyfqn1T0mv-b5H00UgfqnHDsPHKxnH0krNtknjDLg1csPH7xn1msnfKopHYs0ZFY5HDdPsKBpHYkPH9xnW0Yg1bsn6KVm1YknH0dn7tknjD4g1DsnHIxnW0dnNts0Z7spyfqP0Kkmv-b5Hb10ZFMIA7M5H00Uh7GujYs0A49IZ0qn0KWIyfqPjc4nWb3PWn10A7B5HKxn0K-ThTqn0KsTjYs0A4vTjYsQW0snj0snj0s0AdYTjYs0AwbUL0qn0KzpWYs0Aw-IWdsmsKhIjYs0ZKC5H00ULnqn0KBI1Ykn0K8IjYs0ZPl5fK9TdqGuAnqTZnVuLGCXZb0pywW5R9rf6KspZw45fKYmgFMugfqn17xn1DYg1Dsn1R0IZN15HDvPjc3n1RLP10drjcsPHRdrHf40ZF-TgfqnHTYn1nzPj6vnWT1n6K1pyfqrHPhujK-Phmsnj6Yuhc3u0KWTvYqrHFAnDujwj61wHDYPYcLw0K_mMnqn0K9m1Yk0ZK85H00TydY5H00Tyd15H00uANYgvPsmHYs0ZGY5H00UyPxuMFEUHYsg1Kxn7tsg100uA78IyF-gLK_my4GuZnqP1ndnjRLndtsg1Kxn7ts0ZK9I7qhUA7M5H00uAPGujYs0ANYpyfqQHD0mgPsmvnqn0KdTA-8mvnqn0KkUymqn0KhmLNY5H00pgPWUjYs0A7buhk9u1Yk0Akhm1Ys0AwWmvfq0Zwzmyw-5HmLnj6sn6KBuA-b5HD4wWTdnRczwWIKnWDznHRdnjP7njTsPYm1wRD1Pbnk0AFY5Hn0Uv7YI1Ys0AqY5HD0ULFsIjYzc10WnHTWnH0snan1PHTYnWT1PH0Yc16snj0sc16snj0sQW0snj0snan1c1Dsnj0WnankransQW01rHRdninkQW0snj0snankc10WnHRsnj0sQW0snj0snansc10Wnansc1DWnans0AF9UhV9mvnqnHb4nankrHnkc1D4rH0WnHfvnsK3TLwd5Hnsn1nsnHc40Z7xIWYsQW0sg108njKxna3sn7tsQW0sg108njKxn7tsQW0sg100mMPxTZFEuA-b5H00ThqGuhk9u1YY0APv5fKGTdqWTADqn0KWTjYs0AN1IjYs0Z7MIvfqn0KETjDqnW030ZKsPjYkn0KWThnqPH0dnHR&us=newvui&xst=mWYkrRmLPH7anbmLfHcknWDdPH01wH0LnjIAnYNKn1ujnf715HDsPWm1PWbdn1mzPHbvnjTvPjc4g1czPNts0gTq1Sr3vqUf1_iYtqAMzXoZlt1dE53KTHL53eWUdVjrkQH1YpTCzXeUvBb68IMPS07d5Hnsn1nsnHc40gfqnHTYn1nzPj6vns7VTHYs0W0aQf7Wpjdhmdqsms7_IHYs0yP85yF9pywd0gFY5H0Kn1n1PHcLrjmsP0&cegduid=n101n10knWb&solutionId=2912034&word=&ck=0.0.0.0.0.0.0.0&shh=www.baidu.com&sht=baidu
https://www.baidu.com/baidu.php?url=a00000KEJeCxDFezEG9Rjx4JjZNEzPAq20iD_2emEvdZOsipGMfP9Iz_UB_rrzik5ua8PdOIi4JvLt5uch5goaP-Azs-c4LbWchwBlObmRSw22XxQM4McH0tuyKOElP79xQyK-t8tL53yM566wbCkn-GKEL3g20hPC81eM6SLDrt5QcoZ7NuRoW-yYwlcygJztkR5LSkkVGj-5vGnr_1UDYtVl3t.7R_iNTZ-snknsYDfuQnMHec_EwC6eOESLeOVSx4TqgKgYSEVSOzOvTtTrxtLs4OSkOs5ot_XxOOLS5sSEOOo5b__enMWuuugELImtHZW8tpqOZoZfudnXnreuumMWu3erPhecheIELtpYevUVdXVMFudW89Cq8FWvOodwdeVTxVOvEbSOSW-kLeEJGyAp7BEk3vNJ0.U1Yk0ZDq_thvEPQ3YPrSkogJ8I10eIAMdQC-nWa4vTL30ZKGm1Ys0Zfq_thvEPQ3YPrSkogJ8I10eIAMdQJOEPZf_oM5_Qj60A-V5HczPfKM5yq-TZnk0ZNG5yF9pywd0ZKGujY1PsKWpyfqn0KVIjY1nHcsg1DsPjwxnH0krNtknjDLg1csPH7xn1msnfKopHYs0ZFY5HDdPsKBpHYkPH9xnW0Yg1bsn6KVm1Y1nHcsg1DsPjwxnH0krNtknjDLg1csPH7xn0KkTA-b5Hc30Z7WpyfqnWcv0ZFMIA7M5HD0Uh7GujYs0A49IZ0qn0KWIyfqPHn3rHTYPHD0mycqn7ts0ANzu1Ys0ZKs5H00UMus5H08nj0snj0snj00Ugws5H00uAwETjYs0ZFJ5H00uANv5gKW0AuY5H00TA6qn0KET1Ys0AFL5HDs0A4Y5H00TLCq0A71gv-bm1dsTzdMXh410A-bm1dcHbc0TA9YXHY0IA7zuvNY5Hnkg1nkP7tzP0KYIgnqnH0kP1bzPjT4rjRvPj0zPWfYP1T0ThNkIjYkP1f1n1c4PHcdnjck0ZPGujdhPjTLPW9WnW0snWNhnHcv0AP1UHY4nbmswbPDrjP7nHfLfWID0AkBT1Ys0A7W5HD0TA3qn0KkUgfqn0KkUgnqn0KbugwxmLK95H00XMfqn0KVmdqhThqV5HKxnH0YP-tsg1Kxn7ts0Aw9UMNBuNqsUA78pyw15HmdPWn3nWKxPWRvn16zn7tsg1Kxn7ts0ZK9I7qhUA7M5H00uAPGujYs0ANYpyfqQHD0mgPsmvnqn0KdTA-8mvnqn0KkUymqn0KhmLNY5H00pgPWUjYs0A7buhk9u1Yk0Akhm1Ys0AwWmvfq0Zwzmyw-5H00mhwGujYkrRmLPH7anbmLfHcknWDdPH01wH0LnjIAnYNKn1ujnfKEm1Yk0AFY5Hn0Uv7YI1Ys0AqY5HD0ULFsIjYzc10WrHcWnzn1PHnkPWm1PjcLc1Rznj0sc1Rznj0sQW0snj0snan1c1nWnanVc108njn4PHRkc1D8nj0snj0sc1DWnansQW0snj0snansc10Wnansc10Wnans0AF9UhV9mvnqnWbYc1c4PanzrHfWnWDv0Z91IZRqn1mkPHb1PH60TNqv5H08n1Kxna3sn7tsQW0sg1RsQW0sg16sQW0sg1Dzr7tsQW0sg1Dzr0KBTdqsThqbpyfqn0KzUv-hUA7M5Hf0mLmq0A-1gvPsmHYs0APs5H00ugPY5H00TyILujYs0AqsnHYkPjf0TZ0Y5HDs0APzm1Ydn1Ddn0&us=newvui&xst=mWYkrRmLPH7anbmLfHcknWDdPH01wH0LnjIAnYNKn1ujnf715HDLPWDdPWm1PWf4rHD3PjDdnHfzg1czPNts0gTq_thvEPQ3YPrSkogJ8I10eIAMdQJOEPZf_oM5_Qj60gDq_thvEPQ3YPrSkogJ8I10eIAMdQC68IMPS07d5HnvnHR4n1R30gfqnHTYn1nzrHRzPf7VTHYs0W0aQf7Wpjdhmdqsms7_IHYs0yP85yF9pywd0gFY5HDKnWnYPWDvnjDLnf&cegduid=n1mkPHb1PH6&solutionId=14872477&word=&ck=0.0.0.0.0.0.0.0&shh=www.baidu.com&sht=baidu
https://www.baiyunu.edu.cn/
https://www.bcurt.ac.cn/
https://www.bcvit.cn/
https://www.betltc.edu.cn/
https://www.bgypt.edu.cn/
https://www.bhkyxy.com/
https://www.bhlgxy.cn/
https://www.bidizhaobiao.com/public/hebdlzyjsxy
https://www.bijiemc.cn/
https://www.bjgzy.cn/
https://www.btc.edu.cn/
https://www.btqy.edu.cn/
https://www.btsvc.edu.cn/
https://www.bttmskzy.edu.cn/
https://www.bttzy.cn/
https://www.bxait.cn/
https://www.byau.edu.cn/
https://www.bzu.edu.cn/
https://www.cap.edu.cn/
https://www.caskm.cn/
https://www.ccdlvtc.com/
https://www.cct.edu.cn/zh
https://www.ccufe.edu.cn/
https://www.cczjxy.com/
https://www.cdgmxy.edu.cn/
https://www.cdisu.edu.cn/
https://www.cdp.edu.cn/
https://www.cfgy.cn/
https://www.cfxy.cn/
https://www.changdian2001.com/
https://www.chinaschool.com.cn/i_region/i_11_zhejiang/b_6/b_6.html
https://www.chinaschool.com.cn/i_region/i_15_shandong/b_49/b_49.html
https://www.chinaschool.com.cn/i_region/i_25_yunnan/b_36/b_36.html
https://www.chinaschool.com.cn/i_region/i_31_xinjiang/b_19/b_19.html
https://www.ciit.edu.cn/
https://www.cjpt.edu.cn/
https://www.cnsnvc.edu.cn/
https://www.cntcvc.com/
https://www.csit.edu.cn/main.htm
https://www.cuggw.com/
https://www.cuhf.edu.cn/
https://www.cukm.edu.cn/
https://www.cusx.edu.cn/
https://www.cxtc.edu.cn/
https://www.cyprxy.edu.cn/
https://www.czcvc.net/
https://www.czxy.com/
https://www.czzy.cn/
https://www.czzy-edu.com/
https://www.dcc.edu.cn/
https://www.dgcu.edu.cn/
https://www.dkyaolan.com/
https://www.dqsy.net/
https://www.dqzyxy.net/
https://www.dtmtxy.cn/
https://www.dtsz.edu.cn/
https://www.dxalu.org.cn/
https://www.dxvtc.edu.cn/
https://www.dykj.edu.cn/
https://www.dynky.cn/voc/
https://www.fareast-edu.net/
https://www.fjbu.edu.cn/
https://www.fjipe.cn/
https://www.fjlzy.com/index.htm
https://www.fjmzw.com/
https://www.fjsdxy.com/
https://www.fjsmu.edu.cn/
https://www.fjvcb.cn/
https://www.forerunnercollege.com/gfc/
https://www.fpnu.edu.cn/
https://www.fylgedu.com/
https://www.fzacc.com/
https://www.gavtc.cn/
https://www.gcp.edu.cn/
https://www.gcu.edu.cn/
https://www.gdafc.edu.cn/
https://www.gdatv.edu.cn/
https://www.gdbtu.edu.cn/
https://www.gdddc.edu.cn/
https://www.gdgm.edu.cn/
https://www.gdiet.edu.cn/
https://www.gdjdxy.edu.cn/
https://www.gdjpvc.edu.cn/
https://www.gdpi.edu.cn/
https://www.gdpnc.edu.cn/
https://www.gdpt.edu.cn/
https://www.gdust.edu.cn/
https://www.gdvtc.com/
https://www.gdwlxy.edu.cn/
https://www.gfxy.com/
https://www.ghu.edu.cn/
https://www.gkd.edu.cn/
https://www.gmu.cn/
https://www.gnhvc.edu.cn/
https://www.gnun.edu.cn/
https://www.gscat.edu.cn/
https://www.gsjcxy.edu.cn/
https://www.gsjdxy.edu.cn/index.htm?ivk_sa=1024320u
https://www.gtcfla.edu.cn/
https://www.gues.edu.cn/
https://www.gxart.cn/
https://www.gxjsxy.cn/
https://www.gxkjzy.com/
https://www.gxltu.edu.cn/
https://www.gxnrvtc.edu.cn/
https://www.gxnun.edu.cn/
https://www.gxsdxy.cn/
https://www.gxtic.edu.cn/
https://www.gxuie.cn/
https://www.gxxd.net.cn/
https://www.gyiist.edu.cn/
https://www.gzasc.edu.cn/
https://www.gzccc.edu.cn/
https://www.gzdhxy.edu.cn/
https://www.gzdsxy.org.cn/
https://www.gzhlxy.edu.cn/
https://www.gzist.edu.cn/
https://www.gzjszy.cn/
https://www.gzmdrw.cn/
https://www.gzmhxy.cn/index.html
https://www.gzmhxy.cn/index.html
https://www.gznyzyxy.cn/
https://www.gzptc.edu.cn/
https://www.gzqy.cn/
https://www.gzsport.edu.cn/
https://www.gzspzy.cn/
https://www.gzst.edu.cn/
https://www.gzsu.net/list/4231
https://www.gztcme.cn/
https://www.gztzy.edu.cn/
https://www.gzws.edu.cn/
https://www.gzyyxy.com/
https://www.habeihang.com/
https://www.hagmc.edu.cn/
https://www.hayouzhuan.org.cn/
https://www.hbasstu.net/
https://www.hbc.edu.cn/
https://www.hbcollege.com.cn:443/p1/index.html
https://www.hbdfxy.cn/
https://www.hb-green.com/
https://www.hbhvc.edu.cn/
https://www.hbjhart.cn/
https://www.hbliti.edu.cn/
https://www.hbly.edu.cn/
https://www.hbmzu.edu.cn/
https://www.hbou.cn/
https://www.hbsy.cn/
https://www.hbtyzy.com/
https://www.hbucm.edu.cn/
https://www.hbxgmgpi.edu.cn/
https://www.hbxtzy.com/
https://www.hcc.edu.cn/
https://www.hceb.edu.cn/
https://www.hciit.edu.cn/
https://www.hcrt.edu.cn/
https://www.hdkz.edu.cn/
https://www.hebpu.edu.cn/
https://www.hebuee.edu.cn/
https://www.hebuet.edu.cn/
https://www.henz.edu.cn/
https://www.hezevc.edu.cn/
https://www.hfjjxy.edu.cn/
https://www.hfpec.edu.cn/
https://www.hfstu.cn/
https://www.hfue.edu.cn/
https://www.hgtc.org.cn/
https://www.hhdu.edu.cn/
https://www.hibu.edu.cn/
https://www.hict.org.cn/
https://www.hinsrc.edu.cn/
https://www.his.edu.cn/
https://www.hljsfjy.org.cn/
https://www.hljys.cn/
https://www.hltn.edu.cn/
https://www.hmlc.edu.cn/
https://www.hmxxy.com/
https://www.hnasatc.edu.cn/
https://www.hnaues.com/
https://www.hncsut.cn/
https://www.hnebp.edu.cn/
https://www.hngczy.cn/
https://www.hngfxy.com/
https://www.hngsxy.com/
https://www.hngsxy.com/index.html
https://www.hnhvc.edu.cn/
https://www.hnjs.edu.cn/
https://www.hnjt.edu.cn/
https://www.hnmeida.com.cn/
https://www.hnnvc.edu.cn/
https://www.hnptc.edu.cn/
https://www.hnqczy.com/Index.html
https://www.hnshzy.cn/
https://www.hnslsdxy.com/
https://www.hnstx.com/
https://www.hntbc.edu.cn/
https://www.hntyxy.net/p1/index.html
https://www.hnucc.com/
https://www.hnvc.net.cn/
https://www.hnvcc.edu.cn/
https://www.hnvist.cn/
https://www.hnwmxy.com/index.html
https://www.hnwmxy.edu.cn/
https://www.hnxtjyxy.com/
https://www.hnxxc.com/
https://www.hnyszy.com.cn/
https://www.hrbmcc.com/
https://www.hsjkkjzyxy.cn/
https://www.hsvch.cn/
https://www.huas.edu.cn/
https://www.huuc.edu.cn/
https://www.huwai.edu.cn/
https://www.hwec.edu.cn/
https://www.hxci.com.cn/
https://www.hykjxy.cn/
https://www.hylgzyxy.cn/
https://www.hyyesz.com/
https://www.hzevc.edu.cn/
https://www.hzgrys.net/collinfo/2887.html
https://www.imaa.edu.cn/
https://www.imnc.edu.cn/
https://www.imvtcc.edu.cn
https://www.ivt.edu.cn/
https://www.jlcsxy.com/
https://www.jlenu.edu.cn/
https://www.jlhtedu.com/
https://www.jljcxy.com/
https://www.jlthedu.com/
https://www.jnnu.edu.cn
https://www.jsafc.edu.cn/
https://www.jsahvc.edu.cn/
https://www.jsbc.edu.cn:443/
https://www.jscfa.edu.cn/
https://www.jscn.edu.cn/
https://www.jscu.cn/
https://www.jsei.edu.cn/
https://www.jsfpc.edu.cn/
https://www.jsmc.edu.cn/
https://www.jvic.edu.cn/
https://www.jxaevc.com/
https://www.jxfu.edu.cn/
https://www.jxmtc.com/
https://www.jxslsd.com/
https://www.jxuspt.com/
https://www.jxysedu.com/
https://www.jxytxy.cn/
https://www.jyc.edu.cn/
https://www.jyccc.cn/
https://www.jzcit.edu.cn/
https://www.jzhxy.edu.cn/
https://www.jzxcl.edu.cn/
https://www.jzzy.sx.cn/
https://www.kdvtc.edu.cn/
https://www.kllyxy.com/
https://www.kmhvc.cn/
https://www.kszy.edu.cn/
https://www.kxedu.net/
https://www.lcat.edu.cn/
https://www.lfvtc.cn/
https://www.lfwx.net/
https://www.lfzj.edu.cn/
https://www.lhub.cn/
https://www.lj-edu.cn/
https://www.lksnzyxy.cn/
https://www.llsz.edu.cn/
https://www.lpssy.edu.cn/
https://www.lsgx.com.cn/
https://www.lsnu.edu.cn/
https://www.lszyxy.edu.cn/
https://www.lywhxy.com/
https://www.lzmvc.edu.cn/
https://www.lzwyedu.com/
https://www.lzxk.edu.cn/
https://www.mhkkmzyjsxy.com/
https://www.mku.edu.cn/
https://www.msvtc.edu.cn/
https://www.mtxy.edu.cn/
https://www.mypt.edu.cn/
https://www.nbchs.net/
https://www.nbt.edu.cn/
https://www.ncc.edu.cn/
https://www.ncdyxy.com/
https://www.ncec.edu.cn/main.psp
https://www.ncmc.edu.cn/
https://www.ncvcct.edu.cn/
https://www.ndky.edu.cn/
https://www.neau.edu.cn/
https://www.newyishi.com/
https://www.nfdx.net/
https://www.njnhvc.com/
https://www.njpji.edu.cn/
https://www.nmbfxy.com/
https://www.nmgjdxy.com/
https://www.nmmzyz.org.cn/
https://www.nmpower.cn/
https://www.nmxzy.cn/
https://www.nncat.edu.cn/
https://www.nnvtu.edu.cn/
https://www.nsi.edu.cn/
https://www.nstc.edu.cn/
https://www.nsu.edu.cn/
https://www.nufe.edu.cn/
https://www.nustti.edu.cn/
https://www.nvu.edu.cn/
https://www.nxjy.edu.cn/
https://www.nxtc.edu.cn/
https://www.nxtzy.com.cn/
https://www.ny2000.com/
https://www.nyist.edu.cn/
https://www.nykjzyxydz.com/
https://www.nyvc.edu.cn/
https://www.peixianedu.cn/
https://www.plvtc.cn/
https://www.polus.edu.cn/
https://www.qcuwh.edu.cn/
https://www.qdfa.edu.cn/
https://www.qdhkxy.com/
https://www.qgzxzs.com/edu-about-7978.html
https://www.qhdgzy.com/
https://www.qhxmzy.cn/
https://www.qjmc.edu.cn/
https://www.qlgxy.com/
https://www.qlxyedu.com/
https://www.qmc.edu.cn/
https://www.qnzy.net/
https://www.qqhrit.com/
https://www.qxnvc.edu.cn/
https://www.qyvtc.com/
https://www.qzc.edu.cn/
https://www.qzfzfz.com/
https://www.qzuie.edu.cn/
https://www.qzygz.edu.cn/
https://www.rzvtc.cn/
https://www.sanyau.edu.cn/
https://www.sca.edu.cn/
https://www.scac.edu.cn/
https://www.scasc.cn/
https://www.scavc.com/
https://www.scc.edu.cn/
https://www.scctcm.edu.cn/
https://www.sccvc.com/
https://www.scetop.com/
https://www.scmvc.cn/
https://www.scpcfe.cn/
https://www.scsc.edu.cn/
https://www.sctbc.net/
https://www.sczszw.com/wenti/1492150.html
https://www.sdbky.cn/
https://www.sdcivc.edu.cn/
https://www.sdipct.edu.cn
https://www.sdjnwx.com/
https://www.sdse.cn/
https://www.sdshxy.cn/index.html
https://www.sduc.edu.cn/index.htm
https://www.sdvcst.edu.cn/
https://www.sdwcvc.edu.cn/
https://www.sdwm.cn/
https://www.sdwu.edu.cn/
https://www.seig.edu.cn/
https://www.sepc.edu.cn/
https://www.sgmart.edu.cn/
https://www.shaolinkungfu.edu.cn/
https://www.shzv.edu.cn/
https://www.shzvce.cn/
https://www.sjzevc.com/
https://www.sjzjjxy.com/
https://www.slu.edu.cn/
https://www.smu.edu.cn/
https://www.smxpt.cn/
https://www.snbc.edu.cn/
https://www.sntcc.cn/
https://www.snvce.edu.cn/
https://www.sqmc.edu.cn/
https://www.sqsf.cn/
https://www.sru.edu.cn/
https://www.suet.edu.cn/
https://www.svccc.net/
https://www.swut.edu.cn/
https://www.sxct.edu.cn/
https://www.sxfu.cn/index.htm
https://www.sxgkd.edu.cn/
https://www.sxhvc.com/
https://www.sxhvc.com/
https://www.sxie.edu.cn/
https://www.sxist.edu.cn/
https://www.sxjdzy.cn/
https://www.sxjzit.edu.cn/
https://www.sxpolice.org/
https://www.sxptc.com/Home/List/1?page=5
https://www.sxqzy.com/
https://www.sxshxy.cn/
https://www.sxtwedu.com/
https://www.sxycys.com/
https://www.sxyqsz.cn/
https://www.sxyz.com/
https://www.szcp.edu.cn/
https://www.szhct.edu.cn/
https://www.szhkxy.edu.cn/
https://www.szpu.edu.cn/
https://www.sztczyjsxy.com/
https://www.szvtc.cn/
https://www.szys.net/
https://www.tarp.edu.cn/
https://www.tccu.edu.cn/
https://www.thyyjkzyxy.org.cn/
https://www.tmi.edu.cn/
https://www.topflying.com.cn/
https://www.tzvcst.edu.cn/
https://www.uor.edu.cn/
https://www.wfhgzxy.edu.cn/
https://www.whavc.com/
https://www.whinfo.cn/
https://www.whmvc.net/
https://www.whpa.cn/
https://www.whtcc.edu.cn/
https://www.whvtc.net/
https://www.whwl.edu.cn/
https://www.wic.edu.cn:443/
https://www.wids.edu.cn/
https://www.wjtts.net/
https://www.wjut.edu.cn/
https://www.wnzy.net/
https://www.wtc.edu.cn/
https://www.wuhues.com/
https://www.wwoc.cn/
https://www.wynu.edu.cn/
https://www.xahtxy.cn/
https://www.xcevc.cn/
https://www.xcmc.edu.cn/
https://www.xhkjzyxy.edu.cn/
https://www.xhsysu.edu.cn/
https://www.xjbyxy.cn/index.htm
https://www.xjnyedu.com/
https://www.xjsmc.edu.cn/
https://www.xjtzy.net/
https://www.xmgcedu.cn/
https://www.xmht.com/
https://www.xmist.edu.cn/
https://www.xmxc.com/
https://www.xncy.edu.cn/
https://www.xnec.cn/
https://www.xnhkxy.edu.cn/
https://www.xsbnzy.cn/
https://www.xtxnyzyxy.com/
https://www.xvua.edu.cn/index.htm
https://www.xxgc.edu.cn/
https://www.xxmzy.org.cn/
https://www.xxzyjsxy.cn/
https://www.xygczyxy.com/
https://www.xykj.edu.cn/
https://www.xync.edu.cn/
https://www.xzgzy.cn/
https://www.xzvtc.org.cn/
https://www.xzyz.edu.cn/
https://www.ychlxy.com/
https://www.yckjzy.cn/
https://www.ycnxy.com/
https://www.yctu.edu.cn/
https://www.ycyesf.cn/
https://www.yitsd.edu.cn/
https://www.ylnkxy.com/
https://www.yncjxy.com/
https://www.yncpu.net/
https://www.ynczy.edu.cn/
https://www.ynenc.cn/
https://www.ynlg.com/
https://www.ynmec.edu.cn/
https://www.ynqfzyxy.cn/
https://www.ynsvu.edu.cn/index.htm
https://www.yntzy.edu.cn/
https://www.ynucm.edu.cn/
https://www.ynwater.edu.cn/
https://www.ytcc.edu.cn/
https://www.ythealth.edu.cn/
https://www.ytysgz.com/
https://www.yvcct.edu.cn/
https://www.ywicc.edu.cn/
https://www.zbjycn.com/page107?article_id=2521
https://www.zbjycn.com/page107?article_id=3319
https://www.zcmu.edu.cn/
https://www.zhac.edu.cn/
https://www.zhjpec.edu.cn/
https://www.zjcst.edu.cn/
https://www.zjkptc.edu.cn/
https://www.zjyc.edu.cn/
https://www.zltvc.edu.cn/
https://www.zptc.cn/
https://www.zqmc.edu.cn/
https://www.zsthc.com/
https://www.ztbu.edu.cn/
https://www.ztwzy.cn/
https://www.zueb.edu.cn/
https://www.zuel.edu.cn/
https://www.zyfb.com/
https://www.zykqxy.com/
https://www.zzafa.edu.cn/
https://www.zzjc.edu.cn/
https://www.zzlg.org/
https://www.zznu.edu.cn/
https://www.zzsvtc.edu.cn/
https://www.zztrc.edu.cn/
https://www.zzure.edu.cn/
https://www.zzvcae.edu.cn/
https://www.zzyaou.edu.cn/
https://xjgzy.100anquan.com/
https://yhvcedu.cn/
https://zd.nuaa.edu.cn/
https://zhengzhoutiyuan.com/
https://zsc.cfgy.cn/
https://zyyhj.yzpc.edu.cn/
"""

# 将多行字符串分割成列表
urls = urls.strip().split("\n")


# 自动添加 URL 前缀的函数
def format_url(url):
    if not url.startswith(("http://", "https://")):
        return "http://" + url  # 默认加上 http://
    return url


# 检查网站是否响应式的函数
def check_responsive(url):
    formatted_url = format_url(url)  # 确保 URL 有前缀
    try:
        response = requests.get(formatted_url, timeout=5)
        soup = BeautifulSoup(response.text, 'html.parser')

        # 查找<meta>标签，检查是否有viewport属性来判断是否为响应式设计
        if soup.find('meta', attrs={'name': 'viewport'}):
            return "响应式网站"
        else:
            return "非响应式网站"
    except Exception as e:
        return f"无法访问: {e}"


# 批量检查每个网址的响应式状态并导出结果
results = []
batch_size = 5  # 每次保存5条数据

output_file = "website_check_results.xlsx"

# 检查每个网址
for index, url in enumerate(urls):
    result = check_responsive(url)
    results.append([url, result])
    print(f"网址: {url}, 结果: {result}")

    # 每处理完5条数据，就保存一次
    if (index + 1) % batch_size == 0 or (index + 1) == len(urls):
        # 创建 DataFrame
        df = pd.DataFrame(results, columns=["网址", "结果"])

        # 如果文件不存在，创建新文件并写入
        if not os.path.exists(output_file):
            df.to_excel(output_file, index=False)
        else:
            # 如果文件存在，使用 openpyxl 追加数据
            with pd.ExcelWriter(output_file, engine='openpyxl', mode='a', if_sheet_exists='overlay') as writer:
                df.to_excel(writer, index=False, header=False, startrow=writer.sheets['Sheet1'].max_row)

        print(f"已保存 {len(results)} 条数据到 {output_file}")

        # 重置结果列表，以便下一个批次使用
        results = []
